### ISSUE TITLE
Imperative invoker relationships

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#1024]
This is two issues in one:

1. Should it be possible to do `popover.showPopover({invoker: anotherElement})` and have that set the invoker relationship? Reminder: an invoker relationship allows `popover` to be "nested" inside `anotherElement`'s containing popover, and it also fixes up the keyboard tab order so `popover` comes just after `anotherElement`. Both of these happen automatically for `<button popovertarget=popover>`.
2. If the answer to the above is "yes", then what should be done about the [invokers proposal](https://open-ui.org/components/invokers.explainer/)? First, it doesn't connect popovers in the same way that `popovertarget` does (nesting plus keyboard behavior). Second, it doesn't have a proposed imperative API at all, that I know of.

**Comment by lukewarlow** [comment]
> First, it doesn't connect popovers in the same way that popovertarget does (nesting plus keyboard behavior).

I don't fully understand what you're referring to but just wanted to say anything popovertarget does invoketarget should absolutely be doing and it's a spec bug if there's something missing.

**Comment by keithamus** [comment]
1. Passing the invoker is useful, so yes I think it should be possible. 
2. a. As Luke says, if we're aiming to deprecate popovertarget then invoketarget should do the same thing. Arguably it makes sense for invoketarget to fixup tab order in all scenarios and not just for popovers (for dialog it's irrelevant but details/video/input etc?).
  b. I think the imperative API remains as `showPopover`. We could also extend `showModal()` to take `{invoker}`... [TAG did mention a desire to add `invoke(action, invoker)`](https://github.com/w3ctag/design-reviews/issues/920#issuecomment-1989499571) so maybe that should be the direction of travel?

**Comment by tabatkins** [comment]
Oooh, thanks y'all.

For context: I raised this with Mason when exploring switching Bikeshed's info panels (showing information on `dfn` and `a` elements) to using popovers, so I could stop using the roving tabindex hacks to get good tabbing behavior. Unfortunately, you currently only get that focus behavior from a `<button popovertarget>`, which meant I was SOL.

Being able to specify the invoker in the JS call will solve my problems, thanks!

**Comment by lukewarlow** [comment]
@mfreed7 would `popover.showPopover({invoker: anotherElement})` work if the popover is in one shadow root, and `anotherElement` is in another? That would solve part of the issues with popoverTargetElement *not* working that way.

**Comment by mfreed7** [comment]
> @mfreed7 would `popover.showPopover({invoker: anotherElement})` work if the popover is in one shadow root, and `anotherElement` is in another? That would solve part of the issues with popoverTargetElement _not_ working that way.

It certainly *could*, assuming we did **not** create an API to retrieve the invoker. Otherwise, we risk opening access to a shadow root via this mechanism.
