### ISSUE TITLE
[interest invokers] Should we support other forms of link elements?

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#1032]
Currently HTMLAnchorElement, HTMLAreaElement, HTMLInputElement (when in button form), and HTMLButtonElement.

Now for the deep breath.

You'll notice these are all HTML elements.

However, there are anchor elements in other namespace(s).

Should we also support SVGAElement (lovely naming consistency) as an interest invoker? It behaves much the same way as HTMLAnchorElement.

**Comment by lukewarlow** [comment]
The story with MathML and href is much more complicated as @bkardell can attest to, but there's discussions about standardising a MathML `<a>` element too, so any decision here would also apply to that (or whatever element MathML ends up with for links it might be `<mrow>`).

**Comment by lukewarlow** [comment]
Fwiw I implemented it for SVGAElement in chromium locally and it's a trivial change. I made sure to anchor everything to Element not HTMLElement when implementing initially, so it just basically just works.

So I can't see a compelling case against just supporting them?

**Comment by mfreed7** [comment]
Feels like "link-like things" should be supported, if we're supporting `<a>`. So makes sense to me, especially if the implementation didn't pose any issues.
