### ISSUE TITLE
Target minimum size for select

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#1049]
This accessibility document says that pointer inputs must be at least 24x24: https://www.w3.org/WAI/WCAG22/Understanding/target-size-minimum.html

I think we discussed this recently, but someone recently reached out to me about this. Should the button to open the listbox and every option inside the listbox be at least this size? If so, which CSS properties should we use to do this?

**Comment by scottaohara** [comment]
https://github.com/openui/open-ui/issues/1026

**Comment by gregwhitworth** [comment]
Closing based on @scottaohara linking to a prior discussion on this with resolution.
