### ISSUE TITLE
[select] Video in select?

### ISSUE THREAD

**Issue by brechtDR** [openui/open-ui#1108]
I noticed that at the moment, we allow the video tag in the customisable select.
It will also render in current browsers without an issue.

I was wondering if this is safe too use for accessibility reasons. If not, maybe we should set a notice on that.
Not sure if this will ever be possible to be accessible, if not, might be even best not to allow it? 

Love to hear thoughts

[Here is a quick demo](https://codepen.io/utilitybend/pen/gOVmLzz/e54b9ab28c83c0d721cce351ec6ae49f)

In canary:
<img width="276" alt="Screenshot 2024-10-14 at 15 24 23" src="https://github.com/user-attachments/assets/e5754a7a-67fd-4950-956e-9efb46279ecf">

current stable chrome:
<img width="174" alt="Screenshot 2024-10-14 at 15 24 34" src="https://github.com/user-attachments/assets/e4e08eac-b28d-44d8-a1dd-7cb5ab05e15d">

**Comment by brechtDR** [comment]
I just noticed that this is a duplicate of #1099
Closed for now

**Comment by scottaohara** [comment]
Yeah this would be pretty unexpected / likely unwanted from most users, beyond introducing a11y issues.
