### ISSUE TITLE
The utility of the `popover=hint` feature

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#1114]
I'm opening this issue to discuss the utility of `popover=hint`, generally. Note, importantly, that this is separate from the [Interest Invokers](https://open-ui.org/components/interest-invokers.explainer/) feature, and the [related issue](https://github.com/openui/open-ui/issues/1052) about how to handle touch-activation of hovercards. The `popover=hint` feature is an orthogonal part of creating "subordinate" popovers, which don't interfere with existing `popover=auto`'s that are open on the page. The explainer is [here](https://open-ui.org/components/popover-hint.research.explainer), and in particular, [this section describes the exact behavior that `popover=hint` provides](https://open-ui.org/components/popover-hint.research.explainer/#proposal-popoverhint).

There is a formal objection from WebKit/Apple on the spec PR for this feature (https://github.com/whatwg/html/pull/9778#issuecomment-2427908755). While that comment comes with no details, a related comment on the WebKit standards thread (https://github.com/WebKit/standards-positions/issues/305#issuecomment-2284319289) indicates that perhaps the objection is because they feel that `popover=hint` is "tied" to solving [Interest Invokers](https://open-ui.org/components/interest-invokers.explainer/), and they don't want "encourage" tooltips and hovercards in the meantime.

I'd like to use this issue to do two things:
 1. Discuss whether there is utility in a `popover=hint` feature, even if there isn't (yet) an interest-invokers feature.
 2. Discuss the general utility, prevalence, and support for hovercards, tooltips, and other UI patterns that might use `popover=hint`.

**Comment by keithamus** [comment]
It seems like `hint` would be useful for ephemeral floating UI like toasts or notifications. The ability to open a popover that doesn't close other auto popovers, but still has the light dismiss capabilities of auto-style popovers. Having said that toasts/notifications are a little contentious a11y wise.

**Comment by scottaohara** [comment]
similar light dismiss, but not exactly the same, i'd think?

**Comment by sorvell** [comment]
I think it's not unusual to need to present tooltips for *a lot* of elements where it might be desirable to create the ephemeral DOM on demand. Is supporting that robustly a potential goal for this feature?
