### ISSUE TITLE
select: Should `<selectedoption>` update when selecting the already-selected option

### ISSUE THREAD

**Issue by jakearchibald** [openui/open-ui#1119]
This is following up on the resolution of https://github.com/openui/open-ui/issues/825, where the selected `<option>`'s content is only cloned when the selection is changed, and not when the _content_ of the selected `<option>` changes.

Which of the following cases should result in the triggering of the clone operation, even though the result is the same option being selected:

- The user opens the picker and closes it without making a selection
- The user opens the picker and clicks on the `<option>` that is already selected
- `select.value = select.value`
- `select.selectedIndex = select.selectedIndex`
- `select.selectedOptions[0].replaceWith(select.selectedOptions[0])`
- `select.append(document.createElement('optgroup'))`
- `form.reset()`

---

My opinions:

- The user opens the picker and closes it without making a selection

No change. Nothing happened.

- The user opens the picker and clicks on the `<option>` that is already selected

Now I've thought about it, I don't think this should re-clone. [The spec seems a little loose on this](https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-value:~:text=If%20the%20multiple%20attribute%20is%20absent%2C%20and,and%20then%20send%20select%20update%20notifications.) but browser don't fire `change` or `input` when selecting the already selected option, so internally this seems like a no-op.

- `select.value = select.value`
- `select.selectedIndex = select.selectedIndex`

I think these should trigger the cloning operation, since it's an explicit set of the value. Although my feelings on this aren't strong.

- `select.selectedOptions[0].replaceWith(select.selectedOptions[0])`

This should clear the `<selectedoption>` when the selected `<option>` is removed, then trigger the cloning operation when the `<option>` is reinserted.

- `select.append(document.createElement('optgroup'))`

This should not trigger the cloning operation. Nor should adding an `<option>` unless it become the new selected option.

- `form.reset()`

This should trigger the cloning operation only if the selected option changes to another option.

**Comment by sorvell** [comment]
> My opinions:

... seem reasonable.

**Comment by josepharhar** [comment]
> * The user opens the picker and clicks on the `<option>` that is already selected
> 
> Now I've thought about it, I don't think this should re-clone. [The spec seems a little loose on this](https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-value:~:text=If%20the%20multiple%20attribute%20is%20absent%2C%20and,and%20then%20send%20select%20update%20notifications.) but browser don't fire `change` or `input` when selecting the already selected option, so internally this seems like a no-op.
> 
> * `select.value = select.value`
> * `select.selectedIndex = select.selectedIndex`
> 
> I think these should trigger the cloning operation, since it's an explicit set of the value. Although my feelings on this aren't strong.

Making a distinction between these two feels a bit inconsistent to me, but making re-assigning the value from script trigger cloning means that we don't need a separate method to do so.

It looks like the spec already says that assigning to select.value resets a bunch of stuff, so no special casing would be needed for this hopefully:

> On setting, the [value](https://html.spec.whatwg.org/multipage/form-elements.html#dom-select-value) attribute must set the [selectedness](https://html.spec.whatwg.org/multipage/form-elements.html#concept-option-selectedness) of all the [option](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element) elements in the [list of options](https://html.spec.whatwg.org/multipage/form-elements.html#concept-select-option-list) to false, and then the first [option](https://html.spec.whatwg.org/multipage/form-elements.html#the-option-element) element in the [list of options](https://html.spec.whatwg.org/multipage/form-elements.html#concept-select-option-list), in [tree order](https://dom.spec.whatwg.org/#concept-tree-order), whose [value](https://html.spec.whatwg.org/multipage/form-elements.html#concept-option-value) is equal to the given new value, if any, must have its [selectedness](https://html.spec.whatwg.org/multipage/form-elements.html#concept-option-selectedness) set to true and its [dirtiness](https://html.spec.whatwg.org/multipage/form-elements.html#concept-option-dirtiness) set to true.

**Comment by josepharhar** [comment]
Proposed resolution: adopt Jake's suggestions: Clone when re-assigning to select.value, don't clone when user selects the same option again

**Comment by gregwhitworth** [comment]
@josepharhar has the edits for this change landed, since there is the upstream WHATWG PR I'm curious if we need this issue still open.

**Comment by josepharhar** [comment]
Thanks for the reminder, updates here:
- https://chromium-review.googlesource.com/c/chromium/src/+/6086797
- https://github.com/whatwg/html/pull/10633#issuecomment-2536720523
