### ISSUE TITLE
Designer kits for Open UI

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#117]
One of the key principles of Open UI is to get everyone in the industry to begin speaking the same language and having the same fundamental principal of these paradigms. As we've begun to define anatomies and behaviors it dawned on me that it is pretty heavily focused on developers even thought it's discussing UX. This isn't inherently wrong but we have folks that represent design systems in this group.

I was thinking that there may be value for creating out templates in design software (eg: Figma/Sketch/Adobe XD) to give the web designers the same base anatomy and states as that we're standardizing on.

Thoughts?

**Comment by ststimac** [comment]
I like this idea Greg. I'd be happy drive this or collaborate with someone who works on a design system for this.

**Comment by una** [comment]
Is #168 a dupe of this?

**Comment by gregwhitworth** [comment]
@una if sticker kits are the same thing as Figma starter templates. I think that one can be merged into this one if that is indeed the goal.

**Comment by una** [comment]
I think #168 is more broad, to encompass Figma as well as Sketch, etc. No strong feelings on issues, just want to prevent dupes

**Comment by bkardell** [comment]
Given that this issue is approaching 4 years old and hasn't had comment in a really long time - and there is also, as @una suggested a broader 168 - let's close this one.
