### ISSUE TITLE
Updating component definitions

### ISSUE THREAD

**Issue by janechu** [openui/open-ui#122]
# Background

It appears that Open UI is maintaining a list of popular component libraries where it would be better to allow maintainers of these libraries to conform to the JSON schema and export their components definition from their libraries.

If this does not happen we will likely fall out of sync with the libraries as they are updated. An example is that the FAST components are already out of sync, as they have been replaced by web components instead of React and are quite different.

## Proposal

I'd propose the following:
- Document how to prepare a component library with exported JSON definitions
- Document a process on how to get your component library contributed to Open UI

When a component library has exported an Open UI compliant set of JSON definitions we can then add it as a dependency and consume updates to the library as they happen.

**Comment by gregwhitworth** [comment]
This sounds like a great idea! Our JSON schema is in the repo, any chance you can submit a PR for the documentation. We can start having the active Open UI group participants prepare their libs.

**Comment by janechu** [comment]
Will do, and I can also start an effort on the FAST library to export these definitions as well.

**Comment by gregwhitworth** [comment]
Awesome, assigning over to you then @janechu

**Comment by bkardell** [comment]
this is quite old and I'm not sure there is more to do? I'm going to close this, but feel free to reopen and explain where I went wrong if that's incorrect.
