### ISSUE TITLE
[Documentation] Link common contribution markdown files to "Contribute" page

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#127]
Speaking from experience 😅, if you are in the habit of checking README and CONTRIBUTING files in order to learn build steps and project structure/syntax, you may forget that https://open-ui.org/contribute exists.

It would be helpful to include in these files…

* https://github.com/WICG/open-ui/tree/master/research
* https://github.com/WICG/open-ui/blob/master/CONTRIBUTING.md

…a link to the rendered [contribute page](https://open-ui.org/contribute).

The main CONTRIBUTING file looks like WICG boilerplate, so hopefully it is acceptable to just tack on another section to that for the purposes of linking to deeper contribution guidance.

**Comment by andrico1234** [comment]
A little late to the party but added a reference to the site in both the [research's readme](https://github.com/openui/open-ui/pull/503) and the [contributing](https://github.com/openui/open-ui/pull/502)

**Comment by andrico1234** [comment]
Hi @melanierichards , I added your suggestions [here](https://github.com/openui/open-ui/pull/503) and [here](https://github.com/openui/open-ui/pull/502). 

I'll close this issue, but feel free to re-open it if there are any other places we should add links to the contributing page 😄
