### ISSUE TITLE
Add some new component libraries?

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#129]
I don't own or contribute to any of the following component libraries, but they came up in my research for #116 and might be reasonable additions to the list of design systems:

* [Bulma](https://bulma.io/)
* [Foundation](https://get.foundation/index.html)
* [Ionic](https://ionicframework.com/docs): may be slightly less relevant as it targets mobile/desktop apps and paradigms, but uses web technologies (HTML & CSS)
* [UIKit](https://getuikit.com/)

Thoughts? Any additional data/evidence needed in order to determine whether these pass criteria for inclusion?

**Comment by chrisdholt** [comment]
I think if they are building with web technology that satisfies the largest requirements. I'm all for more research here.

**Comment by erikkroes** [comment]
Would https://github.com/ing-bank/lion be a useful addition to this list?

**Comment by gregwhitworth** [comment]
@melanierichards while we're focusing on web tech, we often do look at native platforms and we've heard folks from Windows are beginning to use this. When we get to the events and states we'll probably have to be specific to web libraries but I think if any native component library is able to be ingested that would be valuable as well. Also, I'd like to see Ionic included as well.

**Comment by jouni** [comment]
Hi! Shameless self-promoting, but I think [Vaadin](https://github.com/vaadin/vaadin) could also be included 🤗

**Comment by una** [comment]
How do we promote the owners of these libraries to contribute to Open UI? That feels like the best solution here.

**Comment by devongovett** [comment]
I would be interested in contributing as well. I work on the [Spectrum](https://spectrum.adobe.com) design system at Adobe, and also the [React Aria](https://react-spectrum.adobe.com/react-aria/) library that we use to underpin our React implementation. It's kinda like the model/controller layer without any specific rendering, so I think it is similar in spirit to what Open UI is trying to accomplish. Happy to share what we've learned with this group. I would love for parts of this library to be built into the platform some day! 😄 

How does one get involved here? What are you looking for help with?

**Comment by bkardell** [comment]
I think we should close this as it's been a long time and we have numerous issues around adding, removing or updating component libraries.  Practically speaking I think we need to figure out how to make this more sustainable.  Feel free to re-open if you disagree.
