### ISSUE TITLE
<select> anatomy seems Windows-centric

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#143]
In [MicrosoftEdge/MSEdgeExplainers#361](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/361) @othermaciej raised the following [issue](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/361):

> The proposed anatomy for a includes a part named listbox. <select> elements in macOS Safari (and in the closest matching native macOS controls) don't have a listbox, except in the <select multiple> state; they have a menu. On iPadOS, there's a popover instead. On iOS, it's a list wheel. On iOS and iPadOS, this is true even for the <select multiple> state; they use a checkable list wheel and a checkable popover respectively. I am not sure if the anatomy is meant to encompass the <select multiple> case. Can we name this part of the anatomy something that is suitable for all the different ways this control is presented on different platforms?

The open-ui [anatomy](https://open-ui.org/components/select) is intended to encompass the `<select multiple>` case, but I don't think it's been fully fleshed-out yet; I just opened #142 .

Perhaps we can come up with a term that better encompasses all use cases while still being somewhat descriptive.  Something like "popup" could describe a lot of these cases, but doesn't fit with `<select multiple>` on Windows.

Thoughts?

**Comment by dandclark** [comment]
Thinking about this more, one observation is that the goal isn't necessarily to encompass all the ways that a `<select>` controls are currently presented on different platforms.  There will be some OS-native controls that won't fit the anatomy defined in OpenUI, but web developers creating a custom control based on the OpenUI anatomy probably weren't going to be using the native controls anyway.  Control usage by developers could be divided into two distinct categories:

A) The developer wants to specify the appearance of their control, e.g. to match the styles on the site or match the guidelines of a particular design system.  The developer wants it to look the same across different browsers and OS platforms.  Currently a developer in this category would use a component framework, or just roll their own control.  They aren't using the native controls because those might have drastically different appearances and structures, e.g. the big differences of `<select multiple>` on Windows vs iOS.
B) The developer doesn't need to specify the appearance of the control.  They are fine with it having potentially significant differences in appearance and behavior on different platforms, as long as it still fulfills its basic function.  The cross-platform differences could even be considered an advantage for this developer because they know that the control will have an experience tailored for each platform without any work on their part.

Proposals based on OpenUI like [Enabling Custom Control UI](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md) target only the first category, where the goal is to make life easier for developers who want to specify how their controls look.  Developers in the second category will continue using the default non-customizable `<select>`.

Given that the target audience of [Enabling Custom Control UI](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md) and, I believe, OpenUI as a whole, is developers who are using controls from component frameworks or are writing their own, rather than developers who are using native controls, it need not be a requirement that the OpenUI anatomy encompass all OS-native control implementations.

That said, the `<select>` anatomy shouldn't be overly biased towards any particular current `<select>` implementation; it should instead be a distillation of widely agreed-upon ideas of how a `<select>` should work.   This considers not just OS implementations but browser implementations and those of popular component frameworks like Bootstrap, Ant Design, etc etc.  If folks feel that we're steering the anatomy too close to any given implementation at the expense of others then we should be prepared to correct for this.

**Comment by othermaciej** [comment]
Perhaps `<select>` and `<select multiple>` (and also `<select size=n>` where n > 1, since that also generally has a listbox style presentation) should have distinct anatomy? There doesn't seem to be that much call to style them the same, and the `button` and `selected-value` portions of the anatomy are inapplicable to `<select multiple>`. Even worse, `<select multiple>` does have one or more select values, but they are just different stylings of items in the list, not a distinct slot.

Alternately, or in addition, perhaps the `listbox` portion of the anatomy could just be called `list`, as that is relative neutral to what form of presentation is used, whether a listbox, a popup menu, a popover, a wheel, or something else entirely.

**Comment by gregwhitworth** [comment]
> Perhaps `<select>` and `<select multiple>` (and also `<select size=n>` where n > 1, since that also generally has a listbox style presentation) should have distinct anatomy? There doesn't seem to be that much call to style them the same, and the button and selected-value portions of the anatomy are inapplicable to `<select multiple>`. Even worse, `<select multiple>` does have one or more select values, but they are just different stylings of items in the list, not a distinct slot.

I agree with this completely. I have it on my list to investigate multiple and can agree that the anatomy should be distinct. I have shown that this model can achieve a multiple looks including multiple using Safari's OSX design you can play with here: https://epic-cray-0896e3.netlify.app/src/select/demos/safari-desktop/

**PLEASE NOTE:** That demo is merely testing the general model for styling and behavior/state testing of the anatomy. There are NUMEROUS gaps between a truly complete `select`. Hopefully over time we can get this WC to be a solid complete `<select>` that can be used in production.

> Alternately, or in addition, perhaps the listbox portion of the anatomy could just be called list, as that is relative neutral to what form of presentation is used, whether a listbox, a popup menu, a popover, a wheel, or something else entirely.

Possible. This discussion is happening in the [breadcrumb proposal](https://github.com/WICG/open-ui/pull/165#pullrequestreview-485379830) as the part of breadcrumbs is actually a wrapper on a nav. Would be cool to generalize this in some meaningful way.

**Comment by josepharhar** [comment]
> Alternately, or in addition, perhaps the listbox portion of the anatomy could just be called list, as that is relative neutral to what form of presentation is used, whether a listbox, a popup menu, a popover, a wheel, or something else entirely.

Shall we rename `listbox` to `list` as suggested?
Adding agenda+

**Comment by josepharhar** [comment]
> whether a listbox, a popup menu, a popover, a wheel, or something else entirely.

If `<selectmenu multiple>` doesn't have the same named parts then I think that keeping it as `listbox` is fine because it will always be a popover.

**Comment by josepharhar** [comment]
Closing per resolution
