### ISSUE TITLE
Investigate modal/dialogue element

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#18]
There is an increasing desire/demand for a <dialogue> or <modal> component in the web platform. There is also an [explainer ](https://github.com/adrianhopebailie/modal-window/blob/master/explainer.md)that is geared to addressing needs presented by the Payments WG for other items using a custom <dialogue>. We should ensure that needs outlined by the various design systems is also covered by this solution. The cross origin needs outlined there are real but we should figure out a way to converge the needs so that webdevs aren't having to create a modal/dialogue <N> different ways with different capabilities of styling, extensibility, etc.

**Comment by chrisdholt** [comment]
@gregwhitworth I'd like to take a shot at writing a spec for this. I'm working on a similar issue on our end. Going to self assign.

**Comment by gregwhitworth** [comment]
@chrisdholt is there any plan to keep moving forward with this. cc @melanierichards as I know she's been looking at things like this

**Comment by chrisdholt** [comment]
@gregwhitworth I'll pull up the branch and see if I can get something up in the next week or so. I think I primarily need to update to align with the latest spec template and update a reference for light dismiss to the issue created the other week.

**Comment by melanierichards** [comment]
Happy to coordinate with you on this, @chrisdholt! The work I'm tracking is popups all-up, which includes dialog: #116 Currently planning on a mega-page for popups, and we can discuss as a group how to break that up if needed. AFAICT that's the first instance of nested concepts.

**Comment by chrisdholt** [comment]
@melanierichards would be great to sync on this! Do you want to setup some time next week to walk through what I have currently and we can refine and get a PR out?

**Comment by gregwhitworth** [comment]
@melanierichards @chrisdholt ping

**Comment by keithamus** [comment]
`<dialog>` now exists, and it has a `showModal()` API which shows the given dialog as modal, in the top layer. Congrats everyone!
