### ISSUE TITLE
Using <file> over <input type=file>

### ISSUE THREAD

**Issue by mrmckeb** [openui/open-ui#180]
This issue comes from this comment: https://github.com/WICG/open-ui/pull/140/files#r491263079

@gregwhitworth suggested that the root component could be named `<file>` - which would align with other components, like `<select>`.

Currently the proposal has this as `<input type=file>`.

**Comment by gregwhitworth** [comment]
@mrmckeb mind weighing in on this discussion because it will impact this issue: https://github.com/WICG/open-ui/issues/184

**Comment by andrico1234** [comment]
Based on resolution from [issue 184](https://github.com/openui/open-ui/issues/184):

> Resolved in 01/07/2021 Open UI telcon meeting:
> 
> > Use `openui-` naming for prototyping and web components, and the file name after the prefix alone for native implementation of the components.
> 
> i.e. `<openui-superselect>` and `<superselect>`

Would this need to be updated on the Open UI site before closing?
