### ISSUE TITLE
Slider with tickmarks

### ISSUE THREAD

**Issue by kant2002** [openui/open-ui#227]
In continue to exploration of existign concepts in the UI, on the SAP website there interesting example of slider which is valuable in the UI for engineering/manufactoring applications. See here https://openui5.hana.ondemand.com/entity/sap.m.Slider/sample/sap.m.sample.Slider

The slider presented with tickmarks 

![image](https://user-images.githubusercontent.com/4257079/100540134-8f2b5700-3265-11eb-9b26-9c6a729242b0.png)

Should this be added to the Slider research?

**Comment by una** [comment]
Yes, this would be great to add to the slider research. Could you please open a PR?

**Comment by kant2002** [comment]
Give me some time, and don't be shy to ping me in case I lost somewhere on the internet

**Comment by gregwhitworth** [comment]
@kant2002 friendly ping based on above

**Comment by kant2002** [comment]
Thanks for the ping. I'm not fully ready to do write-up yet. I try to warm-up with small quality of life improvements for myself which allow me to produce something of value.

**Comment by gregwhitworth** [comment]
Duping this to #297
