### ISSUE TITLE
Light dismiss on window blur?

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#241]
Discussed this yesterday with @bocupp-microsoft, @melanierichards, @ipopescu93 but we didn't come to any conclusion on this one.

The definition of "light dismiss" at https://open-ui.org/components/select#light-dismiss states that `<select>` closes when the user hits escape, or when focus moves outside of the listbox due to user action or script.

Should "light dismiss" also occur when blur occurs on the browser window, e.g. when the user switches tabs or changes focus to another application?  In Firefox and Chromium both of these actions cause an open `<select>` listbox to close.  In my own mental model though, these should not cause it to close because in the context of that window, nothing has really changed.  The user has not shown an intent to engage with other content on the page (which would suggest that we should close the popup); instead they've temporarily context switched to some other task.  When they return, the page should be the same as when they left it.

Note, the "light dismiss" definition currently lives inside `<select>` but I expect it to generalize to other control types that have a popup.  See also #240.

Thoughts?

**Comment by una** [comment]
I would argue that switching tabs, or changing focus to another application should **not** lightdismiss. If I were in a select experience, I would want to return to the same state. Some examples:

1. Filling out a form, and the dropdown contains a word I don't know. I change tabs to look it up. I'd want to return to my location.
2. Styling a form UI in open state, switch over to Sketch for comparison. I'd want to return to it open.
3. Selecting a personalization for an item I am purchasing at checkout. I might switch tabs to check the options.

Hope this helps!

**Comment by cathibosco** [comment]
I'd be curious to test this with keyboard navigation use cases - and see if this serves these use cases well.

**Comment by gregwhitworth** [comment]
This was discussed during the call and the following resolution and actions were found:

> RESOLUTION: Popups that support light dismiss will dismiss on window blur 

> ACTION: Greg or Daniel to move light dismiss definition to behavior section of Open UI to allow sharing amongst other popup types.

Minutes can be found [here](https://www.w3.org/2020/12/17-openui-minutes.html#ResolutionSummary)

**Comment by mfreed7** [comment]
So the Popover spec has landed, and it carefully describes what's included in light dismiss. We had many meetings at OpenUI to discuss this, including here in this issue, so I think we can call this "done".
