### ISSUE TITLE
Light dismiss on window resize

### ISSUE THREAD

**Issue by JanMiksovsky** [openui/open-ui#247]
As a tangent to [light dismiss on window blur](https://github.com/WICG/open-ui/issues/241), I propose that light dismiss also occur on window resize.

This is primarily an issue on Windows, which commonly lets a user resize a window even when a system popup is open.

Some precedents on Windows:
* If you open a `<select>` in Chrome/Edge/Firefox/IE and resize the window, the select closes.
* If you open a popup (context menu, toolbar button menu) in various Microsoft Office apps and resize the window, the popup closes.

As with window blur, the fact that the user has switched from the popup to a window resize task can generally be taken as a sign the user may no longer be interested the popup anymore, and the popup can be implicitly dismissed.

There are fewer precedents on macOS, which generally disables window resize with a mouse while a system popup is open. That said, it is possible to resize a window while a popup is open with custom keyboard shortcuts that move a window. And in any event, a web developer has no means of disabling window resize, so it's possible to resize a web browser while a custom popup is open. Given that, it seems reasonable to apply the same default behavior on macOS as well, i.e., have light dismiss occur on window resize.

(Heads up @dandclark and other people working on Chromium browsers: In exploring this on Windows, I found a bug in Edge/Chrome: open a select, press Windows+Left or Windows+Right to resize the window → the window moves, but the select popup can remain visible in the location it had before the window moved.)

If you want to see an example of a web component with a popup that dismisses on window resize, see the demos for [Elix DropdownList](https://component.kitchen/elix/DropdownList).

**Comment by mfreed7** [comment]
Given the age of this issue, and the fact that Popover has shipped without this behavior, I'm going to close the issue. Thanks!
