### ISSUE TITLE
Design survey around lightdismiss behavior

### ISSUE THREAD

**Issue by una** [openui/open-ui#252]
Establish a survey to understand how folks using the web expect to interact with components that have lightdismiss behavior, including but not limited to:

- Lightdismiss behavior when the page is scrolled #240
- Lightdismiss behavior when the page is resized #247
- Lightdismiss behavior when the page is blurred (i.e. another tab/application open) #241

Additional insight:
- OS of the user (might impact expectations)

**Comment by josephrexme** [comment]
I don't know if it's worth adding orientation change explicitly as that will get triggered by resize as there is a possibility for a square shaped device not triggering resize for orientation change

**Comment by una** [comment]
As an FYI, informal poll results: https://twitter.com/Una/status/1352337996310339585?s=20

**Comment by keithamus** [comment]
Ref: https://github.com/whatwg/html/pull/10157
