### ISSUE TITLE
Checkbox/Radio with expandable content

### ISSUE THREAD

**Issue by Malvoz** [openui/open-ui#275]
I came across this issue: https://github.com/w3c/aria/issues/1404 which describes a pattern of checkbox/radio buttons that expand content upon selection. Thought I'd raise an issue since that might be worth considering.

**Comment by scottaohara** [comment]
i'd argue that this is a feature that you'd only want authors to add for very specific situations.  

if this were more commonly available, you'd see more instances of people using checkboxes/radio buttons where disclosure widgets or tabs would be the more appropriate UI/controls to use.

**Comment by mfreed7** [comment]
Based on the comments here, particularly [this one](https://github.com/openui/open-ui/issues/275#issuecomment-1059559580), I'm going to close this issue.
