### ISSUE TITLE
Change URL parameter without Javascript

### ISSUE THREAD

**Issue by alejsanc** [openui/open-ui#276]
On multiple occasions it is necessary to change a parameter of the current URL and reload the page. For example to change the language or the number of results per page. To do this, a &lt;select&gt; element is usually used with the different options and through Javascript the selection change is detected, the parameter changed and the page reloaded. This is something very used, very useful and very simple that the browser could do without using Javascript. It would only be necessary to indicate in the &lt;select&gt; element that its function is to change a parameter of the URL.

Example:

  ```
<select url-parameter="lang"/>
      <option>en</option>
      <option>es</option>

  URL = https://demo.nexttypes.com/?lang=en
```

**Comment by gregwhitworth** [comment]
Thanks for filing @alejsanc - this is effectively getting into a dynamic listbox and something we'll need to discuss and investigate quite thoroughly before we determine solutions. I'm going to lean heavily on the component lib authors that may have tried a declarative approach to this dynamic option creation in the past and I'd be curious if they handle dynamic optgroups. Adding a label and adjusting the title.

**Comment by alejsanc** [comment]
I think there has been an error. My proposal is not about creating options dynamically. It's about changing URL parameters.

I made another proposal that has more to do with that: [Dynamic datalist with searchable JSON source without Javascript](https://github.com/WICG/proposals/issues/23)

**Comment by josepharhar** [comment]
In my opinion, this is not a common enough use case to warrant a declarative feature. I don't see anything wrong with adding script to change the URL and reload the page.

**Comment by alejsanc** [comment]
> In my opinion, this is not a common enough use case to warrant a declarative feature. I don't see anything wrong with adding script to change the URL and reload the page.

It is very common to change the language, the number of results per page, results filters and any other parameter that modifies the presentation. 

for something so simple and useful it should not be necessary to add complexity with javascript

**Comment by jh3y** [comment]
If the goal is to change attributes in the page or the URL. That's pretty much "out of scope" for what the SelectMenu does. It's a <form> control. The behavior of which is defined by the user. There is nothing stopping someone from wrapping it in a <form> and leaning into <form> behavior. But, if you are wanting to make changes to `window.location`, it's going to need JavaScript.

**Comment by LeaVerou** [comment]
While I’m usually all for declarative ways to do common tasks, I agree this is out of scope. Also, there are multiple different ways to apply the result in the URL: `?lang=en`, `en.website.com/`, `website.com/en/` etc.

It is also a one liner to do this with script, so not even a significant abstraction.

**Comment by josepharhar** [comment]
Closing per resolution

**Comment by alejsanc** [comment]
> While I’m usually all for declarative ways to do common tasks, I agree this is out of scope. Also, there are multiple different ways to apply the result in the URL: `?lang=en`, `en.website.com/`, `website.com/en/` etc.

What i have proposed is for url parameters but it can also be done for full urls

<select url/>
    <option>en.website.com/</option>
    <option>es.website.com/</option>

    <option>website.com/en/</option>
    <option>website.com/es/</option>

>It is also a one liner to do this with script, so not even a significant abstraction.

That it can be done with a line of javascript doesn't seem to me a reason not to do it declaratively. Lots of things recently added to HTML and CSS can also be done with javascript.

**Comment by alejsanc** [comment]
> It is also a one liner to do this with script, so not even a significant abstraction.

And it's not just one line, it takes a lot more code to generalize it to multiple parameters. You have to look for all the "url-parameter" elements and add a function that takes the url of the page, modifies the indicated parameter and loads the new url

```
function addEventListeners(rootElement, query, event, eventFunction) {
	var elements = rootElement.querySelectorAll(query);
	for (let element of elements) {
		element.addEventListener(event, eventFunction);
	}
}

function changeURLParameter(event) {
	var select = event.currentTarget;
	var value = select.options[select.selectedIndex].value;
	var parameter = select.getAttribute("data-url-parameter");
	
	var pageURL = new URL(window.location);
	pageURL.searchParams.set(parameter, value);
	window.location = pageURL;
}

addEventListeners(document, "select[data-url-parameter]", "change", changeURLParameter);
```

**Comment by alejsanc** [comment]
> If the goal is to change attributes in the page or the URL. That's pretty much "out of scope" for what the SelectMenu does. It's a
> control. The behavior of which is defined by the user. There is nothing stopping someone from wrapping it in a and leaning into behavior. But, if you are wanting to make changes to `window.location`, it's going to need JavaScript.

It is possible to create a new element. The important thing is the functionality, not what we call it.

```
<url-parameter parameter="lang"/>
    <option>en</option>
    <option>es</option>
```
