### ISSUE TITLE
Form not submitted warning message before unload

### ISSUE THREAD

**Issue by alejsanc** [openui/open-ui#280]
When data has been entered or modified in a form it is convenient to notify the users that they will lose the data if they leave the page without having submitted the form. Currently, to do this, it is necessary to use Javascript to monitor the changes, monitor when the user avandonates the page with the "beforeunload" event and display a warning message. This could be easily done by the browser if it is indicated in a parameter of the form.

`<form show-unload-warning>`

**Comment by keithamus** [comment]
I've moved this over to https://github.com/whatwg/html/issues/10218 which I think is the more appropriate forum to raise this. Sorry for the long delay in a response here.
