### ISSUE TITLE
Handling strange DOM structures in <select>

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#291]
Given that authors can replace arbitrary parts of a compound control like `<select>`, it's possible to create some very odd structures that don't line up with the semantics of the control.  For example:
```html
<select>
  <div slot="button"></div><!-- remove the default button without replacing it -->
  <option slot="listbox-container">
    <!-- This isn't under the listbox part.  What should happen? -->
    <option>Do I get option behaviors?</option>

    <popup part="listbox">
      <button part="button">Do I get button behaviors?</button>
      <option>option?</option>
    </popup>
  </option>
</select>
```

When the behaviors under https://open-ui.org/components/select#events-1 are applied to the specified parts, we could get some surprising results if the tree structure is malformed in this way, e.g. the button part is under the listbox, listbox is under the button, option is outside of the listbox, etc.  User agents trying to handle all such cases will likely result in bugs and interoperability differences.

To sidestep this trickiness, I'd like to consider only applying "controller code" (i.e. behaviors defined in [events](https://open-ui.org/components/select#events-1) and [behavior](https://open-ui.org/components/select#behavior)) to elements as follows:

1. To receive option part controller code, an element labeled as an option must be a descendant of the listbox part in a flat tree traversal.
1. To receive button part controller code, an element labeled as a button must *not* be a descendant of the listbox part in a flat tree traversal.
1.  To receive listbox part controller code, an element labeled as a listbox must *not* be a descendant of the button part in a flat tree traversal.

From (1) and (3) it also follows that an element an only receive option part controller code if it is *not* a descendant of the button part in a flat tree traversal

We could also consider restricting the selected-value part to be only under the button.  But that one is probably less prone to error since it's not user-interactive (the only thing we do with it is write the selected value text). And it might be somewhat reasonable for an author to put the selected-value part outside the button so that it's displayed somewhere else.

Note, I'm only considering single-select here, as the structure for `<select multiple>` will be different.

If we do decide to enact these restrictions, the next question is what should happen if they are not met.  Should the elements in the wrong place just be ignored?  Maybe with a console warning to explain why they didn't receive controller code?  Or should the control not be rendered at all, like when a listbox or option part is missing?

cc @ipopescu93, @melanierichards, @mfreed7

**Comment by mfreed7** [comment]
Thanks for opening this issue. I agree with your limitations - they all seem reasonable, and minimal (i.e. not overly restrictive). Since it seems that we're heading for a situation where breaking some of the rules "breaks" parts of the control, it would seem to me that we should stop rendering the control at all, with a warning, to prevent any usage of the outlawed patterns. Otherwise, authors could ignore (or not notice) the warning, and bake in some dependency on *not* attaching controller code to some parts. Better would be to more-strongly enforce that these conditions are required. But I also understand that this isn't very HTML-y.

This feels like we need developer input on which "error" state is more ergonomic.

**Comment by gregwhitworth** [comment]
Thanks for raising this @dandclark this does seem reasonable to me. Given the change is an expectation on normative text changes. I'm going to add it to the agenda.

**Comment by gregwhitworth** [comment]
This was discussed in today's telecon. No resolution but we expect to have one next week: https://www.w3.org/2021/03/25-openui-minutes.html

**Comment by dandclark** [comment]
This was discussed again in today's telecon, with the resolution:
>Proposed Resolution: When a control has a malformed structure we render the HTML as is but we don't apply the controller code
>
>"apply the controller code" to be defined by dandclark

So I'll suggest a more comprehensive definition here that we can discuss in a future telecon.

<h2>General principles for when an author provides a malformed HTML structure:</h2>

- Render the HTML as-is instead of hiding it or replacing it with an error message.
  - This aligns more closely to how HTML has worked up to this point. It is also more useful to the user to see a broken control than to not see a control at all when one is expected; in the latter case the user might waste time trying to look for it elsewhere on the page.
- Show a warning in the DevTools console giving the author a clear explanation of what is wrong about their HTML structure.
  - Something like: `In <select id="my-select">, controller code was not applied to <option>Choice N</option> because it is not a descendant of a listbox part`.
- Prefer handling errors by simply not applying controller code to the section of the control that is malformed.  Avoid complicated fallbacks and fixups that will be hard to standardize and will lead to interoperability issues.
  - Controller code that tries to be too clever and guesses the author's intention will probably get it wrong in most cases anyway.

<h2>Types of malformed HTML structure and how to handle them:</h2>

For all of the below errors, emit a descriptive console warning when encountered.
These examples all use `<select>`, but most of these rules could be applied to other controls compose of multiple parts.

__Error:__ Multiple instances of a singleton part are provided.
__How to handle it:__ Only apply controller code to the first instance of the part in a [flat tree ](https://drafts.csswg.org/css-scoping/#flat-tree) traversal
__Example:__
```html
<select>
  <div id="button-container" slot="button>
    <div part="button">My button</div> <!-- only this one gets controller code -->
    <div part="button">My other button</div> <!-- this one doesn't get controller code, but it's still visible in the DOM as a normal div-->
  </div>
  <popup part="listbox" slot="listbox">
    <option>Thing 1</option>
    <option>Thing 2</option>
  </popup>
</select>
```

__Error:__ An expected part is missing.
__How to handle it:__ Apply controller code to the parts that are present, but don't attempt any fallback for the parts that are missing. The implementer code for handling such cases should not be any more complicated than a null check (aside from emitting the console warning).
__Example:__
```html
<select>
   <!-- This button will get controller code, e.g. it will get a "button" aria role.
        But clicking it won't open a listbox because none was provided. -->
  <div part="button" slot="button">My button</div>
  <div slot="listbox">
    <!-- Swap out the default listbox, but don't replace it with anything -->
  </div>
</select>
```

__Error:__ A part isn't in the expected ancestor hierarchy.
__How to handle it:__ Don't apply controller code to parts that are not in their expected ancestor hierarchy.
For `<select>`, this means the following:
1. To receive option part controller code, an element labeled as an option must be a descendant of the popup part in a flat tree traversal.
1. To receive button part controller code, an element labeled as a button must not be a descendant of the popup part in a flat tree traversal.
1. To receive listbox part controller code, and element labeled as a listbox must not be a descendant of the button part in a flat tree traversal.

__Example # 1:__
```html
<select>
  <div id="button-container" slot="button>
    <div part="button">My button</div>
    <!-- This option is rendered, but gets no controller code because it isn't in a listbox. -->
    <option>My option</option>
  </div>
  <popup part="listbox" slot="listbox">
    <option>Thing 1</option>
    <option>Thing 2</option>
  </popup>
</select>
```

__Example # 2:__
```html
<select>
  <div id="button-container" slot="button">
    <!-- There is no restriction about putting a part in an arbitrary slot, so controller code is
         is still applied to this popup.  The hierarchy restrictions apply to parts, not slots. -->
    <popup part="listbox" slot="listbox">
      <option>Thing 1</option>
      <option>Thing 2</option>
      <!-- This button doesn't get controller code because it's inside a listbox part. -->
      <div part="button" id="invalid-button">My invalid button</div>
    </popup>
    <!-- This button gets controller code because it's not inside a listbox.  Note that #invalid-button comes
         earlier in the DOM, but doesn't 'count' as a button part because it's under a listbox. So the controller code
         goes to the first eligible button part, which is this one. -->
    <div part="button">My button</div>
  </div>
  <div slot="listbox">
    <!-- Swap out the default listbox so the rest of the example works. -->
  </div>
</select>
```

**Comment by melanierichards** [comment]
This is awesome, thanks for putting the comprehensive definition together @dandclark! These processing rules make sense and could be templatized for application to other controls.

**Comment by josepharhar** [comment]
It doesn't look to me like anything further needs to be done for this issue, so I'm going to close it
