### ISSUE TITLE
Discord link removed from site

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#292]
A merge must have removed the discord link - opening this issue to add it back in.

**Comment by andrico1234** [comment]
This may have been [resolved](https://github.com/openui/open-ui/issues/304).

Both the Discord link in the top bar and the link in the Getting Started section direct to https://discord.gg/DEWjhSw

**Comment by keithamus** [comment]
Looks like this issue has been resolved for a while. If anyone can't access the discord via the site please re-open or file a new one!
