### ISSUE TITLE
Simple design system for Open UI

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#293]
A few weeks back when discussing the `::indicator` pseudo-element there was understanding on how design in general may take a long time to align on. We wanted to show the very basic designs we're planning across at least 10 different components to alleviate concerns of locking in any specific brand/design.

**Comment by gregwhitworth** [comment]
This is being superseded by the other global design system discussions so closing this in favor of those.

**Comment by markcellus** [comment]
Thanks @gregwhitworth. For those of us following this issue, where are the other design system discussions? Is that in this repo?
