### ISSUE TITLE
[Popup] Naming for the new popup element

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#296]
Time for everybody's favorite activity: name bikeshedding! 😄

We recently resolved to take up [the `<popup>` proposal](https://open-ui.org/components/popup.research.explainer) for incubation in this group. On the initial explainer, some folks [felt that the name `popup` could be confusing](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/438), either because it implied a particular directionality and/or because it didn't mesh well with the nomenclature of that person's first language.

As a first step in incubation, let's land on an appropriate name for the proposed element. The name should be generic enough that multiple subclasses of top-layer UI could be built using the element, but specific enough that it can't be confused with another purpose. Here we are talking about transient UI that is displayed in the top layer of a web application; this might be a standalone element (such as a teaching bubble) or part of a composited control (such as a select/combobox's listbox).

Suggestions—and additional discussion on these—from the [original issue](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/438) include:

* float
* floatable
* popover
* positioned
* overlay
* popout
* popper

**Comment by chrisdholt** [comment]
A few generic thoughts off the top of my head. 

**Prefer to avoid (reasoning):**
- float (consider conflicts w/ CSS property of the same name)
- floatable (does this have to do w/ the float CSS property?)
- overlay (similarly named UI constructs such as what partially obstructs the screen behind some modal dialogs - dialog might use this, does that create confusion from an anatomy standpoint in the dialog?)
- popper (completely subjective, I've never liked names ending in "-er")
- positioned (lots of things are positioned, this is just one...somewhat subjective I guess :) )

I'm a fan of `popup` or `popover`.

**Comment by melanierichards** [comment]
+1 to @chrisdholt, my personal opinion (biased, am co-author of the explainer) is that `popover` would be my preference if we move away from `popup`. Feels in spirit with the concept; disambiguated from other concepts; avoids the directionality of "up". A `pop-*` may not cover all other elements, but "over" still seems reasonable given top layer positioning.

**Comment by FezVrasta** [comment]
> * popper (completely subjective, I've never liked names ending in "-er")
> 
> I'm a fan of popup or popov**er**.

😅

**Comment by Westbrook** [comment]
Agree that `popover` is likely the best of the available options at this time. Features none of the possible naming/context collisions other options might run into and for some reason feel more of a single _thing_ than a complete _system_ which aligns well with the idea that only ONE can be open at a time...

I see `overlay` as a close second, as it feels like what this content actually is, an overlay on top of its sibling DOM tree, however I see Chris' point re: the naming of the underlay or backdrop as "overlay" having potential collisions here. `overlay` also feels more like a _system_ than a single _thing_, though maybe simply from it being called as such in libraries I currently work with/build.

**Comment by melanierichards** [comment]
Summarizing discussion, there were some folks who wanted to keep `popup`, some who preferred `popover`, and some feeling that we might want to consider other names as well. Some concerns about whether we are implicating a particular presentation in the naming.

As a next step, I suggested we (I) cycle back to the popup research PR, so we can consider the various different use cases for `<popup>` together and mull over whether there is a name that feels satisfactorily inclusive of these.

**Comment by mfreed7** [comment]
We've moved to a `popup` content attribute approach https://open-ui.org/components/popup.research.explainer, so this issue is now moot.
