### ISSUE TITLE
Noscript element in XHTML

### ISSUE THREAD

**Issue by alejsanc** [openui/open-ui#300]
The HTML standard indicates that the [noscript element must not be used in XML documents](https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element). Even so, browsers like Firefox or Chrome allow it to be used in XHTML pages served as application/xhtml+xml. It is quite a useful element and I think it could be added to the standard for XHTML documents.

**Comment by lukewarlow** [comment]
Not sure OpenUI is really the correct venue for this. Worth raising an issue in whatwg/html
