### ISSUE TITLE
[Navigation Architecture] Rename "Contribute" to "Get Involved"

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#303]
This is a sub-task of #285.

Make sure also that redirects aren't broken.

**Comment by chiranjeevihr** [comment]
Hi, I would like to work on this.

**Comment by andrico1234** [comment]
Hey @chiranjeevihr , I noticed there hadn't been any activity in a couple of weeks. I whipped up a quick MR, but would be more than happy to take it down if you're mid-progress of this item. 

https://github.com/openui/open-ui/pull/337
