### ISSUE TITLE
[Navigation Architecture] Elevate mechanical participation information on Get Involved

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#304]
This is a sub-task of #285.

> Elevate the status of basic mechanical information (joining the CG, the importance of the Discord, getting invites to meetings, the fact that we don't really use mailing lists the way other groups do)

**Comment by andrico1234** [comment]
Hi @melanierichards ,

I'm curious about what `elevate` means in this context. Is it to simply bring the mechanical participating details so they live under a higher heading level?

If this is the case, the page would have two `h2` headings:
- Getting started
- Standardizing an Open UI Web Component

Getting Started would have the basic mechanical information
Standardizing a Open UI Web Component would house the 0-4 stage process of creating a standard


I had something in mind like this, but wanted other's thoughts in case i misunderstood the spec

```
# Getting Involved
We welcome all types of contributions from attending a meeting, to giving feedback, to conducting research, facilitating input gathering, writing a spec and/or implementing a web component. Below is your guide to contributing.

## Getting Started
For those who are new to the OpenUI community we recommend joining our Discord server where we (insert activities here). We also have weekly meeting where we...

## Standardizing an Open UI Web Component
The following guides walks you through the process of bringing a Component from idea to either a standardized Open UI Web Component and/or an implemented feature in a browser.

### 0. Research: Collect Research and share your Idea
#### Why research
Research is a cornerstone of Open UI...
```

I couldn't find any existing copy relating to joining the CG, discord, and meetings. If there's something that already exists, are you able to point me in the right direction and I can use that??


Note: Just to clarify, does CG refer to the WICG?

**Comment by gregwhitworth** [comment]
> I couldn't find any existing copy relating to joining the CG, discord, and meetings. If there's something that already exists, are you able to point me in the right direction and I can use that?

@andrico1234 you hit the nail on the head. We have helping documentation but this makes an assumption you're already a member of the CG.

Here is some content from an email I'll send out to new members to the CG, probably good content to surface:

> Discord server: https://discord.gg/DEWjhSw
> Open UI Github: https://github.com/WICG/open-ui
> Open UI Telecon Agendas: https://github.com/WICG/open-ui/tree/master/meetings/telecon
> Open UI community group: https://www.w3.org/community/open-ui/

And finally, we should reference to DM myself or Una on Discord to be added to the calendar invite. It would be good to expound on this though of why to join those and purpose the tools serve.

**Comment by andrico1234** [comment]
Thanks for the details @gregwhitworth , I'll whip up a PR for this
