### ISSUE TITLE
[Popup] Polyfil / Open UI component

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#312]
On [MSEdgeExplainers #461](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/461), @newtack asked:

> I love the idea of having a native popup and would love to start programming against the API now with a polyfill, which I could remove later on.
> 
> Would this be possible?

Certainly possible, and a great thing for us to take up in Open UI! Transferring the issue here so we can make this part of the Open UI component library.

**Comment by melanierichards** [comment]
I know @samthor was interested in contributing towards a polyfil. Unfortunately we (Edge folks) were/are still working out some kinks in our anchored positioning proposal, and that was a bit of a blocker to complete a polyfil story. Working on getting that published ASAP though!

**Comment by mfreed7** [comment]
Still would be great to have someone write a polyfill for the [Popup API](https://open-ui.org/components/popup.research.explainer). Any takers? I'm willing to assist with any questions about the API or the Chromium implementation.

**Comment by mfreed7** [comment]
We have someone working on polyfills now, so I'm going to close this. More details later.

**Comment by nuxodin** [comment]
I would like to have a look at the polyfill, is the code to be found somewhere?
