### ISSUE TITLE
[Popup] Specify that popups in different documents cannot effect each other

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#318]
Something we didn't call out explicitly in the initial popup explainer but had in mind is that each document has its own top layer stack. Interacting with a popup in one document cannot pop a popup off the stack in another document. This prevents cross-document abuse, e.g. in scenarios where a host document may contain several embedded documents in `<iframe>`s. This issue is a note to self to add this security mitigation explicitly to any spec text.

Refer to [MS Edge Explainers #433](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/433) for background.

In case the question comes up, popups [cannot break out of embedded documents](https://open-ui.org/components/popup.research.explainer#privacy-and-security-considerations):

> Freedom over the size and position of a popup could enable an author to spoof UI belonging to the browser or documents other than the popup’s document. For this reason the popup will be constrained as all other elements of the relevant document are, by clipping the element to the document's layout viewport.

**Comment by mfreed7** [comment]
The comments on this issue seem to contradict the ones on https://github.com/openui/open-ui/issues/319. I.e. https://github.com/openui/open-ui/issues/319 says that we might want to hide popups when the focus leaves their document. This one says one document shouldn't affect another, popup-wise. Generally, I agree with the latter - I think separate documents need to stay separate, and it would be bad to have the popup stack close when either a) focus leaves the document, or b) another popup opens in a separate document.

What am I missing?

**Comment by mfreed7** [comment]
As mentioned here (https://github.com/openui/open-ui/issues/319#issuecomment-1078055183), I believe this is a duplicate and can be closed.
