### ISSUE TITLE
[Popup] Should focus changes between documents clear open popup in a given document?

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#319]
This question refers to use cases where a given host/parent document may contain 1+ embedded documents (e.g. `iframe`d content). Both the parent and embedded documents may have `<popup>`s.

On [MS Edge Explainers #433](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/433), @BoCupp-Microsoft said:

> If focus leaves that active document, because the browser or tab or document lost focus, then I expect its popups to be dismissed.

@domenic mentioned (I believe partially in response to the above comment, please correct me if I'm wrong):

> In general any kind of way in which documents can affect each other is pretty unusual on the web platform, and poses some security and privacy issues. I'd definitely suggest sticking to everything being document-scoped, and not giving any particular document special treatment.

Should loss of focus in a host or embedded document clear that document's open popup from the stack? Examples:

* A user visits a web page where a "teaching UI" popup instructs them how to use some new feature of the website. The user effectively ignores this and immediately clicks into a commenting widget embedded on the page via an `iframe`. Should the teaching UI popup close?
* A user is interacting with a web-based publishing tool composed of several separate `<iframe>`s. They choose an item from a combobox (whose listbox is a `popup`) in iframe A. The user hits the tab key, and immediately passes into iframe B. Should the combobox popup close?

**Comment by melanierichards** [comment]
We should fully consider any privacy-security ramifications and mitigations. From a user experience perspective, I would expect that any popups would be dismissed as focus crosses boundaries between host and embedded documents. Many complex web applications are constructed as "several iframes in a web page suit", and users would be none the wiser as to the implementation. Not light dismissing in these cases could get an application into a weird state where multiple popups are open and displayed simultaneously, and a user wouldn't understand why.

**Comment by mfreed7** [comment]
I believe this is mostly a duplicate of https://github.com/openui/open-ui/issues/415#issuecomment-1072638040, which discusses loss-of-focus being a light dismiss trigger. Given that the [general direction](https://github.com/openui/open-ui/issues/415#issuecomment-1072638040) that issue is going is to light-dismiss on loss of focus, I think we can close this issue. I'll add a comment there, pointing out the specific question of embedded documents.
