### ISSUE TITLE
[Popup] [Light Dismiss] Light dismiss "escape key" should probably include all close signals

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#320]
On [MS Edge Explainers #457](https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/457), @domenic said:

> The popup explainer says
> 
> > An opened popup will have “light dismiss” behavior, meaning that it will be automatically hidden when:
> >
> > - The user hits the escape key,
> 
> @dvoytenko and I have been working on https://github.com/slightlyoff/history_api/blob/master/history_and_modals.md, which is quite related. We believe that this escape key mention should probably be expanded to cover all "close signals", including:
> 
> - <kbd>Esc</kbd> on desktop
> - Android back button
> - Accessibility technology gestures (e.g. [iOS two-finger scrub](https://github.com/WICG/proposals/issues/18#issuecomment-772702386))
> - Maybe even game console buttons
> 
> @natechapin is working on a Chromium implementation of this concept, that so far intercepts both the desktop <kbd>Esc</kbd> key and the Android back button.
> 
> Our plan is to have all parts of the platform which use these close signals, e.g. the fullscreen API or the `<dialog>` element, use a core unified definition. Hopefully `<popup>` will too.
> 
> (Separately, some of the explainer linked above also talks about a `ModalCloseWatcher` class to allow direct developer handling of close signals. But, that would just be another consumer of this core "close signal" concept. The overlap with `<popup>` is about the hopefully-shared concept.)

This should probably go into our shared definition of "light dismiss", which can then be referenced by `<popup>`.

**Comment by mfreed7** [comment]
There already was a reference to close signals, but I [just put up a PR](https://github.com/openui/open-ui/pull/501/files) to replace most "Esc" references with "close signal". I'll get that landed.
