### ISSUE TITLE
[Popup] Should the hide() method be renamed to close()?

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#322]
From the proposal's open questions:

> Show/hide or show/close? This proposal introduces a symmetrical show/hide method pair on the proposed popup element. dialog, however, sets a precedent for a show and close method pairing. That seemed less intuitive, but perhaps the existing pattern should be followed. Alternatively, the platform could introduce hide on dialog and consider close deprecated.

This consistency feedback came up on https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/455

**Comment by markcellus** [comment]
If `close` is used, was `open` considered instead of `show`? Open/close are opposites, so it seems more intuitive imo.

**Comment by melanierichards** [comment]
Thanks @markcellus, we initially proposed `show` and `hide` along the same line of reasoning, in that they make a symmetric linguistic pair. `<dialog>` uses `show` and `close`, and there was interest in creating parity with `<dialog>` lest there be developer confusion from the inconsistencies. Summarizing the options, they are:

1. Take `show` and `close` to align with `<dialog>`.
2. Take a linguistic pair that makes sense together: either `show`/`hide` or `open`/`close`.
3. Optionally to (2), try and bring `<dialog>` in line with `<popup>`, and deprecate (but not remove from the platform) any language that is unaligned.

**Comment by markcellus** [comment]
Ah I see. I'd be in favor of establishing parity between dialog and popup! 👍 

I dont know much about the reasoning behind why show/close was chosen for dialog implementation (I'll have to search the issues there). But it may be worth proposing that dialog be changed to open/close (if that's still possible) and then having popup follow along with that.

**Comment by una** [comment]
+1 to either `show`/`hide` or `open`/`close` for linguistic matching. No strong preference between them

**Comment by melanierichards** [comment]
Minutes for this issue seem to be missing, but from the record in IRC, resolutions were:

* RESOLVED: Name the methods show hide
* ACTION: Raise an issue on HTML to deprecate `close` in favor of `hide` for `dialog
* ACTION: Review other decisions (function syntax, open issues) we've made for consistency with show/hide

**Comment by melanierichards** [comment]
Addressed in #355

**Comment by mfreed7** [comment]
FYI, there is likely to be a decision for `<dialog>` to keep it as-is, with `show`/`close`. See [this comment](https://github.com/whatwg/html/issues/7748#issuecomment-1095680584) for more details, but I think it might be ok to have `<div popup>` not be perfectly parallel to `<dialog>`.
