### ISSUE TITLE
[Popup] Consider modal-ness as a spectrum in the platform

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#325]
On https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/445, @erikkroes said of the `<popup>` proposal:

> I see the "light dismiss" behaviour as the most interesting part of this exploration. We currently have elements in a page that can have a show/hide or open/close state like `<summary>` and `<details>`. On the other side of the spectrum you can have a fully modal dialog. 
> 
> The modal dialog has a lot of interesting aspects. You shouldn't be able to interact with the rest of the page which introduces a lot of caveats. A modal dialog is like a new page (but without the URL). It gives an entirely new context and removes you from the original context both visually, and non-visually.
> 
> It feels like the idea of a light dismiss tries to find a middle ground. It could be interesting for a proposal like this to explore the ideas behind modal behaviour (like defined with `aria-modal`).  Some elements are clearly not modal and some are completely modal, following the binary choices of `aria-modal`. What elements belong to the first group, which belong to the second, and which go into the category of the (semi-modal?) light dismiss. Likewise, what characteristics does it share with a modal dialog, and which doesn't it share?
> 
> A venn diagram of modal and non-modal behaviour could be made. And following, a venn diagram of (possible) elements. The current proposal is for an element, but the element is part of a system. When you want to improve a sytem by adding something, you need to consider the entire system.

@maltenuhn said:

> There is another dimension to the venn diagram (or spectrum) from modal to non-modal behaviour, namely whether UI events are passed through when interacting with the area outside it - including the click-outside-to-dismiss.
> 
> In our web based design tool (https://github.com/concrete-utopia/utopia) we have three classes of controls that might be modelled with `<popup />` or `<dialog />`:
> 
> 1.  A colour picker "popup" style control with swatches. It dismisses when clicking outside it. It  also needs to pass through that "click", as well as the hover events we use to draw hover outlines on other elements. Basically, the outside of the popup is transparent to all mouse events, _including_ the click to dismiss.
> 2. An "uploading files" modal. Clicking outside it dismisses the modal, but neither the click outside nor the hover events should be passed through, but clicking outside does dismiss it.
> 3. A heavy "select" type of control. Here the _click_ outside of it (to dismiss) _should_ be passed through, but while the popup is visible, other events (e.g. hover) are not.
> 
> In practice we achieve this with a combination of React portals, `fixed` positioned elements with `pointerEvents`, global event handlers, and `z-index` contortions. In particular, we either have to draw a div to act as a click / hover catcher, or use global event handlers via JS. Because the click catchers need to have the right net z-index (behind the popup, in front of everything else), _and_ cover an area contiguous to either the full screen or a part of it, we have to combine a number of techniques to achieve it (z-index, React portals, global event handlers, manually "positioning" the popup part). 
> 
> There's obviously a number of ways to support it, but if the intention is for `popup` and `dialog` to cater for these use cases, having some control over what happens _outside_ of the modal would be very welcome.

@tlouisse added:

> Great examples @maltenuhn. I would like to add another example where light dismiss boundaries are not clear. The gif below shows what happens to the github dropdown when screensize is changed from 'desktop' to 'mobile':
> 
> ![githubSwitch](https://user-images.githubusercontent.com/13814138/106145316-ac9d7400-6175-11eb-97bb-131caaad58b4.gif)
> 
> Question arises: **does the mobile screen still fit the 'light dismiss criterium'?**
> 
> Since it has a backdrop, the only way to build this dropdown, would be with a `<dialog>`, since 
> popups don't have backdrops? See: https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/432 

I confess that I'm not exactly certain what the desired outcomes would be here. Potentially:

* More precise definition of "light dismiss" behaviors and which events are(n't) passed through? (This would apply not just to `popup` but other elements with light dismiss behaviors as well)
* Some design change to `<popup>` interaction behaviors?
* A separate primitive to control modal-ness along a spectrum?

@erikkroes, do you want to take a stab at a proposal for us to consider in Open UI?

**Comment by erikkroes** [comment]
No idea what I'm doing yet, but I made a little something at https://github.com/openui/open-ui/pull/352

Getting to know the workflow, and can hopefully build from there.

**Comment by melanierichards** [comment]
Hey @erikkroes, I saw that your PR is in draft, are you ready for feedback or not quite yet?

**Comment by scottaohara** [comment]
a lot has changed with `popover` since this issue was filed.  a `popover` is not modal, light dismiss behavior is being defined in HTML for modal dialogs.  Closing this issue per the evolution of where this topic has gone.

**Comment by erikkroes** [comment]
Also fine to close it as "Erik will probably never get to it" 😄
