### ISSUE TITLE
[Popup spec] Define in finer detail processing of autofocus and delegatesfocus attrs for popup

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#330]
On https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/435, @tlouisse asked:

> - Would it also work for shadow dom content?
> ```html
> <popup>
>   #shadow-root
>   <button autofocus></button>
> </popup>
> ```
> 
> - What would happen when both host and child apply autofocus (or delegatefocus and autfocus)?
> ```html
> <popup autofocus>
>   <button autofocus></button>
> </popup>
> ```
> ```html
> <popup delegatefocus>
>   <button></button>
>   <button autofocus></button>
> </popup>
> ```
> - And what when content is being rendered asynchronously, right after show (since this does not work on first meaningful paint for [current autofocus](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement/autofocus) when rendered with a template engine like lit-html)? 

Finer details on processing these attributes should be written up in spec text, or should reference existing details in the HTML spec.

**Comment by melanierichards** [comment]
```
<popup>
  #shadow-root
  <button autofocus></button>
</popup>
```

I believe this should work but paging @mfreed7 in case anything has come up in popup prototyping.

```
<popup autofocus>
  <button autofocus></button>
</popup>
```

Per [the spec details on `autofocus`](https://html.spec.whatwg.org/multipage/interaction.html#the-autofocus-attribute) this should be invalid use of the attribute. From my [reading on `dialog`](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element) I believe the spec indicates that the button would take precedence, but it seems Chromium will focus the `dialog` first.

```
<popup delegatefocus>
  <button></button>
  <button autofocus></button>
</popup>
```

IMHO `autofocus` should take precedence as it is a more specific indication of author intent, but we should discuss this point.

```
And what when content is being rendered asynchronously, right after show (since this does not work on first meaningful paint for current autofocus when rendered with a template engine like lit-html)?
```

`dialog` runs focusing steps [when the `dialog` is shown](https://html.spec.whatwg.org/multipage/interactive-elements.html#the-dialog-element); we should follow similar behavior for popup. I'd say it would be better to pre-populate contents or if they must hydrated after show, manage focus explicitly in script.

**Comment by tlouisse** [comment]
Thanks @melanierichards

**Comment by josepharhar** [comment]
My HTML spec PR uses get focus delegate for popover initial focus, which was thoroughly designed by domenic and handles the autofocus attribute as well as shadowroots with delegatesfocus. This issue can be closed
