### ISSUE TITLE
[SELECT] The use of "part" clashes with custom elements containing <selectmenu>

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#354]
Copy/pasted from https://github.com/MicrosoftEdge/MSEdgeExplainers/issues/483 so we can discuss/bikeshed names in OpenUI. @mfreed7 says:

According to the explainer, [here](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md#hooking-up-native-controller-code-to-user-provided-ui-parts), when authors "replace" a part of the `<selectmenu>` using the slot attribute, they are required to also add the "part" attribute to allow the UA to connect up controller code. However, if a `<selectmenu>` is contained inside a custom element shadow root, that use of "part" will **also** expose the part for styling **outside** the custom element, since the "part" syntax is identical and there is no direct-child requirement for using "part".

Here is an example:

```html
<my-custom-select>
  <template shadowroot=open>
    <selectmenu>
      <div slot="button" part="button">Custom button</div>
      <option>Cat</option>
      <option>Dog</option>
    </select>
  </template>
</my-custom-select>

<style>
  my-custom-select::part(button) {
    /*This will match the button inside the custom element*/
    background-color: red;
    padding:20px;
  }
</style>
```

Note that the replaced custom "button" part will be exposed **outside** the `<my-custom-select>` element.

Perhaps we could either use a different attribute name ("custom-part", "replaced-part", ...?) or change the behavior/spec for CSS custom parts so that it somehow magically "hides" these contained parts?

Thanks to @justinfagnani for pointing this out.

**Comment by dandclark** [comment]
@justinfagnani asked:
> @dandclark is there a place in the explainer that says why `slot` alone is insufficient?

I'm not sure that it's specifically laid out in the explainer; probably I should add something on this.

Having `part` (or whatever we name it) as a separate attribute grants a lot more power to authors who want to be selective about where the native controller code is applied. The example in [Another example of extensibility: Split-button select](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md#another-example-of-extensibility-split-button-select), modeled after Bootstrap's [Splitbutton](https://getbootstrap.com/docs/4.3/components/dropdowns/#split-button), could not be written as easily without this capability. The author wants to replace the entire default button of the `<select>`, so they use `slot="button"` to replace it with their own custom-styled content.  But, they only want the right-hand section of their button to get the native event handlers that open the listbox on click/keyboard, so they apply `part="button"` to only the `<div class="arrow" part="button"></div>`.

```html
<select>
  <div slot="button-container">
    <div class="select-label">Primary</div>
    <div class="arrow" part="button"></div>
  </div>
  <div name="listbox-container" slot=”listbox-container” part=”listbox”>
    <option value="Option One">Option One<option>
    <option value="Option Two">Option Two</option>
    <option value="Option Three">Option Three</option>
    <div class="separator"></div>
    <option value="Option Four">Option Four</option>
  </div>
 </select>
```


![](https://raw.githubusercontent.com/MicrosoftEdge/MSEdgeExplainers/main/ControlUICustomization/splitButtonSelect.png)

**Comment by dandclark** [comment]
As I said in the original thread, I'd previously thought about the dual-use of part as a potential advantage, in cases where custom control authors might want to have their custom parts be styleable by the outer page. But the inability to prevent the styleability from leaking seems bad. I think the simplest solution is, as proposed, just use another name for the attribute.

@mfreed7 said:
> I kind of prefer a longer name here - I think it will be important to distinguish this from the existing Shadow Parts API. Perhaps we could use a word that doesn't even include "part"?

Brainstorming some possibilities:
- `subcomponent`
- `subcomponentname`
- `piece`
- `controlsegment`
- `hasbehavior`, or just `behavior`, like `behavior="button"`

Or if we're OK with allowing "part" in the name:
- `controlpart`
- `componentpart`
- `controlsubpart`
- etc

Naming is hard...

**Comment by dandclark** [comment]
In https://github.com/openui/open-ui/issues/396#issuecomment-912059441 @chrisdholt suggested using `role` instead of `part` for applying controller code. I like this idea because:
- Semantically the word `role` seems to work.
- If the author is required to specify the correct value of `role` in order to have controller code applied to an element, then there is less magic that the controller code needs to do to assign the correct accessibility role to that element.

However there are two problems to this that I can't think of a way around.
The first is that I think it would cause problems with the splittbutton example I wrote about in https://github.com/openui/open-ui/issues/354#issuecomment-855003752.

```html
<select>
  <div slot="button-container">
    <!-- We don't want to give this one controller code, since it shouldn't open the listbox,
            but it needs the role attr to have the correct a11y semantics: -->
    <div class="select-label" role="button">Primary</div>
   <!-- We do want to give this one controller code so that it opens the listbox:-->
    <div class="arrow" role="button"></div>
  </div>
  <div name="listbox-container" slot=”listbox-container” role=”listbox”>
    <option value="Option One">Option One<option>
    <option value="Option Two">Option Two</option>
    <option value="Option Three">Option Three</option>
    <div class="separator"></div>
    <option value="Option Four">Option Four</option>
  </div>
 </select>
```

There's no way to distinguish between an element given a `role` because the author wanted it to receive `<selectmenu>` controller code, and an element given a `role` because the author just wanted to give it the correct a11y semantics.

Secondly, there are UI parts that might not have a corresponding `role`, e.g. the "selected-value" part in https://open-ui.org/components/select#anatomy-1. "selected-value" is probably not critical to include and could maybe be dropped from the anatomy, but there are other cases of this that probably can't be dropped. For example, [checkbox](https://open-ui.org/components/checkbox#anatomy) has an "indicator" part that doesn't really correspond to an ARIA role.

So I can't think of a way around these problems, but the use of `role` for applying controller code is an interesting enough idea that I wanted to raise it here in case anyone has ideas for making it work.

**Comment by chrisdholt** [comment]
> There's no way to distinguish between an element given a `role` because the author wanted it to receive `<selectmenu>` controller code, and an element given a `role` because the author just wanted to give it the correct a11y semantics.
> 
> Secondly, there are UI parts that might not have a corresponding `role`, e.g. the "selected-value" part in https://open-ui.org/components/select#anatomy-1. "selected-value" is probably not critical to include and could maybe be dropped from the anatomy, but there are other cases of this that probably can't be dropped. For example, [checkbox](https://open-ui.org/components/checkbox#anatomy) has an "indicator" part that doesn't really correspond to an ARIA role.

On this - I think it really comes down to what we want to enable as the platform and what is the responsibility of an implementor. One of the primary reasons that I elevated role is that it ties the *functional* code to accurate a11y semantics. As you point out, this does create a problem in scenarios where you want something to get controller code but isn't necessarily accurate from an accessibility standpoint. I think in some sense, we need to pick a direction here in terms of which way we bend. Do we prioritize tying the controller code functionally to an attribute like role which enables an accurate representation for all users, or do we prioritize flexibility to support select doing anything someone wants, which may not be able to be made accessible regardless. My bent in this case is always to lean into prioritizing accessibility here, but that is my opinion. I could also see where that creates inaccessible controls because people do wrong things. On the other hand, if we prioritize something like part, then ensuring an accurate role is *again* up to the implementor...so that's somewhat a wash.

@dandclark, on the note regarding checkbox...what portion of the controller code is tied to the actual indicator part? I think an indicator would be slotted, but I can't necessarily think of a reason that we would need to tie behaviors to the visual indicator itself. Elements with a role of `checkbox` or `radio` will both end up labelling their children as presentational so anything in this slot is likely not interactive or accessible from an AT perspective.

**Comment by dandclark** [comment]
Per the resolution [here](https://github.com/openui/open-ui/issues/354#issuecomment-954161227) to use `"behavior"` instead of `"part"`, I think we can consider this to be resolved. Closing.
