### ISSUE TITLE
[Checkbox] Alter DOM structure to place label after control

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#361]
Based on the [research comparing various design systems](https://open-ui.org/components/checkbox.research.concepts), it's common practice for the control to be placed to the left hand-side, and the corresponding text label to be placed on the right hand side.

![image](https://user-images.githubusercontent.com/17087167/123315559-c32cd900-d523-11eb-913e-6f289dd7950f.png)

The proposed DOM structure  found on the [checkbox research page](https://open-ui.org/components/checkbox/) shows the label placed on the left-hand side by default:

```html
<oui-checkbox>
  <label part="label">
    <slot name="label"></slot>
  </label>
  <div part="indicator">
    <slot name="indicator"></slot>
  </div>
</oui-checkbox>
```

This is what a basic implementation of a checkbox looks like with the structure defined in the proposal:

https://user-images.githubusercontent.com/17087167/123315764-fbccb280-d523-11eb-9345-cec2e2371fee.mov

Note: These are the styles on set on the checkbox `:host` . 

```css
:host {
    display: flex;
    contain: content;
    cursor: pointer;
    width: fit-content;
}
```
All other styles are defined on the client side for some visual flair.

Here's an example of the same checkbox component but with an altered DOM structure. The label is placed after the control.

```html
<div part="control">
    <div part="indicator">
        <slot></slot>
    </div>
</div>

<label id="label" part="label">
    <slot name="label"></slot>
</label>
```

https://user-images.githubusercontent.com/17087167/123315808-09823800-d524-11eb-95d7-39e6591ee137.mov

I had a look around for a previous resolution relating to this, but didn't come across one. Apologies if one exists and I missed it.

**Comment by leolopes** [comment]
Hi @andrico1234 , as I'm dealing with Radio Buttons, this concerns me as well.
What do you propose? Should directionality be solely determined by CSS?
Should the slots' positions be interchangeable?

**Comment by andrico1234** [comment]
I want to be careful not to assert that having a label placed after the indicator is objectively the right thing to.

I tried having a look for rationale in some previous issues, like [here](https://github.com/openui/open-ui/pull/54) but couldn't find an answer.

I'll tag some folks that have been involved in the issue @nicholasrice , @gregwhitworth  in the past.

My main questions are:

- According to the [out of scope](https://github.com/openui/open-ui/pull/54) section, the styling is up to the browser. So does that make this a non-issue? Or do we still need to be mindful about the placement of the markup?
- Are there a11y considerations I'm completely missing with having the label placed after the control? Or would using properties like `aria-labelledby` make the structure of the DOM trivial?


P.s. this is my first time getting involved, so I'm sorry if I missed something obvious, or got things a little muddled!

**Comment by leolopes** [comment]
I second your questions :)

**Comment by chrisdholt** [comment]
> I want to be careful not to assert that having a label placed after the indicator is objectively the right thing to.
> 
> I tried having a look for rationale in some previous issues, like [here](https://github.com/openui/open-ui/pull/54) but couldn't find an answer.
> 
> I'll tag some folks that have been involved in the issue @nicholasrice , @gregwhitworth in the past.
> 
> My main questions are:
> 
> * According to the [out of scope](https://github.com/openui/open-ui/pull/54) section, the styling is up to the browser. So does that make this a non-issue? Or do we still need to be mindful about the placement of the markup?
> * Are there a11y considerations I'm completely missing with having the label placed after the control? Or would using properties like `aria-labelledby` make the structure of the DOM trivial?
> 
> P.s. this is my first time getting involved, so I'm sorry if I missed something obvious, or got things a little muddled!

I'll note that I think the issue here seems largely visual and presentational and I don't think a change is warranted. This feels purely like a visual delta and I don't think that the semantic structure of the DOM should be driven by visual presentation.

**Comment by gregwhitworth** [comment]
Yes, the important aspect here is that there IS a label in association by default with the checkbox. `aria-label` can also ensure that the exact name computation can be defined. That said, we can easily add a slot that wraps both the indicator and the label and this will enable an author to change the ordering.

**Comment by andrico1234** [comment]
Thanks folks, that clears things up

**Comment by andrico1234** [comment]
I had a play with a WC that matches the DOM structure of the Open UI's Checkbox component. Looks like you can adjust the direction in userland quite easily. This might be a non-issue. Unless there are a11y 

https://user-images.githubusercontent.com/17087167/130571759-0fd405b5-ab6e-498a-8405-a17971cc7403.mov

and a short vid using a screen reader in case there are a11y concerns WRT to content ordering


https://user-images.githubusercontent.com/17087167/130572462-0c63ca7d-2358-4844-be62-332c854a82cf.mov

If there are no follow up questions, I'll be happy to close this isssue

**Comment by leolopes** [comment]
It seems I can keep the structure I proposed on my PR as is. By the way, I'd love anyone to review it: https://github.com/openui/open-ui/pull/360/
