### ISSUE TITLE
[Popup] Conflict resolution with delegatesfocus and autofocus

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#369]
As the "focusing steps" for `popup` are written in #355, the `delegatesfocus` attribute effectively takes precedence over `autofocus` when both are applied to `popup`, like so:

```
<popup autofocus delegatesfocus>
  <button>I will be focused, not the popup itself</button>
</popup>
```

The Chromium prototype also follows this behavior. Is this the desired/most reasonable conflict resolution?

**Comment by bkardell** [comment]
this is how I would assume it should work, as an author.

**Comment by gregwhitworth** [comment]
We discussed this on the telecon today and resolved on the following:

> RESOLUTION: delegatesfocus should win in conflict resolution with autofocus
