### ISSUE TITLE
Page for listing companies & individuals involved in Open UI

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#375]
Open UI continues to grow and as more and more work is being done by this group I'd like to shine a light on those involved. I'd like to create a page that shows the logos of companies that people represent (only if you represent them officially and have legal support for us to post their logo) as well as individual names. I could list everyone in the Open UI CG membership but I'd like folks permission to post their names on a page for the site. Please reply here with the logo you'd like us to use and your Name, Company (if affiliated) with how you would like it rendered on the page. For example here is mine:

Greg Whitworth, Salesforce

**Comment by bkardell** [comment]
Brian Kardell, Igalia 

Our logo assets are in the zip on https://www.igalia.com/press/ - please choose the one in web/tagline appropriate for the background color of the page.

**Comment by SebastianZ** [comment]
I guess irregularily providing feedback on different issues doesn't qualify for being listed, though if it's ok, you could add me as Sebastian Zartner with the image I use here on GitHub.

Sebastian

**Comment by leolopes** [comment]
Leonardo Baptista Lopes, Strongway Webstudio

Here are two images. See what might fit best :)

![logotipo-sw](https://user-images.githubusercontent.com/2057740/126678355-bc28789a-acbd-4a32-8342-9ae66d520434.png)

![perfil-sw](https://user-images.githubusercontent.com/2057740/126678358-e8f7eeb4-f2e0-4f98-b6c5-54019e118a79.png)

**Comment by mirisuzanne** [comment]
Miriam Suzanne - my Github avatar is fine.

**Comment by chrisdholt** [comment]
Chris Holt - FAST & Microsoft

Leverage whichever Microsoft logo others provide :).

FAST logo SVG code is below:
```html
<svg width="148" height="120" viewBox="0 0 148 120" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path fill-rule="evenodd" clip-rule="evenodd" d="M117.652 27.3344C128.932 24.2136 140.213 31.0794 143.346 42.3144C146.166 53.8615 139.586 65.4085 128.932 68.5293C128.62 68.8414 127.993 68.8414 127.679 68.8414C124.545 86.6301 111.385 102.234 92.8983 107.228C75.3511 112.221 57.4905 106.291 45.897 94.1201C44.3302 92.5597 42.1369 91.9355 40.2568 92.5597H39.9434C38.0634 92.8718 36.1833 91.9355 35.87 90.063C35.5567 88.1905 36.4967 86.6301 38.3768 86.0059L77.8578 75.0831C79.7379 74.771 81.6179 75.7072 81.9313 77.5797C82.2446 79.4522 81.3046 81.0126 79.4245 81.6368L59.0573 87.2543C55.2972 88.5026 53.7304 93.1838 57.1773 95.3684C66.8909 101.61 79.1112 104.107 90.3916 100.986C105.745 96.9288 117.026 84.1334 120.159 69.1535C112.012 68.2172 104.806 62.2877 102.612 53.5494C100.418 44.8111 103.552 36.0728 110.132 31.0794C100.105 20.1566 84.438 15.1632 69.3976 19.2203C56.8639 22.6532 47.1503 31.7036 42.1369 42.9386C40.5701 46.6836 44.0169 49.8044 47.777 48.8681L49.9703 48.244C51.8504 47.9319 53.7304 48.8681 54.0438 50.7406C54.3572 52.6131 53.4172 54.1735 51.5371 54.7977L15.1894 64.7843C13.3093 65.0964 11.4293 64.1602 11.1159 62.2877C10.8026 60.4152 11.7426 58.8548 13.6227 58.2306L29.2898 53.8614C31.4832 53.2373 33.0499 51.6769 33.3632 49.4923C37.1234 32.0157 49.9703 17.6599 67.8308 12.6666C86.0047 7.67324 104.492 14.227 116.086 27.9586C116.254 27.8749 116.4 27.7912 116.535 27.7135C116.903 27.5015 117.194 27.3344 117.652 27.3344ZM107.938 47.9319C107.938 56.3581 114.832 62.9118 122.979 62.9118C131.439 62.9118 138.02 56.3581 138.02 47.9319C138.02 39.5057 131.126 32.9519 122.979 32.9519C114.832 32.9519 107.938 39.5057 107.938 47.9319ZM82.3262 62.9744L94.8489 59.5303C96.7273 58.9042 97.6664 57.3387 97.3533 55.4601C97.0402 53.5815 95.1619 52.6422 93.2835 52.9553L80.7609 56.3994C78.8825 57.0256 77.9433 58.5911 78.2563 60.4696C78.5694 62.3482 80.4478 63.2875 82.3262 62.9744ZM70.4296 65.7923L61.3507 68.2971C59.4723 68.9233 57.5939 67.6709 57.2808 65.7923C56.9678 63.9137 57.907 62.3482 59.7854 61.722L68.8643 59.2172C70.7427 58.9041 72.6211 59.8434 72.9342 61.722C73.2473 63.6006 72.3081 65.1661 70.4296 65.7923ZM47.5756 65.1661C49.4539 64.853 51.3323 65.7923 51.6453 67.6709C51.9584 69.2364 51.0192 71.115 49.1408 71.7412L8.12919 83.0128C6.25078 83.3259 4.37239 82.3866 4.05933 80.508C3.74626 78.6294 4.68546 77.0639 6.56385 76.4377L47.5756 65.1661Z" fill="url(#paint0_linear)"/>
    <defs>
        <linearGradient id="paint0_linear" x1="135.969" y1="60.5478" x2="16.0389" y2="43.156" gradientUnits="userSpaceOnUse">
            <stop stop-color="#E1477E"/>
            <stop offset="1" stop-color="#EC422E"/>
        </linearGradient>
    </defs>
</svg>
```

I'll attach a PNG for convenience once I track it down.

**Comment by hidde** [comment]
Hidde de Vries, GitHub avatar works!

**Comment by josephrexme** [comment]
I'm not as actively involved as I hope to be (I just show up in meetings and on the chat) but I'd love to get more involved so if that counts

Joseph Rex - ConvertKit ([Logos here](https://convertkit.com/brand))

Avatar:

<img src="https://res.cloudinary.com/strich/image/upload/w_1000,ar_1:1,c_fill,g_auto,e_art:hokusai/v1626979746/E97E24F5-393E-4656-BA43-5EE32EA48E9C_1_105_c_dpbvyr.jpg" alt="Joseph facing the sun" width="200" height="200">

**Comment by christopherallanperry** [comment]
You could use this one for me.

![chris_perry](https://user-images.githubusercontent.com/10407622/155695249-875ccca6-7393-4ffe-8178-a6e80aff4b0b.jpg)

**Comment by christopherallanperry** [comment]
Maybe that's a little large...

**Comment by gregwhitworth** [comment]
This is now covered using the Github API and it runs at least once per year so closing this
