### ISSUE TITLE
Add in support for Github topic minuting

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#376]
Add support for IRC -> Github minute posting.

**Comment by hidde** [comment]
I have done this before and can do it for this repo, we'll need to add the repo to a JSON file.

**Comment by hidde** [comment]
Found it and just opened the relevant PR.

**Comment by hidde** [comment]
Yay, @gregwhitworth @una, the PR was merged, so we can try this next meeting!

**Comment by gregwhitworth** [comment]
@hidde thanks for this!!
