### ISSUE TITLE
Headings in site navigation have contrast issues

### ISSUE THREAD

**Issue by hidde** [openui/open-ui#377]
The headings in the site navigation have a [contrast ratio of `2.84 : 1`](https://contrast-ratio.com/#%23999999-on-white). 

My proposal would be to make them slightly darker. That makes them less different from the links, so I'd suggest also making them bold.

<img width="477" alt="on the left, page navigation with non bold lighter gray headings, on the right, page navigation with bold darker gray headings" src="https://user-images.githubusercontent.com/178782/127541210-5db882b3-3d1e-4e57-80dc-bb08fbb08833.png">

Related, they are also marked up as `div` elements, as part of resolving this issue I could change them into `h*` tags too, seems like that would be helpful for people navigating by heading to get to these lists quickly.

**Comment by andrico1234** [comment]
My knee-jerk reaction during my first time on the UI site was that these were disabled buttons!
