### ISSUE TITLE
Ensure that delegatesfocus cannot trap focus

### ISSUE THREAD

**Issue by flackr** [openui/open-ui#379]
If delegatesFocus automatically focuses the first focusable child *when* the element is focused, then we need to make sure that shift+tab or similarly trying to navigate out of the element is possible. This is likely only an issue if we extend delegatesfocus to other elements #367

E.g.
```html
<button id="A"></button>
<div delegatesfocus>
  <button id="B"></button>
</div>
```

If the user has B focused, and presses shift+tab, I would expect A to be focused.

**Comment by melanierichards** [comment]
+1, definitely expecting the same behavior from your example.

Also, I realized I had misinterpreted the comment in our original discussion and was thinking you meant SHIFT + TAB'ing _into_ the `popup`, or whatever element has `delegatesfocus` applied. Here is what I would expect (using `popup` as a proxy for "thing that has `delegatesfocus` applied"):

## Author programmatically sets focus to the popup (in script)

```
<button id="A"></button>
<popup delegatesfocus>
  <button id="B"></button>
  <button id="C"></button>
</popup>
<button id="D"></button>
```

B receives focus.

## User tabs forward to the popup from "A"

```
<button id="A"></button>
<popup delegatesfocus>
  <button id="B"></button>
  <button id="C"></button>
</popup>
<button id="D"></button>
```

B receives focus.

## User shift + tabs backward to the popup from "D"

```
<button id="A"></button>
<popup delegatesfocus>
  <button id="B"></button>
  <button id="C"></button>
</popup>
<button id="D"></button>
```

C receives focus (normal shift + tab behavior)

## User shift + tabs backward from "B"

```
<button id="A"></button>
<popup delegatesfocus>
  <button id="B"></button>
  <button id="C"></button>
</popup>
<button id="D"></button>
```

A receives focus.

**Comment by chrisdholt** [comment]
@melanierichards just to confirm, the above is all expected with the popup *visible* (open) - correct? The above doesn't account for instances where it's hidden, correct? Just covering bases :)

**Comment by melanierichards** [comment]
Yep, what @chrisdholt said :)

**Comment by mfreed7** [comment]
Given the recent resolution (https://github.com/openui/open-ui/issues/368#issuecomment-1138881225) to wait on `delegatesfocus` for Popup until later, and possibly pursue a more general `delegatesfocus` type feature, I'm going to remove the `popup` label from this issue.

**Comment by mfreed7** [comment]
So Popover shipped without `delegatesFocus`, and based on my experience, I'm not sure it's actually a needed use case (because of `autofocus` and also the default focus "fixup" behavior of popover). So tentatively, I'm going to close this issue.
