### ISSUE TITLE
[Popup spec] Move invoker activation behaviors to other parts of the HTML spec

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#390]
#355 lands a first editor's draft of `<popup>` in Open UI, and is intended to be brought to various parts of the HTML spec in WHATWG.

Of the steps in the ["Showing/hiding a popup element via the popup attribute" section](https://open-ui.org/components/popup#showing-hiding-a-popup-element-via-the-popup-attribute), @domenic's [advice ](https://github.com/openui/open-ui/pull/355#discussion_r687180355) was to:

* Add/modify explicit activation behavior for `button` and `input` in the various relevant states. [Button element example](https://html.spec.whatwg.org/#the-button-element). Having a single algorithm multiple places call makes sense.
* Modify the [focus update steps](https://html.spec.whatwg.org/#focus-update-steps):

> I think the focus update steps need modification for "OR the _invoker_ is an input in the `email`, `number`, `search`, `tel`, `text`, or `url` states and focus is set to the _invoker_". That is, whenever focus is updated for an input type=email, you need to check if that input type=email is the invoker for a popup and then run these steps if so.

Opening this issue to track the edit as suggested. We can add a snippet to the Open UI spec as I've done here: https://open-ui.org/components/popup#html-incubation-text-user-interaction-focus-processing-model

**Comment by josepharhar** [comment]
My HTML spec PR hooks into activation behavior. This issue can be closed
