### ISSUE TITLE
[Popup spec] Update autofocus specifications in HTML for popup

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#391]
#355 lands a first editor's draft of `<popup>` in Open UI, and is intended to be brought to various parts of the HTML spec in WHATWG. Regarding [autofocus language](https://open-ui.org/components/popup#setting-initial-focus-with-the-autofocus-attribute), @domenic's [advice](https://github.com/openui/open-ui/pull/355/files#r675163363) was to update the [autofocus attribute](https://html.spec.whatwg.org/multipage/interaction.html#the-autofocus-attribute) portion of the spec for `popup`.

Opening this issue to track the edit as suggested. We can add a snippet to the Open UI spec as I've done here: https://open-ui.org/components/popup#html-incubation-text-user-interaction-focus-processing-model

**Comment by josepharhar** [comment]
My HTML spec PR includes changes to get focus delegate which support the autofocus-only behavior for popovers.

This issue can be closed
