### ISSUE TITLE
[Popup spec] Update close watcher logic and focusing steps algo for popup light dismissal

### ISSUE THREAD

**Issue by melanierichards** [openui/open-ui#393]
#355 lands a first editor's draft of `<popup>` in Open UI, and is intended to be brought to various parts of the HTML spec in WHATWG.

Of the [light dismissal section](https://open-ui.org/components/popup#light-dismissal), @domenic's [advice](https://github.com/openui/open-ui/pull/355/files#r675188384) and [additional advice](https://github.com/openui/open-ui/pull/355/files#r675188930) was to:

* Add something like the [dialog patch to close watcher logic](https://domenic.github.io/close-watcher/#patch-dialog)
* Update the [focusing steps algorithm](https://html.spec.whatwg.org/#focusing-steps)
* Not to add componentized "light dismissal" definitions anywhere before relevant, i.e. before there are multiple elements that would call into that behavior. That's a little different than what we had planned for Open UI, as we do think there are multiple Open UI components that we imagine will consume from a common definition (whether or not they will all be platform changes remains to be seen).

Opening this issue to track the edit as suggested. We can add a snippet to the Open UI spec as I've done here: https://open-ui.org/components/popup#html-incubation-text-user-interaction-focus-processing-model

**Comment by josepharhar** [comment]
> Add something like the [dialog patch to close watcher logic](https://domenic.github.io/close-watcher/#patch-dialog)

We will make sure that close watcher gets integrated when close watcher is added to the HTML spec. I don't feel inclined to also spell out exactly how I'm going to integrate it into HTML in domenic's repo.

> Update the [focusing steps algorithm](https://html.spec.whatwg.org/#focusing-steps)

Light dismiss doesn't do this king of patching for focus anymore in my HTML spec PR for popover

> Not to add componentized "light dismissal" definitions anywhere before relevant, i.e. before there are multiple elements that would call into that behavior. That's a little different than what we had planned for Open UI, as we do think there are multiple Open UI components that we imagine will consume from a common definition (whether or not they will all be platform changes remains to be seen).

In my HTML spec PR, light dismissal is not an abstraction that only has one consumer - it is specifically defined only for popovers and lives in the popover section.

This issue can be closed.
