### ISSUE TITLE
[select] Shadow root replacement

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#399]
In https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md#shadow-dom-replacement we proposed that authors should be able to supply a custom UI for `<selectmenu>` by calling `attachShadow()` and replacing the control's entire shadow DOM:
```js
let customSelect = document.createElement('selectmenu');
let selectShadow = customSelect.attachShadow({ mode: 'open' });
selectShadow.innerHTML = `
  <style>/* Custom styles... */</style>
  <button part="button">My custom button</button>
  <popup part="listbox">
    <option>Thing 1</option>
    <option>Thing 2</option>
   </popup>`;
document.body.appendChild(customSelect);
```

This is useful as an alternative to the [named slots approach](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md#named-slots) because:
1. The custom UI is isolated from light DOM styles
2. For authors who want to replace the entire default UI, this replacing the shadow DOM might be more straightforward than using the `<slot>`s.

But if we want to support this, there are some questions about how specifically `attachShadow()` should work, since `<selectmenu>` already has a shadow DOM. It seems to me that there are two possibilities for what should happen when `attachShadow()` is called on a `<selectmenu>`:

**Approach A:** The initial shadow DOM is discarded, and a new shadow DOM is attached.

At first this seems pretty straightforward, but there is some strangeness regarding what happens to the old shadow DOM. Now we would have a shadow DOM without a shadow host, which previously wasn't something that could exist. There is no way that the author could get a reference to this shadow root, though, so it's not really observable. But it's still suspicious.

**Approach B:** The initial shadow DOM is emptied out, and `attachShadow()` returns a reference to it.

This is how [declarative shadow DOM](https://github.com/whatwg/html/pull/5465) works. But with `<selectmenu>`, at least in the current Chromium prototype, the initial shadow DOM is a special "User Agent shadow DOM". Currently it's impossible for authors to get a reference to one of these. They have some special capabilities so we probably don't want to make it possible. We could change the "type" of the shadow DOM prior to handing out the reference, but that is also not something currently done, and might have its own problems.

That said, "user agent shadow DOM" isn't part of any standard, and might just be an implementation detail; maybe this issue could be solved by giving `<selectmenu>` a normal open or closed shadow DOM.

@mfreed7, I'd be interested in your thoughts on this since there were probably similar considerations for declarative shadow DOM.

cc @ipopescu93

**Comment by chrisdholt** [comment]
@dandclark My initial thought with regard to what you've outlined in "B" is that we should avoid "special magic" by the browser as some of that is what has helped kick off some of these conversations in Open UI :). With that, I would probably advocate for just going with an open shadow DOM unless there is some clearly defined issue where we need the UA or closed instance. I'm not sure I can think of a *good* reason to run in "closed" mode. I can't think of a good reason not run in open mode, but again, there may be something I'm missing that the UA Shadow DOM provides. It seems like using a normal *not-ua-special* shadow root is reasonable to me and one that may provide more extensibility over time.

**Comment by dandclark** [comment]
> we should avoid "special magic" by the browser as some of that is what has helped kick off some of these conversations in Open UI 

I agree with this sentiment, and I think you might be right that we could just use a "normal" shadow DOM.

As far as I know these are the special magic things that UA shadow roots do in Chromium:
1. They are not shown by default in DevTools. If the "Show user agent shadow DOM" option is enabled, they appear like this:
![image](https://user-images.githubusercontent.com/1688716/131917675-14fb2ac2-bfa4-44e4-b79c-6052d12dcab0.png).
2. There is some special slotting behavior. But I think this is mainly needed for other elements like `<details>`/`<summary>`, and not needed in `<selectmenu>` since we are intending to use "normal" slotting behavior.
3. There is a special capability for applying styles from the user agent stylesheets to specific element IDs in a UA shadow root. This is useful because the styles don't have to be duplicated in each custom element instance (even as, say, a CSS module import). So we could be giving up some performance, but this capability is probably not strictly needed for `<selectmenu>`; in fact the Chromium prototype currently does not use it.

So it is probably possible to use a "normal" shadow DOM for `<selectmenu>`.

I think it should probably be closed, though. If it is open, then for interoperability reasons the initial `<selectmenu>` must be exactly the same for every browser, and could never be changed (since it would be accessible to script and authors might take dependencies on any aspect of it).

If the shadow root is closed, then some aspects of its internals could differ across browsers and could be changed over time, as long as the appearance doesn't change enough to break things.

**Comment by chrisdholt** [comment]
> I think it should probably be closed, though. If it is open, then for interoperability reasons the initial `<selectmenu>` must be exactly the same for every browser, and could never be changed (since it would be accessible to script and authors might take dependencies on any aspect of it).
> 
> If the shadow root is closed, then some aspects of its internals could differ across browsers and could be changed over time, as long as the appearance doesn't change enough to break things.

Ah, this is a good point and one I had not thought of. There *is* a reason to used closed mode here! 👍

**Comment by gregwhitworth** [comment]
I would be curious what @tantek and @hober think since they'll have different implementations of UA controls/components.

From a webdev perspective I prefer option B as well.

**Comment by dandclark** [comment]
Closing since we resolved not to support `attachShadow()` in https://github.com/openui/open-ui/issues/528#issuecomment-1125286285.
