### ISSUE TITLE
[Popup] Should blur() be a light dismiss trigger?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#415]
In some cases, it might make sense for blur (focus leaving the `<popup>`) to trigger light dismiss. For example, if the `<popup>` is the menulist for a `<selectmenu>`, when the list is opened, it is focused, and tabbing out feels like it should close. However, in most other cases, it seems like this behavior would likely be confusing. In particular, because the `<popup>` is not focused by default (without `autofocus` or `delegatesfocus`), it feels especially weird that tabbing over to `<popup>` and then leaving it should close it. But it came up in a discussion, so I thought I should raise it here. Perhaps it should be a light-dismiss trigger only if the `<popup>` is auto-focused?

**Comment by scottaohara** [comment]
This would fundamentally depend on what the popup represents though. Eg the role that is exposed.

**Comment by melanierichards** [comment]
Not wishing to detract from the semantic mapping discussion, I wanted to point to this piece of the initial explainer:

> An opened popup will have “light dismiss” behavior, meaning that it will be automatically hidden when:
> 
> The user hits the escape key,
> The layout of the popup or its anchor element is changed.
> **Focus moves outside of the popup (and its invoking and anchor elements, if applicable).**

The carveout for invoking/anchor elements was meant to solve for things like comboboxes, where you wouldn't want light dismissal of the popup when focus is in the text field. There's something attractive to your line of thinking on `autofocus`/`delegatesfocus`, but just wanted to add that there are cases where you wouldn't autofocus the popup but would expect it to dismiss on blur.

**Comment by jonathantneal** [comment]
Hello 👋 

This item is labelled for discussion in the next teleconference. @melanierichards, @mfreed7, as editors of the proposal (and @mfreed7 as the creator of this issue), would you be available and interested in discussing this in the teleconference for additional feedback or consensus?

If so, @melanierichards, I believe you mentioned you would not be available tomorrow. Would next week work best for you both?

**Comment by dandclark** [comment]
There's another special case for this in https://github.com/openui/open-ui/issues/486, regarding what should happen when the popup is open and the user clicks the button that has `triggerpopup`.

In the `<selectmenu>` prototype, this closes the popup and then immediately reopens it, but we probably want to do something better. Either closing the popup (and keeping it closed), or leaving the popup open both seem like reasonable choices.

**Comment by scottaohara** [comment]
Closing would be my vote, and would be useful for touch screens / people using screen readers on touch screens.

**Comment by mfreed7** [comment]
I just wanted to summarize what I heard at the [discussion](https://github.com/openui/open-ui/issues/415#issuecomment-1071180773) yesterday:

- Generally, folks seem to think that "loss of focus" (see below) **should** cause a light dismissal of the popup. In particular, the AX folks on the call seemed to think that this was the most appropriate behavior.
- There were some good points raised about how to define "loss of focus":
   - The **popup** losing focus is what matters, and it is typically not focusable. So the `focusout` event is the more relevant one, rather than `blur`, since `focusout` bubbles.
   - Moving focus between elements within the popup will trigger `focusout` events. So we need to be careful in how we define "loss of focus" for a popup. It cannot be simply a `focusout` event bubbling to the popup element.
   - Similar to the above, clicking on a non-focusable element within the popup will cause focus to move to the `<body>` and stay there, and that should not constitute a "loss of focus". This will make the above bullet more difficult.
   - When the popup opens, focus might remain on the element that triggered it, and not move inside the popup. In that case, we would want to light dismiss when the **trigger** element loses focus, unless focus is moved directly to something within the popup. Essentially, the trigger element should be considered part of a group including the popup and any ancestor popups, and moving focus within this group should not light dismiss anything.
- We also discussed whether there was a difference between the element losing focus and the **window** losing focus (to another application window). The general consensus seemed to be that window blur should **not** trigger a light dismissal. However, after the meeting, @dandclark pointed out that we [already discussed this exact issue](https://github.com/openui/open-ui/issues/241),  and the resolution there was to have window blur trigger light dismiss. The rationale (see [the minutes](https://www.w3.org/2020/12/17-openui-minutes.html#ResolutionSummary)) was that most operating systems behave this way, and we shouldn't diverge without significant research. I have a hard time disagreeing with this logic, and prior resolution.
- To complete the summary, see the point raised/discussed just above. We need to think about the behavior when the triggering element is clicked or focused. Should that re-close the popup, or leave it open?

**Comment by mfreed7** [comment]
One more point, pulled from https://github.com/openui/open-ui/issues/319, is that we need to think about the correct behavior for focus moving between documents within a page. It would seem (to me at least) that this should fall into the same logic described in the comment above: when the focus leaves one popup, and moves to another element (including within a different embedded frame/document), the first popup should be light dismissed.

**Comment by mfreed7** [comment]
I propose this as a behavior:

1. Add a `focusout` event listener to `Document`.
2. In this listener, iterate through each Popup in the Popup Stack, starting from the "top" of the stack:
   a. Inspect the `relatedTarget` for the event.
   b. If the related target is null, continue.
   c. If the related target is a flat tree descendent of the Popup, continue.
   d. If the related target is a flat tree descendent of the Triggering Element for Popup, continue.
   e. Light dismiss Popup.

I believe this will result in the following behavior:
 - Any change of focus **within** a popup will **not** light dismiss the popup.
 - Any change of focus **within or to/from the triggering element** of a popup will **not** light dismiss the popup.
 - A change of focus to another element on the page, including an `iframe`, **will** light dismiss the popup.
 - A **window blur** (i.e. moving to another application window) **will** light dismiss the popup.

Thoughts?

**Comment by chrisdholt** [comment]
@mfreed7 Does flat tree mean assume flattening all Shadow DOM? If so I think the above would be reasonable.

**Comment by dandclark** [comment]
I think that doesn't work for the following case:
1. Use clicks on focusable item in popup.
2. User clicks on nonfocusable item in popup (here we get `focusout` with `target` == the focusable item, and `relatedTarget` == null. No light dismiss; so far so good).
3. User clicks on nonfocusable item outside of popup (e.g. the `document.body`). Since no focusable item had focus prior to this click, we don't get another `focusout` event, and the popup does not light dismiss.

Because of scenarios like this I'm not sure that it's possible to define this behavior in a straightforward way in terms of the existing DOM events like `focusout`. We may unfortunately need some platform magic to make this work properly.

**Comment by mfreed7** [comment]
> 3\. User clicks on nonfocusable item outside of popup (e.g. the `document.body`). Since no focusable item had focus prior to this click, we don't get another `focusout` event, and the popup does not light dismiss.

Actually I think we’re ok in exactly this scenario, but there might still be an issue. In this case, the user **clicked** on something outside, so the normal “click outside” light dismiss will kick in. But I wonder if there’s a similar scenario where the user clicks inside on something non-focusable, then keyboard navigates out to something outside? In that case we might need magic.

**Comment by mfreed7** [comment]
Ok, slightly modified proposal, which I think takes care of the problem example above:

1. Add a `focusout` event listener to `Document`, which iterates through each Popup in the Popup Stack, starting from the "top" of the stack, and does:
   a. Inspect the `relatedTarget` for the event.
   b. If the related target is null, continue.
   c. If the related target is a flat tree descendent of the Popup, continue.
   d. If the related target is a flat tree descendent of the Triggering Element for Popup, continue.
   e. Light dismiss Popup.

{The above is exactly the same, and will handle all cases except **clicking** on a non-focusable child of the popup, then **tab-navigating out** of the popup to another control.}

2. Add a `focusin` event listener to `Document`, which iterates through each Popup in the Popup Stack, starting from the "top" of the stack, and does:
   c. If the target is a flat tree descendent of the Popup, continue.
   d. If the target is a flat tree descendent of the Triggering Element for Popup, continue.
   e. Light dismiss Popup.

{This should handle the problem case. The first click on the non-focusable child of the popup will cause the related target in the `focusout` handler to be null, so the popup will not close. The tab navigation out of the popup will then not cause any `focusout` events, but will cause a `focusin` on the new focus target. Since that will not be a descendent of the Popup or Triggering Element, the popup will close here.}


Thoughts?

**Comment by dandclark** [comment]
I think that works, when combined with a separate handler to do the "click outside" light dismiss.

**Comment by mfreed7** [comment]
Since I think we've worked out a technical way to implement this behavior, I wanted to summarize where I think we are on this issue:

- Any change of focus **within** a popup will **not** light dismiss the popup.
- Any change of focus within or to/from a **triggering element** of a popup will **not** light dismiss the popup.
- Any change of focus within or to/from the **anchor element** of a popup will **not** light dismiss the popup.
- A change of focus to **another element on the page**, including an iframe, **will** light dismiss the popup.
- A **window blur** (i.e. moving to another application window) **will** light dismiss the popup.

{Note that I changed "the triggering element" to "a triggering element" to acknowledge [this comment](https://github.com/openui/open-ui/issues/508#issuecomment-1105448221).}

Does this sound like the right behavior? Any objections? Any AX issues?

**Comment by mfreed7** [comment]
Per the resolution, my action item was to open an issue. [There already was one, so I commented there](https://github.com/openui/open-ui/issues/493#issuecomment-1119085158).

I'm going to close this issue as resolved!

**Comment by mfreed7** [comment]
@aleventhal mentioned to me that this behavior (pop-up element blur causing a light-dismiss) might be very confusing for screen reader users, since it isn't obvious where the "end" of the pop-up is. It might be too easy to tab past the end of the pop-up, have the pop-up light-dismiss, and then be confused about where that content went, and what lies "behind" in tab order at this point. In fact, I think this is also a concern for sighted users, since it's not always obvious where the tab stops are within a pop-up, so it's easy to accidentally tab out of a pop-up.

I do think this behavior is expected and normal for a `<selectmenu>`, but I'm re-opening this issue to perhaps re-discuss whether we want this behavior for a general pop-up.

**Comment by scottaohara** [comment]
@mfreed7 @aleventhal, definitely worth discussing.  I share the concerns, but i also am not convinced that going this way wouldn't cause other issues.  would there be a more declarative way to allow authors to add/remove light dismiss behavior?  maybe that'd be helpful... and seems that people would appreciate that on modal dialogs (mouse click outside)... it'd sure help promote the point that `<div popup>` is not for recreating dialog elements... if you want the light dismiss behavior use this other [thing] instead on the actual dialog element.

**Comment by mfreed7** [comment]
See also https://github.com/openui/open-ui/issues/609#issuecomment-1268992256

**Comment by mfreed7** [comment]
Thanks for the discussion just now. At this point, it seems like there are really two options:

 1. `blur` is **not** a light dismiss trigger for pop-ups. If a developer wants `blur` to light dismiss, they can add focus catchers and call `hidePopUp()` from JS. Not declarative, but relatively straightforward. This will solve [#609](https://github.com/openui/open-ui/issues/609), but might cause user-confusion if they expect to tab out of a pop-up to get it to close. Users would need to learn to use ESC to escape out of pop-ups.
 2. Only light dismiss via `blur` **once focus has entered** the pop-up (or its triggering/anchor elements). This should solve [#609](https://github.com/openui/open-ui/issues/609). It does not solve the user-confusion problem where the user accidentally closes the pop-up via tabbing "too far". It is also potentially impossible for a developer to "disable" this behavior if they desire - `blur/focusout` are not cancelable.

Thoughts? Other ideas?
