### ISSUE TITLE
Bikeshed: what should <popup> be called?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#416]
See [this comment](https://github.com/openui/open-ui/issues/410#issuecomment-966680779) for more context. But the direction the `<popup>` proposal is heading is toward an accessibility mapping to role="dialog". And a proposed semantic definition of `<popup>` is:

>  "a transient non-modal **dialog box**, which is displayed on top of all other content. Popups are necessarily transient, such that only one is open at a time, and taking action elsewhere hides the popup.".

Given the above, it feels like instead of "`<popup>`", the element name should better-indicate its connection to dialogs.

Some starting ideas:
 - `<popupdialog>`
 - `<transientdialog>`

What other ideas do folks have?

**Comment by chrisdholt** [comment]
Just a gut reaction, and this is purely subjective, but I think "popup" in this case feels redundant as all the elements being proposed in the current `<popup>` proposal are some form of it. I'm leaning towards `<transientdialog>`of the two just given that initial feeling. If I think of any additional names, I'll drop them here :)

**Comment by zcorpan** [comment]
I would prefer shorter and easy-to-spell names for HTML, generally. (c.f. [misspellings of `<script language>`](https://web.archive.org/web/20060203025300/http://code.google.com/webstats/2005-12/scripting.html).)

So, `popupdialog` seems better from this perspective. Also, `initiallyopen` might be a bit long and subject to misspellings, alternatives could be `initopen` or `autoopen` (to mirror `autofocus`).

**Comment by yinonov** [comment]
Pairing _dialog_ to _popup_ would necessarily mean _popup_ contains interactive content. Like a 2 way interaction. Is that always the case?

**Comment by chrisdholt** [comment]
> Pairing _dialog_ to _popup_ would necessarily mean _popup_ contains interactive content. Like a 2 way interaction. Is that always the case?

I think this allows for both types of content, whereas the inverse wouldn't be true.By choosing dialog it _may_ or _may not_ have it, but both are enabled which I think is a win.

**Comment by jonathantneal** [comment]
Hi there 👋 

This item is labelled for discussion in the next teleconference. @mfreed7, as an editor of the proposal and creator of the issue, would you be available and interested in discussing this in the teleconference for additional feedback?

If so, would this week or next week would best for you?

I’m also curious if anyone has assembled any pro/con lists applied to `<popup>`, `<popupdialog>`, and `<transientdialog>`?

**Comment by scottaohara** [comment]
@jonathantneal this might be stale?  see Mason's pr for the updated `popup` proposal where it is no longer an element.  though, bikeshedding on the name of the attribute may still be a topic of discussion.  but per your mention of pro/cons to different element names, that's no longer applicable.

**Comment by mfreed7** [comment]
Thanks for the ping - this is definitely stale. In fact, I'm going to close this. There are some issues around naming, but I'm not quite ready to discuss them tomorrow.
