### ISSUE TITLE
meta: cowpaths research?

### ISSUE THREAD

**Issue by bkardell** [openui/open-ui#424]
So far in openui, someone opens an issue suggesting we take up some specific ui pattern which seems to be common.. We make a prelimary decision, find intersted parties and then we begin research.  

That's great, but there's a completely different end of this that is equally (maybe even more) intersting to me, and I wonder if others in OpenUI might also be interested in it.
 
We need better ways to observe (and interpret) what custom elements are 'successful'. We need this for many things, of course, but here there is a large focus on new elements, and custom elements are sort of the closest field trials/things mapped closest to the platform attempting to solve problems, and they're sometimes a way to change things while we still can based on that feedback[1]   

I started looking into it myself in 2018 and based on that, in 2019, @zcorpan and I helped modify some capturing in the HTTPArchive for this purpose.  I/we built [a tool](http://rainy-periwinkle.glitch.me/) that lets us quickly and easily (and for free) to explore any time period's data-set with regular expressions against element names with it manually.  In 2020 we made some improvements to both, and in 2021 we streamlined this to make each time period available to easily import to the tool.  I have also now begun added the ability to automatically track some trends - for example [this view shows custom elements that appear in every dataset and increased adoption every time](http://rainy-periwinkle.glitch.me/popular/mobile)... But, there's lots more we can do here - debates on how to sort through signal from noise, additionally useful views, etc.  My idea is to find a way for a group to idenitify and quickly narrow on things we can investigate and inform work here.

Is this interesting to anyone else?

[1] - I've used this on some other standards efforts with popular polyfills where we learned a lot along the way from actual use in the wild that I believe made the standard proposed in the end very considerably better.

**Comment by gregwhitworth** [comment]
I don't see how more data can hurt and it can also heavily help in prioritization of which elements get focused on by the team. Additionally, to your point, if there seems to be a custom element that is drastically increasing across the web it may be a great one to use as a starting point but I'd expect at that point we'd be back to Stage 0 where research would still need to be done. I for one am all for it and thanks for sharing the data. Any chance you'd be open to doing a brief presentation on this and how we can incorporate it into Open UI? It doesn't need to be drastically formal in any way.

**Comment by bkardell** [comment]
Yeah definitely open to doing that, whenever

**Comment by bkardell** [comment]
In case anyone missed it, but is interested, I recorded a version of the presentation at https://www.youtube.com/watch?v=T-B3Ds-NK-I

@gregwhitworth has created a channel in the discord to discuss `real-world-data` (the link it shows me is https://discord.com/channels/714891843556606052/919019808429846649 but I'm unsure how well the urls hold up?)

@davatron5000 and I reached out to the web components cg as suggested as well..


Please join if we want to carry on discussing this, I guess I can close this issue for now?
