### ISSUE TITLE
Suggest PrimeReact as another reference

### ISSUE THREAD

**Issue by SealOfTime** [openui/open-ui#437]
[PrimeReact](https://www.primefaces.org/primereact/) or the RIA framework it has originated from [PrimeFaces](https://www.primefaces.org/), despite sometimes lacking documentation, is a very feature-full solid UI library. 
From my point of view, the Prime family of UI libraries has quite different approach at UI library design - introducing a lot of options for customization out of the box, rather than relying on the extensibility of components. I believe, this could broaden the Open-UI research's approach at UI components' design and positively affect the results of the initiative in the long run.

The amount of components that PrimeReact implements is quite enormous to be listed here, but it includes the old classics like DataTables, Selects (and TreeSelects, MultiSelects), DateTime input and fresh peculiar ones like Knob (may be called Dial in a different library), MultiStateCheckboxes and etc.

**Comment by gregwhitworth** [comment]
Thank you for filing this @SealOfTime - we have documentation on how to add a design system here: https://open-ui.org/design-system-analysis-guide

Feel free to create a PR to add PrimeFaces.
