### ISSUE TITLE
[popup] stacking context

### ISSUE THREAD

**Issue by yinonov** [openui/open-ui#443]
##### (not sure this meets popup criterion or it may have been addressed elsewhere. will transfer if need)

lately I've been facing more than a few issues regarding web components needing to popup an element to the document (e.g. **snackbar**, **select**, **dialog**, **textfield** triggering **date-picker** etc').

in such scenarios, these components act as services, proxying configuration to be reflected in the popup.
their order of appearance / position in the DOM is irrelevant to their [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context) and commonly required to nest in specific html scopes. 

This causes issues with layout and containment and more...

a suggested solution can be having a common singleton element (typically placed at the end of the document to have high stacking value) that listens and receives requests from an event-based protocol. put that requires weaving a complete modular system together to cause a **popup** to be displayed.

not sure how well this scales as with integrated components, much can be changed in the document and there's no control over the styling and extra dynamic overlapping elements authors can introduce.

##### select: custom-element
![image](https://user-images.githubusercontent.com/15140652/150337326-04a63404-0dbf-40b9-addf-376e0dbb733d.png)

##### select: native
![image](https://user-images.githubusercontent.com/15140652/150337276-509dbfac-e011-4d75-843f-b5c53f3c0ac2.png)

**Comment by EisenbergEffect** [comment]
Here are a couple of related explainers you might want to take a look at:

* [Popup](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Popup/explainer.md)
* [Anchored Positioning](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/CSSAnchoredPositioning/explainer.md)

Let me know if you think the combination of these two would address your scenarios.

**Comment by scomea** [comment]
Look at tooltip.  It uses an anchored-region in "fixed" placement mode which makes it easier to break out of parent containers, of course fixed placement means the component won't automatically track the thing it's anchored to, so the region has to track and update the flyout position (it's quite fast at doing that, but you probably don't want too many such flyouts up at a time).

**Comment by yinonov** [comment]
I didn't notice before these explainers were by Microsoft 🤭

**Comment by yinonov** [comment]
relates to https://fullscreen.spec.whatwg.org/#new-stacking-layer

**Comment by mfreed7** [comment]
Given our work on the [Popup API](https://open-ui.org/components/popup.research.explainer), I'm inclined to close this bug. It sounds like your request is exactly what we're working on. I'm going to do that, but feel free to comment or re-open it if I've missed something significant.
