### ISSUE TITLE
Create a way to style the invalid messages in native form elements 

### ISSUE THREAD

**Issue by Nevraeka** [openui/open-ui#449]
Given an a form input implements the validation API (Element.validity) we need a way to style the messages. We can use :invalid or :valid to style the actual input in that state but there is no way to style the messages that appear in those states. A part or psuedo selector might be useful here.

I found this image showing different browser implementations here `https://webdesign.tutsplus.com/tutorials/html5-form-validation-with-the-pattern-attribute--cms-25145`

![image](https://user-images.githubusercontent.com/647043/151419670-2f72ca3f-3b98-459c-84a2-59e7e38bd83b.png)

**Comment by lukewarlow** [comment]
Closing as duplicate of https://github.com/openui/open-ui/issues/802
