### ISSUE TITLE
New Approach for Popup

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#455]
There has been extensive debate (e.g. https://github.com/openui/open-ui/issues/410 and https://github.com/openui/open-ui/issues/417, plus numerous OpenUI meeting discussions) about the [`<popup>` element proposal](https://open-ui.org/components/popup.research.explainer). That proposal got "stuck" on what appear to be some [rather fundamental questions](https://github.com/mfreed7/popup#alternative-dedicated-popup-element) about the semantics and associated AX roles for this new element.

As a result of these issues, we've put together a [fresh proposal](https://github.com/mfreed7/popup#readme) for a new way to achieve (roughly) the same list of [goals](https://github.com/mfreed7/popup#goals). This new proposal introduces an HTML attribute syntax that allows **any element** to be made into a "popup" that gets rendered on top of all other page content:

```html
<div popup=popup>I'm rendered on top!</div>
```

Here, the `popup` attribute is set to a value of `popup` (other values include `hint` and `async`) to indicate "popup" behaviors should be applied. That includes:
 * Rendering in the top layer
 * Automatically-provided light-dismiss and one-at-a-time behavior. (These depend on the value of the `popup` attribute.)
 * Accessible by default

Additionally, another HTML attribute, `triggerpopup`, can be used for declarative triggering, so that this API can be used without any JavaScript required:

```html
<button id=picker-button triggerpopup=datepicker>Pick a date</button> 
<my-date-picker role=dialog id=datepicker popup=popup hidden>
  ...date picker implementation...
</my-date-picker>
```

In this case, the `<my-date-picker`> component starts out `hidden`, but when the `<button>` is clicked, the UA removes `hidden` from `<my-date-picker`> and the date picker is shown. As with all popups, once the user clicks outside, hits Esc, etc., the UA will light-dismiss it by adding back the `hidden` attribute.

Please take a look at [the new proposal](https://github.com/mfreed7/popup#readme), and add your comments here to this issue. Pull requests for changes are also great.

**Comment by mfreed7** [comment]
So this new approach was [discussed last week](https://www.w3.org/2022/02/10-openui-minutes.html) at OpenUI. I generally heard supportive comments, and didn't hear any (at least major) objections to the new approach. I'd really like to kick the tires by re-implementing the Chromium `<popup>` element prototype into a new `<div popup=popup>` attribute prototype. Before I do that, however, I'd love to hear any input or feedback. I'd hate to implement something that has a fatal flaw. Let me know what you think!

**Comment by mfreed7** [comment]
> @mfreed7 issues here or with your explainer doc?

Either way works for me! I'll try to listen to both and incorporate them back into the explainer.

> from my memory, the topic of `hidden` vs `open` seemed good feedback, and making this change would help realign with the aspect of the element's initial spec that was calling out use of `open`

Yep, this is a great point, thanks for the reminder. I had indeed taken a note to possibly change to an `open` attribute from the `hidden` attribute. There were several good comments to that effect in the meeting. Another related one was that by mapping the `open` attribute to the `visibility` CSS property, animations could still work in both directions. I'll make this change.

**Comment by mfreed7** [comment]
> Yep, this is a great point, thanks for the reminder. I had indeed taken a note to possibly change to an `open` attribute from the `hidden` attribute. There were several good comments to that effect in the meeting. Another related one was that by mapping the `open` attribute to the `visibility` CSS property, animations could still work in both directions. I'll make this change.

I've [updated the explainer](https://github.com/mfreed7/popup#html-content-attribute) to use `open` instead of `hidden`. It begs the question we already discussed on https://github.com/openui/open-ui/issues/311 about whether we actually need the `open` attribute at all. In contrast to the decision/discussion related to the `<popup>` element, I do think we'd need a CSS pseudo class at least, to allow styling things differently depending on whether the element is in the top layer. (That's discussed [here](https://github.com/w3c/csswg-drafts/issues/6965).) But it seems like perhaps we could get away with only something like an `initiallyopen` attribute that sets the initial state, and have the rest happen in the UA. Thoughts?

**Comment by andrico1234** [comment]
@mfreed7 , I'm closing this issue on account of the Telecon resolution. Feel free to re-open if you'd like to continue the discussion here 😄
