### ISSUE TITLE
Should the CSS Toggles API be able to declaratively open a popup?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#456]
The [CSS Toggles](https://tabatkins.github.io/css-toggle/) API proposal ([explainer](https://css.oddbird.net/toggles/)) provides a way for "state" to be set on elements, and for that state to be modified by other elements.

Should the change of a Toggle State be able to (easily) trigger/open a popup?

**Comment by lukewarlow** [comment]
This proposal has been abandoned for now so closing this.
