### ISSUE TITLE
Migrate `popup` explainer over to OpenUI 

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#477]
The new approach for `popup` was recently resolved in a recent [Telecon](https://github.com/openui/open-ui/issues/455#issuecomment-1050172067). After a brief discussion with @mfreed7, we can look to replace the existing [Popup proposal](https://open-ui.org/components/popup), with the brand-new [explainer](https://github.com/mfreed7/popup#html-content-attribute).

I'll open up a PR in the next few days for this

**Comment by mfreed7** [comment]
Done! 😄
