### ISSUE TITLE
Bring focusgroup work under the OpenUI umbrella

### ISSUE THREAD

**Issue by travisleithead** [openui/open-ui#480]
Hello Open UI folks! 

I'd like to move the [focusgroup explainer](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/Focusgroup/explainer.md) into OpenUI and continue iterating on it here. I think this community is the right place to continue to build consensus and get implementer feedback on it's "growing up" journey into HTML and beyond.

Note: Microsoft Edge engineers are currently working on early prototypes of this feature.

Thanks for your consideration!

**Comment by chrisdholt** [comment]
I’m for it @travisleithead! (Biased…)

**Comment by gregwhitworth** [comment]
Congrats @travisleithead
