### ISSUE TITLE
[selectmenu] button click behavior when the popup is open

### ISSUE THREAD

**Issue by luncheon** [openui/open-ui#486]
Currently, in Chrome Canary, if a `<selectmenu>`'s button is clicked when the popup is open, the popup closes while the button is pressed and re-opens when the button is released.

https://user-images.githubusercontent.com/7709610/158392030-d801e325-fee0-449f-9de2-c52ed7c2e78f.mp4

But I think it is preferable to close the popup on a button click when it is open, like `<select>`. What do you think?
(I don't know whether this is a specification or a Chromium implementation.)

**Comment by dandclark** [comment]
Thanks @luncheon for pointing this out. I agree it would make more sense to match the behavior of `<select>`.

The draft at https://open-ui.org/components/select is ambiguous about what the behavior should be, because it depends on whether the button's handling the click or the listbox's light dismiss behavior happens first. The order of these isn't specified.

After resolving on the desired behavior we could probably just add a note about which way it should work (and update the prototype accordingly).

**Comment by dandclark** [comment]
The decision here should probably be generalized to apply to the interaction between `triggerpopup` and light dismiss as defined in https://github.com/mfreed7/popup#declarative-trigger-the-triggerpopup-attribute (moving soon to open-ui via https://github.com/openui/open-ui/pull/490).

**Comment by mfreed7** [comment]
I think I'm in favor of redefining (or likely just more-carefully **defining**) the popup light dismiss behavior to **not** light dismiss if the [`triggerpopup`-based trigger element](https://open-ui.org/components/popup.research.explainer#declarative-trigger-the-triggerpopup-attribute) for any popup is clicked. I can't see what the use case would be for wanting that click to hide **and then immediately re-open** the popup. A third possibility would be that re-clicking the trigger element hides **and does not re-show** the popup? But that feels fairly opinionated to be a default behavior. Perhaps for that use case, you'd avoid `triggerpopup` and hook things up with JS instead?

**Comment by mfreed7** [comment]
Just to highlight the discussion here and on https://github.com/openui/open-ui/issues/508: the tentative conclusion we reached is that the default behavior for declaratively invoked popups is for the popup to "toggle". I.e. clicking the button will open the popup if it is currently closed, and close it if it's already open.

**Comment by mfreed7** [comment]
We've now discussed this behavior in even more detail (e.g. see https://github.com/openui/open-ui/issues/523). The resolved behavior is that `togglepopup` toggles when the button is pressed, `openpopup` just opens, and `hidepopup` just hides. I'm going to close this issue.
