### ISSUE TITLE
[popup] Adjust instances of solely mentioning aria-haspopup in explainer

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#496]
This issue was reported by @scottaohara [here](https://github.com/mfreed7/popup/issues/8), and is being moved to the OpenUI repo.

---

There are three instances of mentioning `aria-haspopup`,  two instances where it is mentioned specifically.  I suggest revising these instances to more generally mention that accessibility properties will be added, as necessary, depending on the value of the `popup` attribute.  

This is due to the fact that `aria-haspopup` may not always be the appropriate attribute (despite it's very fitting name) for the element that is invoked - e.g., possible tooltips.  There is presently discussion in the ARIA WG on if `aria-haspopup` can be modified to allow for more generally exposing that _something_ will popup, rather than the very specific values it allows for right now.

**Comment by mfreed7** [comment]
I believe this issue can be closed. There is now only one reference to `aria-haspopup`, [here](https://open-ui.org/components/popup.research.explainer#declarative-trigger-the-triggerpopup-attribute):

> When the triggerpopup attribute is applied to an activating element, the UA may automatically map this attribute to an appropriate aria-* attribute, such as aria-haspopup, aria-describedby or aria-expanded. There will need to be further discussion with the ARIA working group to determine the exact ARIA semantics, if any, are necessary.

Feel free to re-open this if you disagree.

**Comment by scottaohara** [comment]
nope, this being the only reference works just fine.  thank you!
