### ISSUE TITLE
[popup] Consider renaming `triggerpopup`

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#508]
To complete the trifecta of popup bikeshedding issues (along with https://github.com/openui/open-ui/issues/491 for `popup` and https://github.com/openui/open-ui/issues/500 for `initiallyopen`), let's consider renaming `triggerpopup`.

The purpose of this attribute is to link a button (or similar) element to a popup element, and enable the button to declaratively trigger (show) the popup. The functionality is described [here in the explainer](https://open-ui.org/components/popup.research.explainer#declarative-trigger-the-triggerpopup-attribute).

Suggestions appreciated.

**Comment by scottaohara** [comment]
This may be best decided once popup has been shed or shedded… whichever word is best for past tensing that. 

but, I personally like the terms trigger or controls which could be appended to whatever other word is chosen. though the latter is due to my familiarity with the aria-controls attribute

**Comment by una** [comment]
+1 `togglepopup` seems like a better idea here — 

1. This makes it possible to add this attribute to the "close" button within a modal popup.
2. It also enables open/close in a trigger button such as a select menu instead of just allowing that button to open it

**Comment by mfreed7** [comment]
One proposal to highlight from the meeting just now:

```html
<button togglepopup="id">This toggles the popup</button>
<button togglepopup="+id">This can only open the popup</button>
<button togglepopup="-id">This can only close the popup</button>
```

There are issues with ids that contain +/-, and the syntax is funny. But perhaps something like this as an approach?

**Comment by jonathantneal** [comment]
I did initially suggest symbols. A symbol would prevent conflicts with multiple IDs. This is not a direct concern of `togglepopup`, which is limited to a single ID. Avoiding ID conflicts may still be worth considering, tho, largely as a general practice to be leveraged in future APIs, and lesser as a matter of future-proofing.

However, I would not prefer a pattern using **HYPHEN MINUS** (`-`), as that character overlaps with working IDs.

**Example**:
```html
<style>[-id] { color: blue }</style>
<span -id>this text will be blue</span>
```

I would recommend a **SOLIDUS** (`/`) to separate an ID (or IDs) from additional arguments. In the case of `togglepopup`, a “force” argument.

**Example**:
```html
<button togglepopup="id">makes the popup open or close</button>
<button togglepopup="id / open">makes the popup open</button>
<button togglepopup="id / close">makes the popup close</button>
```

If the separator is acceptable, the second argument can still be bikeshed. In the example above, I set a second argument of `open` or `close`. Perhaps it could also be `toggle`. Perhaps it could be `true` or `false`, mirroring [`DOMTokenList`](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle). Perhaps it could be `0` or `1`,  mirroring the [CSS Toggles](https://tabatkins.github.io/css-toggle/#checked-pseudoclass) proposal. I only mention this to separate the `open` and `close` keywords from the preference for a **SOLIDUS** (`/`) separator.

**Applying this pattern to some future concept:**
```html
<future-concept check="id">makes the thing checked or unchecked</future-concept>
<future-concept check="id / checked">makes the thing checked</future-concept>
<future-concept check="id / unchecked">makes the thing unchecked</future-concept>
<future-concept check="id / indeterminate">makes the thing indeterminate</future-concept>
```

**Comment by mfreed7** [comment]
+1 to using SOLIDUS as a separator, or at the very least not using something that can appear in IDs. I added the `+/-` to my example just because that's what I heard at the meeting. Thanks for pointing out the issue.

I kind of like your proposed syntax. Is there any equivalent API on the platform, or would this be a brand new pattern? (I think it's new.)

```html
<button togglepopup="id">makes the popup open or close (toggle)</button>
<button togglepopup="id / toggle">makes the popup open or close (toggle)</button>
<button togglepopup="id / open">makes the popup open but not close</button>
<button togglepopup="id / close">makes the popup close but not open</button>
```

Personally, I don't like `true/false` or `0/1` because it's confusing. What does `togglepopup="id / false"` mean? Don't toggle? Only close? I think your original `open/close/toggle` naming is the most clear and readable.

**Comment by mfreed7** [comment]
In working on the Chromium prototype, I think I found an issue with the concept of allowing multiple buttons to open/close a popup. In this example:

```html
<div popup=popup id=popup>Popup</div>
<button togglepopup=popup>Click me to *open* the popup</button>
<button togglepopup=popup>Click me to *close* the popup</button>
```

Clicking the "open" button properly opens the popup, and in doing so, registers the first button as the "invoking element" for the popup. Subsequent clicks on that same button are therefore ignored in the light dismiss logic, meaning a mouse-down on the first button doesn't immediately close the popup. However, if instead, the user clicks on the second button intending to close the popup, that mouse-down *is* a light dismiss trigger, since it isn't a descendent of a) the popup, b) the anchor element, or c) the invoking element. So that mouse-down closes the popup. Then the `togglepopup` behavior happens, which sees the now-hidden popup and "toggles" it back open. So the close button just causes the popup to flicker but stay open.

I suppose this could be fixed by adding more magic to the light dismiss algorithm, to check whether the clicked element is a descendent of a button that *also* points (via `togglepopup`) to the popup element, and if so, avoid light dismissing the popup. That seems like it'll work, but I wanted to bring this up in case there are better suggestions.

One bonus, I think, is that if we go this route, we don't actually have to store the invoking element on `Element`. We can just check for `togglepopup` on ancestors as we walk up the tree, and if they point to an open popup, count them as ancestral popups.

**Comment by mfreed7** [comment]
Note the resolution from the meeting just now:

```
<flackr> Resolved: add two more attributes, 'openpopup' and 'hidepopup' which only
open or close the popup. These, plus 'togglepopup' would only take an idref as a
value. We would define how precedence works when more than one of these
attributes is used.
```

**Comment by mfreed7** [comment]
Just to clarify what I assume to be everyone's preference: the resolution above **should have said** `showpopup` and not `openpopup`. If there are objections to that, please open a new issue to discuss, and sorry about that!

I've opened https://github.com/openui/open-ui/issues/523 to discuss the rules for precedence. Given that, I'm going to close this issue as resolved.

**Comment by mfreed7** [comment]
> I suppose this could be fixed by adding more magic to the light dismiss algorithm, to check whether the clicked element is a descendent of a button that _also_ points (via `togglepopup`) to the popup element, and if so, avoid light dismissing the popup. That seems like it'll work, but I wanted to bring this up in case there are better suggestions.
> 
> One bonus, I think, is that if we go this route, we don't actually have to store the invoking element on `Element`. We can just check for `togglepopup` on ancestors as we walk up the tree, and if they point to an open popup, count them as ancestral popups.

I'm treating this issue like an implementation/spec issue at this point. I think it should be possible to get the behavior we want, and as I implement it in Chromium, I'll raise an issue if the above approach doesn't seem to be working.

**Comment by jh3y** [comment]
Thoughts from the call:

- Is there not a use case whereby a developer could want multiple popups on the top level?
- I like the idea of "toggle", "show", and "hide". For precedence, "show" or "hide" trump "toggle" IMO as they are more specific about what they are doing. If all three exist, it's a toggle. If "show" and "hide" exist, it's a non-issue too? Only issue is with varying IDs 🤔  If a button opens one and closes another, where does a11y come into that? Does it?
- +1 for ::backdrop It's one less thing for developers to worry about creating. If they want to create custom, they can.

**Comment by mfreed7** [comment]
Thanks for the comments!

> * Is there not a use case whereby a developer could want multiple popups on the top level?

I view that as the primary difference between popups and dialogs. Popups are "one at a time", which allows them to be light-dismissed. If you want more, `<dialog>` is your friend. If you think there's a use cases we're missing here, please open an issue!

> * I like the idea of "toggle", "show", and "hide". For precedence, "show" or "hide" trump "toggle" IMO as they are more specific about what they are doing. If all three exist, it's a toggle. If "show" and "hide" exist, it's a non-issue too? Only issue is with varying IDs 🤔  If a button opens one and closes another, where does a11y come into that? Does it?

I [posted](https://github.com/openui/open-ui/issues/523#issuecomment-1106667339) this on the [issue](https://github.com/openui/open-ui/issues/523) for you.

> * +1 for ::backdrop It's one less thing for developers to worry about creating. If they want to create custom, they can.

👍

**Comment by jh3y** [comment]
Awesome! Thanks @mfreed7 🙏 

Yeah, after discussing it some more, I think you could do a `popover` as an overlay to tackle that scenario of wanting more than one `popover` displayed at a time. The idea was like "Help" screens/tutorials where you have multiple call outs. I've yet to dig into `dialog` demos in-depth. Can you display multiple at the same time side by side then? I know you can nest them which is interesting.

Thanks for forwarding on my comments 🙏
