### ISSUE TITLE
[popup] Allow <div popup> as a shorthand for <div popup=popup>

### ISSUE THREAD

**Issue by zcorpan** [openui/open-ui#514]
https://open-ui.org/components/popup.research.explainer#html-content-attribute

> A new content attribute, popup, controls both the top layer status and the dismiss behavior. There are several allowed values for this attribute:
>
> - `popup=popup` - A top layer element following “Popup” dismiss behaviors (see below).
> - `popup=hint` - A top layer element following “Hint” dismiss behaviors (see below).
> - `popup=async` - A top layer element following “Async” dismiss behaviors (see below).

The proposal for popups is now a global attribute instead of an element or a set of elements for popups, as discussed in  https://github.com/openui/open-ui/issues/410#issuecomment-973271554

For developer ergonomics, I suggest allowing the empty string as a valid value that is a synonym to `popup`. That is, these should be equivalent:

```
<div popup=popup></div>

<div popup></div>
```

Since `popup=popup` looks the same as a boolean attribute, developers may expect the short form `popup` to work.

There are some enumerated attributes in HTML where the empty string is a valid keyword: `crossorigin`, `hidden`, `contenteditable`, `translate`, `preload`, `spellcheck`.

cc @mfreed7

**Comment by gregwhitworth** [comment]
Closing as the boolean option is being discussed in 491
