### ISSUE TITLE
[popup] Add ::backdrop to popup

### ISSUE THREAD

**Issue by una** [openui/open-ui#519]
Request to add [`::backdrop`](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop) pseudo-element to `popup` elements to enable modal behavior for popups.

Two quick examples:
- Creating dialogs with light dismiss (and other `popup` features)
- Popup navigation elements (separating menus like slide-in menus from the rest of the page content)

Similar to the `dialog` element, this may possibly require a specific way to open the popup as a modal (or not, since `popup` is always in top layer, and the presence of the `::backdrop` would be enough).

**Comment by scottaohara** [comment]
Agree with this idea.  Not all popups may need this, but it would be good if developers easily had the ability to add a `::backdrop` if necessary.

**Comment by mfreed7** [comment]
Note the resolution from the notes above:

```
<flackr> Resolved: add a ::backdrop pseudo element behind popups.
```

**Comment by mfreed7** [comment]
@una Per the discussion, would you mind opening a fresh issue, if you'd still like, to discuss whether there should be a **modal** popup capability? I'd like to close this issue as resolved.
