### ISSUE TITLE
[selectmenu] Should we drop support for attachShadow?

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#528]
The `<selectmenu>` element as originally proposed and prototyped in Chromium allows the author to call `attachShadow()` to swap out the control's user agent shadow DOM and replace it with a user shadow DOM. E.g. see:
https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md#shadow-dom-replacement
https://open-ui.org/prototypes/selectmenu#replacing-the-default-shadow-dom

The purpose of this was to give the author maximal ability to customize the structure of the control. However, in practice given the slot/parts structure we've chosen, the author can achieve the same customizability by swapping out both the button and the listbox. Given the following markup, none of the `<selectmenu>`'s default structure remains:

```html
<selectmenu>
  <button slot="button" behavior="button">My button</button>
  <div slot="listbox" behavior="listbox" popup="popup">
    <option>Thing 1</option>
    ...
  </div>
</selectmenu>
```

In any of the experiments that various authors have built using `<selectmenu>`, I've never seen an any usage of `attachShadow()`, or any case where using `attachShadow()` instead of slots would have made things meaningfully simpler or more elegant.

Supporting `attachShadow()` would complexity to both the specification and implementations. Currently, `attachShadow()` cannot be used on any element with a user-agent shadow DOM. Only the elements listed in Step 2 of https://dom.spec.whatwg.org/#dom-element-attachshadow are supported. Adding `<selectmenu>` here thus raises some tricky questions like https://github.com/openui/open-ui/issues/399.

Given the above I think `<selectmenu>` should not support `attachShadow()`. This is a pretty safe reduction in scope; if we decide not to support `attachShadow()` now but learn at a later date that it's needed, it could be added with low compatibility risk since `attachShadow()` throws if called on an invalid element.

**Comment by chrisdholt** [comment]
@dandclark it looks like there is an exception here though for custom elements. 

> If [this](https://webidl.spec.whatwg.org/#this)’s [local name](https://dom.spec.whatwg.org/#concept-element-local-name) is a [valid custom element name](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name), or [this](https://webidl.spec.whatwg.org/#this)’s [is value](https://dom.spec.whatwg.org/#concept-element-is-value) is not null, then:
>
>Let definition be the result of [looking up a custom element definition](https://html.spec.whatwg.org/multipage/custom-elements.html#look-up-a-custom-element-definition) given [this](https://webidl.spec.whatwg.org/#this)’s [node document](https://dom.spec.whatwg.org/#concept-node-document), its [namespace](https://dom.spec.whatwg.org/#concept-element-namespace), its [local name](https://dom.spec.whatwg.org/#concept-element-local-name), and its [is value](https://dom.spec.whatwg.org/#concept-element-is-value).
>
>If definition is not null and definition’s [disable shadow](https://html.spec.whatwg.org/multipage/custom-elements.html#concept-custom-element-definition-disable-shadow) is true, then [throw](https://webidl.spec.whatwg.org/#dfn-throw) a "[NotSupportedError](https://webidl.spec.whatwg.org/#notsupportederror)" [DOMException](https://webidl.spec.whatwg.org/#idl-DOMException).

I get the complexity but as part of a team that works in the custom element space I think this is both a powerful addition supported by the spec (above) and something that falls into the initial goals of the customizable controls efforts. Were this explicitly prohibited by the spec I would agree to support it, but IMO custom elements are explicitly called out for support and given that I think we should implement and support the specific nuance described above.

**Comment by mfreed7** [comment]
> I get the complexity but as part of a team that works in the custom element space I think this is both a powerful addition supported by the spec (above) and something that falls into the initial goals of the customizable controls efforts. Were this explicitly prohibited by the spec I would agree to support it, but IMO custom elements are explicitly called out for support and given that I think we should implement and support the specific nuance described above.

Unfortunately, `<selectmenu>` isn't a [valid custom element name](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) - it is a builtin element, because there is no dash in the name. And I think this would actually take significant work to specify - no other builtin element that might have its own UA shadow root allows replacement of the shadow root.

As mentioned in the OP, while it sounds like something powerful, it turns out to be just as powerful (in all examples we've seen so far!) to slot in content. @chrisdholt, is there a specific use case you have in mind for this feature, which isn't possible with slotted content?

**Comment by chrisdholt** [comment]
> > I get the complexity but as part of a team that works in the custom element space I think this is both a powerful addition supported by the spec (above) and something that falls into the initial goals of the customizable controls efforts. Were this explicitly prohibited by the spec I would agree to support it, but IMO custom elements are explicitly called out for support and given that I think we should implement and support the specific nuance described above.
> 
> Unfortunately, `<selectmenu>` isn't a [valid custom element name](https://html.spec.whatwg.org/multipage/custom-elements.html#valid-custom-element-name) - it is a builtin element, because there is no dash in the name. And I think this would actually take significant work to specify - no other builtin element that might have its own UA shadow root allows replacement of the shadow root.
> 
> As mentioned in the OP, while it sounds like something powerful, it turns out to be just as powerful (in all examples we've seen so far!) to slot in content. @chrisdholt, is there a specific use case you have in mind for this feature, which isn't possible with slotted content?

AH, I misread the initial nod to `this` in my quick response so I can see that this likely wouldn't apply. I think slotted content is fine for 99% of scenarios. My premise is not accurate after re-reading, so best to just ignore. :)

**Comment by mfreed7** [comment]
> AH, I misread the initial nod to `this` in my quick response so I can see that this likely wouldn't apply. I think slotted content is fine for 99% of scenarios. My premise is not accurate after re-reading, so best to just ignore. :)

Cool! Thanks for the feedback. Definitely, if you think of one of the "1%" scenarios, it'd be helpful to know what it is.

**Comment by jonathantneal** [comment]
Just chiming in to +1 dropping support for `attachShadow`. Prohibiting ShadowDOM on an element with existing ShadowDOM seems consistent with other elements.

I want to note that an exception would be the declarative shadow root.

**Comment by dandclark** [comment]
Closing per the above resolution.
