### ISSUE TITLE
[selectmenu] Interoperability of styles

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#536]
Forgive me if there's already an issue discussing this, but I couldn't find one.

It will be important that the default styling of `<selectmenu>` be made interoperable. By that I mean that it should be easy/trivial for developers to get the same appearance across browsers, without dependencies on the particulars of the UA stylesheet's styling of the `<selectmenu>` element and its parts. However, I believe it should also be possible for UAs to have a default "branded" style for `<selectmenu>` that is unique across browsers, as is the case for other form controls.

To accomplish this, one approach might be:
 1. Specify `appearance:none` concretely for `<selectmenu>`, such that `<selectmenu style="appearance:none">` looks identical across browsers.
 2. Specify that UA stylesheet rules for the `<selectmenu>` must not contain any `!important` rules.
 3. Specify that UA stylesheet rules do not use the `::slotted()` selector to modify styles of slotted content.

I believe that with the above rules (and likely more that I'm not thinking about), it should be straightforward for developers to ensure interoperable styling by simply using `selectmenu {appearance:none}`. We should be able to write WPTs that confirm the above rules.

Maybe this isn't the right approach though. Ideas?

 @chrishtr @domenic @zcorpan

**Comment by domenic** [comment]
The basic problem with that approach is that it's opt-in interop, instead of the interop-by-default we try to shoot for with new web platform features.

**Comment by chrishtr** [comment]
There are two interop issues I can think of:

* UA defaults have different layout behavior w.r.t. surrounding content, leading to different layout.
* Developers accidentally rely on a UA style sheet (e.g. they don't override a UA-default blue background because their site likes that blue; it'll look bad in a UA without that blue background, causing interop issues for that other UA)

The first point seems to require a certain amount of well-specified *layout* for the selectmenu that UAs have to agree on, though it still leaves them free to specify an arbitrary visual look (so long as it doesn't affect layout), and also arbitrary styling of the default selectmenu popup, since it's not part of normal layout.

The second issue can be solved I think by ensuring that the UA stylesheet for selectmenu is inside of the UA shadow DOM, and disallows exposing parts to developers for styling (unless `appearance:none` is specified). Disallowing parts is necessary to prevent developers from applying a style to a shadow DOM part that accidentally relies on UA style sheet defaults.

**Comment by domenic** [comment]
I'm not sure how I understand how the second issue is solved by putting the UA stylesheet inside shadow DOM? (Or what that would even mean?)

Consider: UA 1 has a default background of blue for their selectmenu. UA 2 has a default background of yellow for their selectmenu. The web developer tests in UA 1, not UA 2. They write 

```css
selectmenu { color: yellow; }
```

Now they have a nice yellow-on-blue selectmenu in UA1 where they tested. But for users of UA2, the text in the selectmenu is yellow-on-yellow, i.e. invisible!

**Comment by chrishtr** [comment]
You're right. I take back my comment about the second issue.

**Comment by dandclark** [comment]
Maybe UAs should only apply author styles to the `<selectmenu>` if the author has specified `appearance: none`. This might be annoying for authors but brings us back to interop-by-default.

Alternatively, could UAs automatically switch to `appearance: none` for a `<selectmenu>` if they detect that the `<selectmenu>` or its contents are affected by any author styles? That would be more convenient for authors but I don't know if it's at all feasible.

**Comment by mfreed7** [comment]
@chrishtr and I discussed this today. Here's a quick summary of our thoughts:

- We agree that we need an "interoperability mode" for `<selectmenu>`, which guarantees identical visual results across browsers, when given the same HTML and CSS.
- Perhaps this "interoperability mode" should be the default, or perhaps it should be opt-in. It seems to us like this should be the default, but we'd love to hear developer input.
- There seem to be three options on the table for controlling this mode:
    - The CSS `appearance` property, where `none` would indicate interoperable behavior, and `auto` would indicate UA-themed appearance. The default could be `none`, if we want "interoperability mode" by default.
    - (Suggestion from @dandclark above) Automatically switch between modes, based on which CSS or HTML was detected.
    - Maybe we **only** need the interoperable mode. One concrete example of this is the `<dialog>` element, which has a basic [standardized set of styles](https://html.spec.whatwg.org/#flow-content-3), and no UA-specific styling. It seems like the vast majority of developers will want to style the `<selectmenu>`, given that this is basically the entire point of building this new element. So perhaps this meets nearly all use cases anyway?
- However the "interoperable" mode is controlled, we will need to come to agreement on exactly what those styles should be. Given the difficulty of that, we think the interoperable styles need to be fairly minimal, again similar to [the ones for `<dialog>`](https://html.spec.whatwg.org/#flow-content-3). Note that these styles do produce some visual output, such as setting border sizes and text/background colors. But just enough to make the control usable absent any CSS.

**Comment by zcorpan** [comment]
I thought that the idea was to only have the interoperable mode for `<selectmenu>`. If you want a native select, you can use `<select>`, at the tradeoff of being limited to plain text for the options' labels.

We can still add a native mode to `<selectmenu>` later, and use `appearance: auto` as the opt-in.

**Comment by mfreed7** [comment]
> I thought that the idea was to only have the interoperable mode for `<selectmenu>`. If you want a native select, you can use `<select>`, at the tradeoff of being limited to plain text for the options' labels.
> 
> We can still add a native mode to `<selectmenu>` later, and use `appearance: auto` as the opt-in.

I like that as a plan. Interoperable by default (though `appearance:none` by default), and a styled version if UA’s want to provide it, via explicit `appearance:auto`.

**Comment by gregwhitworth** [comment]
It's worth reviewing this issue that I opened on this a while back: https://github.com/w3c/csswg-drafts/issues/5998

And the `base` keyword to `appearance` in the [explainer](https://github.com/salesforce/standards-explainers/blob/master/indicator-psuedo/explainer.md#the-base-keyword-value-for-the-appearance-property).

> I like that as a plan. Interoperable by default (though appearance:none by default), and a styled version if UA’s want to provide it, via explicit appearance:auto.

So the premise is that `<selectmenu>` browsers will *only* ship the interoperable stylesheet by default? Given that the expectation is that over time these new controls/components will replace their current counterparts are UAs ok having very generic solutions ship? Given the discussions we had with Chromium revamp between MS and Google I doubt that would be the case given the focus on interactions, shadows, colors, etc. I could be wrong though.

**Comment by mfreed7** [comment]
A resolution so nice, we resolved it twice.

I've opened https://github.com/openui/open-ui/issues/552 to discuss what the default styling should be. I don't believe there are other embedded questions that weren't answered, but if someone has one, please raise a fresh issue. I'm going to close this one.
