### ISSUE TITLE
YouTube popup menu containing multiple nested select menus

### ISSUE THREAD

**Issue by flowstate247** [openui/open-ui#541]
![image](https://user-images.githubusercontent.com/13637602/170857736-9bc85724-44f7-44b4-99f8-9c6dd3705e3e.png)
![image](https://user-images.githubusercontent.com/13637602/170857516-32065f0f-5412-4ad8-9d75-089575996963.png)
![image](https://user-images.githubusercontent.com/13637602/170857527-36e2ceea-2def-4590-9347-9cd22e36f262.png)

I find this UI pattern very powerful and practical for users that are either using touch, mouse or keyboard.
It would be great if Open UI could facilitate the creation of such an UI.

**Comment by scottaohara** [comment]
These would likely be better represented as menu > menuitem / menuietemcheckbox / menuitemradio patterns.

maybe resurrecting the `<menuitem>` element for use within `<selectmenu>` would be something to consider.

**Comment by smhigley** [comment]
+1 to @scottaohara's comment. These look like they should be implemented as menus to me (and I've worked on very similar video player UI that used menus, not combobox/listbox semantics).

Even if we end up using menu semantics as the `<selectmenu>` popup, I think I'd still lean towards full menu semantics for this, since in my opinion the triggering elements should also be menuitems.

**Comment by josepharhar** [comment]
If you could call this a selectmenu, it would be a multiple select at the very least since there are multiple different sets of options to choose one (or more?) from.
I'm going to move the label to select-v2, I don't think that this is a use case that we are supporting in v1

**Comment by scottaohara** [comment]
closing this issue as it is not an appropriate use case for select / selectmenu.

These would be better communicated as menu > menuitem(checkbox/radio - as appropriate).  

If someone would like to open a new issue for creating a native "menu" element (unfortunately cannot be named `menu`) then, please do that.
