### ISSUE TITLE
[Documentation] Permalinks to anchored positions not working

### ISSUE THREAD

**Issue by bramus** [openui/open-ui#544]
I noticed that none of the permalinks to anchored positions – such as https://open-ui.org/components/popup.proposal.alternatives#alternative-dedicated-popup-element – are not working. This is because the `id` attributes on the headings are injected through JavaScript.

Preferably these `id` attributes are already in the content without the need for JavaScript. Awaiting a proper solution, a temporary and quick fix would be to extend the script that injects those attributes so that it also scrolls to the URL's hash.

**Comment by lukewarlow** [comment]
This is now longer an issue
