### ISSUE TITLE
[popup] The `popup` IDL attribute might not be web compatible

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#546]
A [bug was filed on the Chromium implementation](https://bugs.chromium.org/p/chromium/issues/detail?id=1332480) that might indicate some Web Compat issues for the `popup` IDL (Javascript) attribute. Because we resolved ([here](https://github.com/openui/open-ui/issues/491#issuecomment-1118927375) and [here](https://github.com/openui/open-ui/issues/533#issuecomment-1138874090)) that the `popup` attribute should reflect only valid (string) values, and should return `null` for invalid values, sites will break that already use `popup` as a property:

```javascript
const myElement = document.querySelector('foo');
myElement.popup = myBigComplicatedObject;
myElement.getAttribute('popup'); // "[object Object]"
myElement.popup; // null
myElement.popup.runMethod(); // Breaks, because popup is null
```

I'm not sure what the best solution is for this problem. The obvious one is to rename `popup` (the IDL attribute, not the content attribute) to something less common. And the downside of that is that it is confusing for developers that `myObject.newPopupAttrribute='auto'` results in `<div popup="auto">`. Another would be to revert to `myPopup.popup` accepting any value. To feature-detect the values of popup, we'd then need another mechanism, such as a different/new property: `myPopup.popupValidated` or something like that.

Suggestions?

**Comment by domenic** [comment]
> Another would be to revert to `myPopup.popup` accepting any value.

The "normal" version of this, where you just remove "limited to only known values" from the spec, won't work. That would just convert `el.popup = { ... some object ... }` to `el.popup = "[object Object]"`, which will break the site in the same way. I.e., all element reflection does string conversion; it doesn't matter whether you're limited to only known values, or not. You'd need to do something more dramatic.

Ideas:

1. Push through the compat issue. Doesn't seem promising since there are many JIRA instances in the wild.

2. Rename both the content and IDL attribute. `toplayer=""`/`topLayer` comes to mind! Also `popupbehavior=""`/`popupBehavior`... consider getting creative with suffixes/prefixes/etc. I know bikeshedding sucks but it might just be the best solution in this case.

3. Introduce an asymmetry between the content and IDL attribute. E.g. `popup=""`/`htmlPopup`, similar to `for=""`/`htmlFor` or `value=""`/`defaultValue`. Highly disrecommended; developers hate this and it's something we'd prefer to never do going forward. IMO this is strictly worse than (2).

4. Introduce huge hacks, such as, if the value being assigned is an object, overwrite the setter (similar to [`[Replacable]`](https://heycam.github.io/webidl/#Replaceable) but only if the given value is an object). This basically means JIRA (and other pages like it) can never use the `popup` IDL attribute, and more importantly libraries probably won't be able to assume that it exists, because some page might have done the dumb thing and overwritten it.

(2) looks like by far the best option to me.

**Comment by mfreed7** [comment]
Thanks for brainstorming ideas. I think I agree that <span>#</span>1 and <span>#</span>4 are likely off the table. In particular, <span>#</span>1  - this was found very quickly, and JIRA indeed has [widespread usage](https://www.atlassian.com/customers). 

Let's discuss the other two:

> * Rename both the content and IDL attribute. `toplayer=""`/`topLayer` comes to mind! Also `popupbehavior=""`/`popupBehavior`... consider getting creative with suffixes/prefixes/etc. I know bikeshedding sucks but it might just be the best solution in this case.

Ugh. But I think I agree this is likely the best option. But painful. Let the bikeshedding (re-)start.

> * Introduce an asymmetry between the content and IDL attribute. E.g. `popup=""`/`htmlPopup`, similar to `for=""`/`htmlFor` or `value=""`/`defaultValue`. Highly disrecommended; developers hate this and it's something we'd prefer to never do going forward. IMO this is strictly worse than (2).

I do realize this sucks for developers, but I think for this attribute, most of the usage will be via the content attribute. For example, in [the `<selectmenu>` demo](https://microsoftedge.github.io/Demos/selectmenu/), which heavily uses the popup API, all 44 uses of `popup` are via the content attribute, or CSS selectors on the content attribute. Perhaps we should (re-)consider the `popup=""`/`htmlPopup` pattern?

**Comment by domenic** [comment]
I think it really depends on what context you're using it. For static demo sites, sure, use the content attribute. But e.g. everyone who would ever use this API through React, would use it via the property, because that's how JSX works there. (I.e. in React-JSX you do `className=`, not `class=`; similarly you'd do `htmlPopup=`, not `popup=`.)

**Comment by mfreed7** [comment]
> I think it really depends on what context you're using it. For static demo sites, sure, use the content attribute. But e.g. everyone who would ever use this API through React, would use it via the property, because that's how JSX works there. (I.e. in React-JSX you do `className=`, not `class=`; similarly you'd do `htmlPopup=`, not `popup=`.)

It definitely depends on the context. In the React case, if you're using JSX (as I think/hope most uses would be), wouldn't the content attribute name be the one that matters? I.e. this JSX:

```jsx
<div popup={myPopupType}> foo </div>
```

would get transformed to:

```javascript
var reactNode = React.createElement('div', {popup: myPopupType}, "foo");
```

which should result (via [this code](https://github.com/facebook/react/blame/main/packages/react-dom/src/client/DOMPropertyOperations.js#L273), or [this code](https://github.com/facebook/react/blame/main/packages/react-dom/src/client/DOMPropertyOperations.js#L223) for custom elements) in roughly this JS:

```javascript
const div = document.createElement('div');
div.setAttribute('popup',myPopupType);
```

Of course, I could have this wrong, and that'd confirm your point about developer confusion.

**If** we go down the route of different content/IDL attribute names, I'd advocate for something that **starts** with "popup", so that autocomplete helps you. In general, here are some suggestions from a recent meeting (thanks @una, @jh3y, @argyleink):

- `myElement.popupAttr = 'auto';`
- `myElement.attrPopup = 'auto';`
- `myElement.popupValue = 'auto';`
- `myElement.poopup = 'auto';` (Mostly a joke, but it's catchy.)

**Comment by domenic** [comment]
> which should result (via [this code](https://github.com/facebook/react/blame/main/packages/react-dom/src/client/DOMPropertyOperations.js#L273), or [this code](https://github.com/facebook/react/blame/main/packages/react-dom/src/client/DOMPropertyOperations.js#L223) for custom elements) in roughly this JS:

No, that's not my understanding. It would instead result in

```js
const div = document.createElement('div');
div.popup =  myPopupType;
```

via [this code](https://github.com/facebook/react/blame/main/packages/react-dom/src/client/DOMPropertyOperations.js#L240) since [this code](https://github.com/facebook/react/blob/c88fb49d37fd01024e0a254a37b7810d107bdd1d/packages/react-dom/src/shared/DOMProperty.js#L205-L207) returns non-null because `popup`, as a standardized HTML attribute, will get added to the `properties` value in that file.

**Comment by domenic** [comment]
`popUp` could work. You would spell the feature "pop up" or "pop-up" in all documentation that wasn't about the attribute, similar to how you talk about an "enter key hint" for the `enterkeyhint=""` attribute, or the "image sizes" for the `imagesizes=""` attribute, or the "max length" for the `maxlength=""` attribute. Then it is natural that the IDL attribute is `popUp`.

I still think `toplayer=""` or `popupbehavior=""` are a bit better though.

**Comment by mfreed7** [comment]
> `popUp` could work. You would spell the feature "pop up" or "pop-up" in all documentation that wasn't about the attribute, similar to how you talk about an "enter key hint" for the `enterkeyhint=""` attribute, or the "image sizes" for the `imagesizes=""` attribute, or the "max length" for the `maxlength=""` attribute. Then it is natural that the IDL attribute is `popUp`.

Ohh I really like this suggestion. It nicely skirts the “content attribute not equal to IDL attribute” problem, and it’d be easy to change documentation to say “pop up” everywhere. I’d need to try it (or do the HTML Archive work) to see if it’s web compatible generally. But it at least fixes the one known breakage.

**Comment by dbaron** [comment]
FWIW, a suggestion (I think it was from flackr) which I liked, was the name `popupType`.

**Comment by dbaron** [comment]
https://github.com/openui/open-ui/issues/526#issuecomment-1157997881 should have been in this issue

**Comment by mfreed7** [comment]
Per the comment above, these notes should have been here:

The Open UI Community Group just discussed `https://github.com/openui/open-ui/issues/546`, and agreed to the following:

* `RESOLVED: Rename the IDL attribute from 'popup' to 'popUp'. Also change documentation to use the phrase "pop-up" rather than "popup".`

<details>
<summary>The full IRC log of that discussion</summary>
<pre>
&lt;JonathanNeal> topic: https://github.com/[/issues/526](https://github.com/openui/open-ui/issues/526)
&lt;JonathanNeal> github: https://github.com/[/issues/526](https://github.com/openui/open-ui/issues/526)
&lt;JonathanNeal> +1 to tantek’s suggestion
&lt;dandclark> masonf: We talked about this a few weeks ago. This is the question about declarative triggering for hint popups.
&lt;dandclark> masonf: Idea is you can put hint on any element. When you hover it, should trigger a hint. Like tooltip. Hover and it will show you tooltip about that thing.
&lt;dandclark> masonf: Initial proposal was to use differerent declarative name. Discussed maybe it would be better to reuse showpopup, togglepopup.
&lt;dandclark> masonf: My concern is there are use cases where that wouldn't work. Have button, want it to trigger popup, but also want a tooltip on that same element.
&lt;dandclark> masonf: Wouldn't be possible if you combine them.
&lt;dandclark> masonf: Also, what does hidepopup mean? Similarly togglepopup. For hints, doesn't make sense to hover the element, tooltip shows up, hover again, and it goes away. Triggering only goes in 1 direction.
&lt;una> q+
&lt;scotto_> q+
&lt;dandclark> masonf: So there's general confusion I have and I wonder if we should revisit the earlier decision.
&lt;JonathanNeal> q?
&lt;JonathanNeal> ack una
&lt;dandclark> una: You said it doesn't make sense to have hover toggle the tooltip. But we do want an action to hide the tooltip. Otherwise we don't be able to do things like animate tooltip out.
&lt;dandclark> una: it's tricky but with tooltip I want to make sure it's not just an open action, and we also have close event that gets triggered.
&lt;dandclark> masonf: Hint popup is still popup, has other popup behaviors includign show/hide events. And animation behaviors. So can animate based on :top-layer.
&lt;dandclark> masonf: There is proposed behavior for how it goes away, modeled on tooltips. After CSS configrable delay after user mouses out, can go away. Can animate that.
&lt;dandclark> una: There is use case you can create with this change
&lt;dandclark> masonf: If we do all the things in this proposal and add another attriubte, can do all the things asked for.
&lt;JonathanNeal> q?
&lt;dandclark> scotto_: Even in demos I was making for sub navigation popup, trying to have that show up on hover, I found I had to reach for JS events to show/hide. Seems that having additional attr to help with showing hints on hover and focus would be beneficial to people who want to have popup subnavigation
&lt;dandclark> scotto_: Hover it with mouse but want behavior to happen only on keyboard events.
&lt;dandclark> scotto_: Could do that with JS, but do we want to make it available to people without JS
&lt;dandclark> masonf: Tricky to do in JS. Handling of open/closed state.
&lt;dandclark> masonf: Suggestion is to make this behavior is to make this work for non hint popups too?
&lt;dandclark> scotto_: yes. There is use case for popup navigation. I don't necessarily like this pattern but it exists. People should be able to do this easily rather than futz with it in JS.
&lt;JonathanNeal> q?
&lt;JonathanNeal> ack scotto_
&lt;dandclark> masonf: In your demo, you hover over something, menu shows up. Goes away when de-hovered?
&lt;dandclark> scotto_: yes
&lt;dandclark> masonf: That's hint popup
&lt;dandclark> scotto_: It's not hint, it's subtnavigation.
&lt;JonathanNeal> q+
&lt;dandclark> masonf: Light dismiss desc for hint is different. It goes away when defocused. Also says you can't nest, but you have in this example. Interesting use case.
&lt;dandclark> JohnathanNeal: Would this work for other popups where that behavior would be appropriate? e.g. CSS property that specifies these things, would that solve this use case?
&lt;dandclark> masonf: You'd use non hint popup (auto), so you can nest it. Apply CSS property, control the fact that when dehovered, dismisses with CSS only. Could work.
&lt;dandclark> JonathanNeal: Similar to transition delays.
&lt;dandclark> masonf: Kind of , in that if you add this property with value you get new behavior. I'll think about that.
&lt;dandclark> scotto_: Demo is in popup chat.
&lt;masonf> q?
&lt;JonathanNeal> ack JonathanNeal
&lt;JonathanNeal> Up Next: Jonathan suggests `popup` itself becomes a CSS property. :P
&lt;JonathanNeal> Kidding... For now...
&lt;dandclark> masonf: Sounds like it needs more brainstorming.
&lt;JonathanNeal> my-button { pop-up: auto; }
&lt;dandclark> masonf: Undoing the last resolution? We need to use a different triggering attribute. Can't reuse others for this behavior, it's confusing and can't use both on same element.
&lt;dandclark> scotto_: I agree with that, particularly for my use case. want to auto show on focus but not hover.
&lt;masonf> Proposed resolution: use a new/different name for declarative hover-triggering of popups. Don't re-use togglepopup, showpopup, hidepopup.
&lt;dandclark> masonf: even for hints, example is that you get different poups for hover vs for click.
&lt;dandclark> s/poups/popups
&lt;scotto_> +1 to proposed resolution
&lt;chrisdholt> +1 to proposed
&lt;tantek> +1
&lt;JonathanNeal> Generally +1, but I don’t understand it well enough to feel authentic about it.
&lt;JonathanNeal> q?
&lt;masonf> RESOLVED: use a new/different name for declarative hover-triggering of popups. Don't re-use togglepopup, showpopup, hidepopup.
</details>

</pre>

**Comment by mfreed7** [comment]
Per the resolution, I'm going to close this issue, modify Chromium accordingly, and cross my fingers that we don't hit compat issues with `popUp`. If I do hit more, I'll open a fresh issue.
