### ISSUE TITLE
[selectmenu] Method to change arrow icon?

### ISSUE THREAD

**Issue by hidde** [openui/open-ui#548]
In our design system / authoring tool, we have a selectmenu-like component that uses a custom arrow:

<img width="168" alt="dropdown with as its icon a double arrow, one pointing up one pointing down" src="https://user-images.githubusercontent.com/178782/173187625-88765de1-b97f-4813-a904-4e25e286ebd9.png">

When I tried to recreate it with `<selectmenu>`, I got the default `<selectmenu>` arrow.

<img width="97" alt="select with arrow pointing down" src="https://user-images.githubusercontent.com/178782/173187694-0564be70-58fc-4b8e-b8e7-603c90ed9010.png">

I was able to insert my own arrow by creating a custom button (see linked Codepen below), but it would be nice to do it with the default button.

Could we add a way to change the arrow icon without replacing the entire button (maybe with `::marker`?)?

Related Codepens:
- [Example with my own custom button](https://codepen.io/hidde/pen/XWZyNqg?editors=1100) 
- [Example with just a standard selectmenu and options](https://codepen.io/hidde/pen/JjpeKQP?editors=1100)

**Comment by captainbrosset** [comment]
I agree that this would be useful. I wrote several demos with the selectmenu component, and for some of them I only wanted a custom icon. Having to replace the entire button part for this seems a bit much.

**Comment by chrisdholt** [comment]
We added a slot for the icon as well with FAST's select as well for this common use case. I'd love to see either `::marker` or a slot unique to this to support the simple scenario.

**Comment by mfreed7** [comment]
I’m going to miss the meeting today, but I wanted to register my support for this proposal. It would seem to make the most sense to just add a slot for the icon, akin to the other two slots we already have.

**Comment by gregwhitworth** [comment]
For ease of finding it in the minutes, the resolution was:

> Resolved: <selectmenu>'s shadow DOM has a <slot> around the button's default arrow icon so that the icon can be replaced by authors without replacing the entire button. The icon will also be exposed as a CSS `::part()`.

**Comment by dandclark** [comment]
I'm going to close this since we had a clear resolution. I filed https://bugs.chromium.org/p/chromium/issues/detail?id=1357866 to update the Chromium prototype.

**Comment by dandclark** [comment]
Reopening because I just realized we never decided what the name of the slot should be. Maybe `button-icon`? Or `dropdown-icon`, `arrow-icon`, just `icon`?

**Comment by chrisdholt** [comment]
> Reopening because I just realized we never decided what the name of the slot should be. Maybe `button-icon`? Or `dropdown-icon`, `arrow-icon`, just `icon`?

Unless there are multiple icons specifically within the anatomy I'd probably prefer to avoid unnecessarily prefixing if we don't have to.

**Comment by mahi072** [comment]
Hi @hidde, I would like to contribute in this issue if its still open.
Please guide me through this

**Comment by hidde** [comment]
@dandclark I see in the [editor's draft](https://open-ui.org/components/select)  and the [how to use](https://open-ui.org/prototypes/selectmenu) the 'marker' part is not included, do we want it updated and could I potentially help with that?

**Comment by josepharhar** [comment]
We resolved to add a slot/part for this and to name it marker, and it has been implemented in the chromium prototype, so I am going to close this issue
