### ISSUE TITLE
[selectmenu] Accept "option" elements through multiple slots

### ISSUE THREAD

**Issue by Westbrook** [openui/open-ui#565]
Referencing the awesome demos for this element available at https://microsoftedge.github.io/Demos/selectmenu/ I am thinking about how a developer might like to components the delivery of such a customization of the `<selectmenu>` element. This will likely be of high importance to design system developers who will need to ensure the newly possibly custom styling of this element is normalized across a broad field of usage.

For instance, working from the [Dribble Filter example](https://microsoftedge.github.io/Demos/selectmenu/#:~:text=done%20with%20divs.-,Dribbble%27s%20filter,-Custom%20toggle%20button) (for its simplicity, but the ideas below could easily apply to any of the demos listed), it would be great to be able to make a custom element to encapsulate the design delivery, while reducing the lift a consuming developer needs to recreate the visual and functional delivery via something like:

```html
<x-selectmenu>
  <option value="now" checked="">Now</option>
  <option value="week">This Past Week</option>
  <option value="month">This Past Month</option>
  <option value="year">This Past Year</option>
  <option value="all">All Time</option>
  <template shadowroot="open">
    <selectmenu id="timeframe-filter">
          <div slot="button" behavior="button">
            <button behavior="selected-value">This Past Year</button>
          </div>
          <slot></slot>
        </selectmenu>
    <style>
      button {
        padding: .5rem;
        border-radius: .3rem;
        width: 100%;
        text-align: left;
        box-shadow: 0px 0px 0px 1px #e7e7e9 inset;
        border: 0;
        background: white;
        color: #6e6d7a;
        font-size: 1rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1rem;
        cursor: pointer;
      }
      
      button:active {
        transform: translate(1px, 1px);
      }
      
      button:hover,
      selectmenu:focus-within button {
        color: black;
      }
      
      button:hover,
      selectmenu:focus-within button:not(:active) {
        box-shadow: 0 0 0 4px rgba(234, 76, 137, 0.1);
      }
      
      button::after {
        content: '';
        width: 1rem;
        height: 1rem;
        background: #e7e7e9;
        clip-path: polygon(10% 20%, 90% 20%, 50% 80%);
        transform-origin: center;
        transition: transform .2s ease-in-out;
      }
      
      selectmenu:focus-within button::after {
        transform: scaleY(-1);
      }
      
      [popup] {
        border-radius: .3rem;
        border: none;
        box-shadow: 0 0 .3rem rgba(0, 0, 0, .25);
        padding: 0;
        margin-top: .5rem;
      }
      
      ::slotted(option) {
        padding: .5rem;
        color: #6e6d7a;
        cursor: pointer;
        padding-right: 2rem;
        display: flex;
        gap: .5rem;
        align-items: center;
      }
      
      ::slotted(option:hover) {
        background: #e7e7e9;
      }
      
      ::slotted(option:checked) {
        color: #ea4c89;
      }
    </style>
  </template>
</x-selectmenu>
```

This way a consuming developer really only need to worry with:

```html
<x-selectmenu>
  <option value="now" checked="">Now</option>
  <option value="week">This Past Week</option>
  <option value="month">This Past Month</option>
  <option value="year">This Past Year</option>
  <option value="all">All Time</option>
</x-selectmenu>
```

Does it look like something we can expect the specification to cover?

In particular, the `<option>` elements are being passed through a `<slot>` into a deeper `<slot>` that lists the in the `<selectmenu>` as its options.

Neither of the current Chrome and Edge Canary releases seem to support this via [this Code Pen](https://codepen.io/Westbrook/pen/zYWqVgo), but hopefully this is just early days still and the move to open up the broader styling and usability of the styling on `<select>` style interfaces includes this capability.

**Comment by dandclark** [comment]
I expect the specification to cover this use case. The `<selectmenu>` should find its options using a "flat tree" walk, which is basically the view that you get after all the slotting has been resolved.

I haven't had a chance to dig into it yet but I suspect this is just a bug in the implementation where the `<selectmenu>` isn't finding the doubly-slotted `<options>`, or perhaps some issue with routing  events across shadow DOMs.

I'm spread pretty thin right now but as soon as I can I'll take a look and see if I can provide a fix.

**Comment by Westbrook** [comment]
That's awesome. Thanks @dandclark!

**Comment by josepharhar** [comment]
In the codepen, I can see the options being rendered in the selectmenu's dropdown, but clicking on them does not appear to change the selected option. Is that the bug?

**Comment by josepharhar** [comment]
I don't think this is an easy to support use case.

The selectmenu implementation uses child/descendant changes as a hook to look for new option elements, in addition to custom listbox/button/selected-value parts. If we were to allow other elements in the document to be slotted in and considered options, we would have to check for new option elements in the flat tree every time *any* node in the document is modified - something that I don't think we do for any other elements and would probably not be very performant.

One of the HTML editors is also against using the flat tree at all in HTML, so this would likely be hard to spec as well: https://github.com/whatwg/html/issues/8970

I would like to support this use case for custom elements if possible, but if we can't you can still do pretty much everything that selectmenu does through custom elements by using form-associated custom elements, declarative/imperative slotting, and the popover attribute.

I propose that we don't support this use case, but I'd like to see what others have to say so I'm going to agenda+ this issue

**Comment by Westbrook** [comment]
> you can still do pretty much everything that selectmenu does through custom elements by using form-associated custom elements, declarative/imperative slotting, and the popover attribute.

Feels like if this was fully true that we’d never have needed `<selectmenu>` in the first place. 

With all of the content that can be slotted here, it makes sense that there would be a lot of complexity here. If the answer was really to lean towards “no” here, is it crazy to investigate partial support here? No idea if it still hits the same issues, but could slotting `<option>`s directly into the `<selectmenu>` be acceptable, but not when slotting an options list? It feels like this is going to be a pretty widely asked for feature from my fellow developers, so a middle ground more so than a nothing here would be amazing!

**Comment by josepharhar** [comment]
Upon further investigation, it looks like the selectmenu implementation in chromium is already watching for all DOM changes in the document anyway when looking for child options and button/selected-value/listbox parts, so I tweaked it to look at the flat tree for options as well. This patch makes your codepen work: https://chromium-review.googlesource.com/c/chromium/src/+/4371978

At first I thought that we should have this slotting/flat-tree behavior for button/selected-value/listbox parts which would make it more complicated, but I realized that won't work properly since they must be slotted directly into the the selectmenu with specific slot attributes, which won't work with nested slotting. @Westbrook do you want to be able to nestedly slot custom buttons and listboxes for this use case, or is just options and anything else that would be put into the default slot in the listbox good enough?

I still think this will be hard to spec and I can't make any guarantees that it will survive the HTML spec review, but I suppose that I am now supportive and propose that we support this use case.

**Comment by Westbrook** [comment]
Thats great news!!

As a maximalist, looking to see if there are ways to make _everything_ "just work™️", would be more than amazing. There are a number of interesting slotting practices that could be leveraged here to interesting ends. I'd be hard press to whip up some practical use cases without some time to spend specifically investigating the pattern, however. In the end, as I mentioned above, some in better than none. If we can only get elements in the default slot, I'd call that a win.

Thanks for reporting back with your findings 🙇🏼

**Comment by josepharhar** [comment]
Here is a minimal example of the use case we're trying to support:
```html
<div>
  <template shadowrootmode=open>
    <selectmenu>
      <slot></slot>
    </selectmenu>
  </template>
  <option>one</option>
  <option>two</option>
</div>
```

**Comment by xiaochengh** [comment]
Wait, should we do this for options only, or for any part?

**Comment by josepharhar** [comment]
I thought that slotting in other parts might not be a thing you can do with shadowdom, but lets see if this example works:
```html
<div id=host1>
  <template shadowrootmode=open>
    <div id=host2>
      <template shadowrootmode=open>
        <slot name=two></slot>
      </template>
    </div>
    <slot name=one slot=two></slot>
  </template>
  <div slot=one>doubly named slotted element</div>
</div>
```
It looks like this doesn't work in any browser, so I don't think that doing this for other parts is currently possible due to limitations of ShadowDOM itself.
If this is something that we must have then we could try to change ShadowDOM to support this, but for now I think we can just not support it - at least until ShadowDOM supports slotting a slot element into a named slot.

**Comment by josepharhar** [comment]
Ah, I didn't think of that, thanks for making that example. I think that Dan felt strongly that we should just use the flat tree to support everything that isn't totally bizarre, so we should probably support this case. I'll see how hard it is to implement.
