### ISSUE TITLE
[popup] It is error prone to have both async and sync 'hide' event

### ISSUE THREAD

**Issue by smaug----** [openui/open-ui#578]
Mixing sync and async event dispatch is error prone.
If one removes a popup from dom (that triggers async hide) and then adds it back and opens the popup, there will be a sync show event, right? And then once the event loop spins, the async hide is dispatched even though the relevant popup is shown.

**Comment by mfreed7** [comment]
Hmm, this is an excellent point. Do you have suggestions for how to handle the fact that dispatching synchronous events is basically prohibited at some times, e.g. while removing the popup from the tree? The alternative (I guess?) might be to just **not** fire the event in those cases. Thoughts?

**Comment by smaug----** [comment]
I guess similar-ish issue might happen with focus/blur.
I can't recall how the blur is defined to work in this case
`
data:text/html,<input placeholder="focus me" onfocus="setTimeout(()=> this.remove())" onblur="document.body.textContent = 'blur fired'">`

**Comment by mfreed7** [comment]
> I guess similar-ish issue might happen with focus/blur. I can't recall how the blur is defined to work in this case ` data:text/html,<input placeholder="focus me" onfocus="setTimeout(()=> this.remove())" onblur="document.body.textContent = 'blur fired'">`

At least in Chromium, this is a special case added to ContainerNode::RemoveChild():

https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/dom/container_node.cc;l=724;drc=34ac5694a0cf645b70049f6c691056165d7e5b41

I'd like to avoid adding another special case for this event also, if possible.

Besides the point about nodes being removed from the tree, the other case I was hoping to avoid was when a pop-up is being hidden because a modal `<dialog>` or fullscreen element is moving into the top-layer. If we fire a synchronous `hide` in those cases, the event handler could preempt or mess with the dialog/fullscreen.

**Comment by mfreed7** [comment]
There seem to be only (?) two potential paths here:

 1. The existing behavior: fire `hide` **asynchronously** when a) the Element is removed from the Document, or b) a higher-priority top-layer element (e.g. modal dialog or fullscreen) is being shown.
 2. **Do not fire** the `hide` event at all in the two corner cases above.

Any others? I think my preference is <span>#</span>1, just because it feels even worse to skip events entirely. Yes, <span>#</span>1 can fire `show` and `hide` out of order, but only in *very* corner case situations. A combination of one of the two corner cases above, **plus** the immediate re-show of the same pop-up. I think out-of-order events likely cause fewer problems than missing events.

**Comment by tbondwilkinson** [comment]
The main use case for `hide` in the explainer is to add animations right? In the cases where `hide` is sent asynchronously, the animation use case is already invalidated.

Unlike `show`, `hide`, isn't cancellable so you can't use that to prevent closing (and even if you could, I imagine you wouldn't want to if the popup was removed from the DOM, which seems like something that shouldn't be cancellable).

In my opinion:
1. Not firing `hide` seems reasonable for when the popup is removed from the DOM. I think it's rare someone will do this, and I think it's reasonable to not get any event if it happens. Removing the element from the DOM is a different operation than "hiding" it.
2. For the top-layer UI case, I suppose it's fine to be asynchronous. I'm not really sure if I agree with the choice for hide to be asynchronous, wouldn't you might want to do simultaneous animations for opening a dialog and closing a popup? But that design decision has probably sailed.

**Comment by mfreed7** [comment]
Certainly one of the use cases for `hide` is starting animations. But another is saving state from the pop-up when it hides. For that reason, it would seem like we should always fire it, right?

The reason behind the asynchronous event in the “other top layer UI” case is perhaps outdated or not completely thought through. The idea was to avoid a pop-up being able to cancel a modal dialog in the `hide` event handler. But that could still happen if the event is asynch. Perhaps we should just fire it normally in that case too? Note that we also skip CSS hide animations in this case, to avoid the delay in closing. But perhaps we should just let them run also? Your example is interesting - you might want the pop-up to fade out while the modal dialog is fading in.

**Comment by josepharhar** [comment]
> If one removes a popup from dom (that triggers async hide) and then adds it back and opens the popup, there will be a sync show event, right? And then once the event loop spins, the async hide is dispatched even though the relevant popup is shown.

How about we just check some state in the async task to fire the hide event to see if it's still sane to fire the hide event...? and/or add some code in other spots to cancel any attempt to fire an async hide event. It seems like the best and easiest path forward to me.

**Comment by mfreed7** [comment]
Coming back to this issue, it sounds like perhaps there are three paths, not two:

1. The existing behavior: fire `hide` **asynchronously** when a) the Element is removed from the Document, or b) a higher-priority top-layer element (e.g. modal dialog or fullscreen) is being shown.
2. **Do not fire** the `hide` event at all in the two corner cases above.
3. (NEW) Fire `hide` **synchronously** when a higher-priority top-layer element (e.g. modal dialog or fullscreen) is being shown. Do **not** fire the `hide` event when the Element is removed from the Document, or perhaps fire it "later" (as discussed in the very related [focus fixup conversation](https://github.com/whatwg/html/pull/8392)).

I'm coming around to at least the first part of <span>#</span>3 - perhaps we should just fire the events synchronously. It's not like developers can't "cancel" the other top layer elements in other ways, and this would enable fading out a popover while a dialog fades in, for example.

> How about we just check some state in the async task to fire the hide event to see if it's still sane to fire the hide event...? and/or add some code in other spots to cancel any attempt to fire an async hide event. It seems like the best and easiest path forward to me.

I think we need a definitive set of logic - either we fire the event or we don't. It's hard for developers to code around an event that might or might not get fired, depending on state.

**Comment by mfreed7** [comment]
So in our discussion just now, there weren't too many conclusions, but it was a good discussion. I heard the following viewpoints:
1. Don't fire the "hide" event in the case that the element has been removed from the DOM. It is confusing to get what is normally a synchronous event asynchronously, after the thing has happened. (Side point, you might have opinions on https://github.com/whatwg/html/pull/8392)
2. Maybe make the "hide" event *always* asynchronous, which requires deferring all of the behavior until that async event runs. (My counterpoint: this makes lots of simple Javascript code confusing. E.g. `p.showPopover(); p.matches(':open') === false`.)
3. Question about ARIA: will `aria-expanded` still be in the correct state when the popover is removed from the DOM? Answer: yes, it should still be correct. This is just about the events.

Let me know if I missed anything, and more importantly, chime in with suggestions for ways forward here. In particular, we didn't discuss my proposal above to make the events synchronous (and animations-respecting) when modal dialogs and fullscreen elements are shown. I'd love input on that too.

**Comment by mfreed7** [comment]
Ok, at this point, I believe these are the open questions (assuming rough agreement with [my comment above](https://github.com/openui/open-ui/issues/578#issuecomment-1319133712)):

- Is it ok to *not* fire the "hide" event if a visible popover is removed from the document?
- If the answer above is "yes", then is it ok to always make "hide" synchronous, including when fired during a `dialog.showModal()` or `requestFullscreen()`?

If the answer to both is "yes", then I think we have a resolution to this issue. Note that the second point makes it "ok" to animate the popover "hide" while a dialog/fullscreen is being shown. That actually seems nice, from a user/developer point of view. Note that this will not delay the dialog/fullscreen showing, so I don't think there is much risk of "abuse" type behavior. We can always apply UA limitations to the duration of those hide animations, if needed.

**Comment by mfreed7** [comment]
FYI @jonathantneal and others, @domenic pointed out [this feature request](https://github.com/whatwg/dom/issues/533), from 2017, for exactly the Mutation Observer addition you requested. I.e. the ability to observe removals on the element itself. Perhaps you'd like to comment there? It doesn't seem like a big implementation burden, but perhaps I'm missing something.
