### ISSUE TITLE
[popup] Consider to dispatch show event as the first step of showPopup

### ISSUE THREAD

**Issue by smaug----** [openui/open-ui#579]
Currently there is
  1. Move the pop-up to the top layer, and remove the UA display:none style.
  2. Fire the show event, synchronously.

I'd expect show event to be cancelable (though such behavior could be added later too, assuming firing show is the first step).
Is there any reason for the current behavior?

@emilio

**Comment by mfreed7** [comment]
Thanks for the comment. In a practical sense, I don't think it would matter if we reversed the steps there, because only step 3 does any rendering. It would be an observable change, of course, but what I'm saying is that I'd definitely be open to that change.

We've discussed the cancelability of the `show`/`hide` events in the past, e.g. [here](https://github.com/openui/open-ui/issues/321#issuecomment-1138893574), and the conclusion we came to was that it ends up being a footgun. Practically, I think we were mostly concerned about the `hide` event though. Perhaps the `show` event is less of a footgun? What's the use case?

**Comment by smaug----** [comment]
It is partially an implementation detail why I'd prefer to fire event first and only after it change styling. There are cases where JS may spin event loop in Gecko, and I'd rather not change style right before that.

But also, based on the experience with popupshowing, I think making show cancelable is quite reasonable.
In XUL popupshowing event is cancelable. Some use cases seem to be:
tooltips, one may want to try to trigger a tooltip like popup as a reaction to something, but perhaps it is only the event listener itself which knows whether there is something to show. (I think something like that is done in 'Manage Bookmarks' code in Firefox)
And looks like similar thing for context menu type of case. Something triggers the popup, but only the listener code knows whether there is anything to show. (the code I'm looking at checks some preference value in the listener whether to show context menu)

**Comment by mfreed7** [comment]
Thanks for the cancelable use case examples. They seem reasonable. And changing `show` to be cancelable is easy enough, so I'm inclined to just do that. Agenda+ to discuss that.

@smaug---- would you agree it's ok to keep `hide` as non-cancelable, to avoid footgun-y interactions with the one-at-a-time and light-dismiss behaviors? One use case does seem to be making a "light dismissible dialog" which asks users for information, yet wants to be able to close in most cases if you click outside the dialog. But it also might want to confirm before closing in case you've changed something and want to save it or avoid data loss. That seems reasonable. My fear is that developers will be too tempted to try to manage the very things pop-up provides in the way of nested pop-ups, and interactions between popup=auto and popup=hint, for example. I'm torn.

**Comment by smaug----** [comment]
(XUL popuphiding is cancelable, but I couldn't find any case where the event is actually cancelled in FF code.)

I'm ok leaving hide as non-cancelable. I think it has fewer use cases and perhaps, if needed, it can be changed later.

**Comment by mfreed7** [comment]
Good point that it can be changed later. Ok, thanks.

For reference, I implemented (in Chromium) the change to "show", and didn't find any issues. I also implemented the change to "hide", but there is some trickiness to the ordering when you have a stack of pop-ups. So yes it'd be nice to tackle this later, if the use case arises.
