### ISSUE TITLE
<p> element parser rules cause content to be kicked out of <selectmenu>

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#598]
The HTML parser has special rules that auto-close `<p>` elements when certain other elements are encountered. See [this section](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inselect:~:text=A%20start%20tag%20whose%20tag%20name%20is%20one%20of%3A%20%22address%22%2C%20%22article%22%2C%20%22aside%22) and [this section](https://html.spec.whatwg.org/multipage/parsing.html#parsing-main-inselect:~:text=A%20start%20tag%20whose%20tag%20name%20is%20%22hr%22) of the HTML spec.

This will cause content to be unexpectedly kicked out of a `<selectmenu>` that's in a `<p>` element. Consider the following HTML:

```html
<p>
  <selectmenu>
     <option>item 1</option>
     <hr>
     <option>item 2</option>
  </selectmenu>
</p>
```

The resulting DOM after parsing is:

![image](https://user-images.githubusercontent.com/1688716/187270457-14221f4c-6447-4b9a-b406-c1b3d35b9192.png)

This will be surprising for authors and will be annoying to work around for them.

It is probably going to be an uphill battle to make any significant HTML parser changes; these have historically been a source of bugs, complexity, and interoperability problems. So one option is to just do nothing, and advise developers to be careful when using `<selectmenu>` inside `<p>` elements.

On the other hand, we might be able to copy the behavior of `<button>`, which can contain arbitrary content without auto-closing `<p>`. This may be as simple as changing all references of [has a p element in button scope](https://html.spec.whatwg.org/multipage/parsing.html#has-an-element-in-button-scope) to `has a p element in button or selectmenu scope`. The definition can be updated by just adding "selectmenu in the HTML namespace" as another bullet [here](https://html.spec.whatwg.org/multipage/parsing.html#has-an-element-in-button-scope). This change may be sufficiently simple not to raise too many concerns with implementors and spec editors.

Thanks @scottaohara for pointing out this issue at https://github.com/openui/open-ui/issues/540#issuecomment-1205801295.
cc @mfreed7 .

**Comment by josepharhar** [comment]
I don't think this needs any text in the explainer. I've filed a crbug to make sure this gets implemented: https://bugs.chromium.org/p/chromium/issues/detail?id=1427679
