### ISSUE TITLE
[selectmenu (& co.)] Figure out interaction with autofill.

### ISSUE THREAD

**Issue by emilio** [openui/open-ui#608]
The autofilled value is not supposed to be exposed to the page.

It seems somewhat tricky to do this with `<selectmenu>` for example.

**Comment by mfreed7** [comment]
> The autofilled value is not supposed to be exposed to the page.

Can you clarify? I think maybe you're talking about autofill **preview** values? The final autofilled value necessarily has to be exposed to the page, or you couldn't use the autofilled value. I.e. my credit card number has to get to the site eventually, right?

**Comment by emilio** [comment]
Yeah, I meant the preview, sorry.

**Comment by mfreed7** [comment]
> Yeah, I meant the preview, sorry.

Ok, thanks. Then can you elaborate a bit on why this is more tricky to do with `<selectmenu>` than with other `<input>`s? Our plan had been to treat it in the same way we treat other controls, which is to be very cautious about how we display previewed values, because the potential is always there for leakage.

**Comment by emilio** [comment]
My point is that it's unclear how would displaying a preview value here work with `<selectmenu>`. Given authors can style the "selected value" in whatever way they see fit, seems like it'd be either trivially observable by the page... Is autofill preview for `<selectmenu>` never intended to work? That'd be slightly unfortunate, but maybe it's ok...

**Comment by mfreed7** [comment]
> My point is that it's unclear how would displaying a preview value here work with `<selectmenu>`. Given authors can style the "selected value" in whatever way they see fit, seems like it'd be either trivially observable by the page... Is autofill preview for `<selectmenu>` never intended to work? That'd be slightly unfortunate, but maybe it's ok...

Yeah, it's a good point. I think the key thing is that autofilled values/previews are (always?) just plain text, and will likely either come from the `value` attribute or the `textContent` of the `<option>`. So if the autofill preview is just a painted bit of text above the `<selectmenu>`'s button, it shouldn't be observable at all. Right?

**Comment by mfreed7** [comment]
> So if the autofill preview is just a painted bit of text above the `<selectmenu>`'s button, it shouldn't be observable at all. Right?

For example, the preview text could be placed inside a `<div popover=manual>` which is inside the `<selectmenu>`’s shadow root. The contents of that div should not be observable at all.

**Comment by josepharhar** [comment]
> For example, the preview text could be placed inside a `<div popover=manual>` which is inside the `<selectmenu>`’s shadow root. The contents of that div should not be observable at all.

This is what we implemented in the selectlist prototype, and I will port it to the select with appearance:bikeshed prototype/implementation. Once the value is committed, then the page will be able to see the value and the select will be able to style it however it likes. Does this go against how autofill works for other replaced builtin form control elements?
