### ISSUE TITLE
Content Mirrors

### ISSUE THREAD

**Issue by jonathantneal** [openui/open-ui#616]
While discussing #571, there has surfaced a need to **mirror** another element.

In #571, to mirror another element is to render some node in another context, like a shadow tree, while being able to retain the contents, styles, or even interactivity of the original. This is similar to [slotting content](https://developer.mozilla.org/en-US/docs/Web/CSS/::slotted), only without the restrictions of only being able to slot child nodes.

Another quality of a mirror comes out of the implementation of #571, which is that the element is ‘moved’ into the shadow tree without removing the original node from the light dom. This is a kind of deep cloning, similar to what we do with an [svg `<use>` element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use). This implies that a mirror of an element can exist in more than one place.

**Possible Features**:
- Allows content to render in more than one place. (closest parity is `<use>`, https://github.com/w3c/svgwg/issues/511).
- Allows “clone”-like elements access to source events. (closest parity is the proposed `getEventListeners()`, https://github.com/whatwg/dom/issues/412)
- Allows deep slotting. (no known parity, https://github.com/WICG/webcomponents/issues/574)

There is an existing proposal for a [`<mirror>` element](https://github.com/whatwg/html/issues/6507) that may address these needs.

https://github.com/whatwg/html/issues/6507

Would we consider picking it up to move forward as a feature for the web?

This mirroring functionality has seemed very helpful and sometimes necessary to me when building components like [custom previews](https://code.visualstudio.com/docs/getstarted/userinterface#_minimap), [selects](https://github.com/openui/open-ui/issues/571), [progressive enhancement wrappers](https://github.com/WICG/webcomponents/issues/574#issuecomment-467178567), trees, [tables](https://css-tricks.com/responsive-data-tables/#aa-so-heres-what-we-are-gonna-do), and [multitracks](https://twitter.com/jon_neal/status/1577058168932536321).

Additionally, it seems like we would want some intuitive way for authors to opt-out of specific aspects of mirroring.

Very loosely, this kind of functionality seems possible by cloning a DOM tree and mirroring it with a MutationObserver. However, this will not allow the user to mirror events or styles.

This functionality also raises issues that I do not yet intuit good answers for.

- What exactly is shared in mirrors?
  - If I have a hovering effect on a mirroring source element, does that affect apply to the mirrored clone element, or vice versa, or is it something that I should configure?
  - If I have events on a mirroring source element, are those events applied to the mirrored clone, or vice versa, or is it something that I should configure?

Is this something we could pick up?

**Comment by yinonov** [comment]
please do! it is extremly useful with documentation referencing
whatwg/html#8287

**Comment by bkardell** [comment]
I'd still like this, but it is "stage 0" and also has [a similar open issue in HTML](https://github.com/whatwg/html/issues/6507)... I believe the main 'question' here is more to implementers than anything else, right? Do we need to keep this open, or can we close it and ask people to comment on 6507?

**Comment by bkardell** [comment]
We decided on the call today to close this
