### ISSUE TITLE
Rename `defaultopen` for popovers

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#631]
See the conversation [starting here](https://github.com/whatwg/html/issues/7785#issuecomment-1294296444) from the WHATWG html spec PR for popover. The issue is that `defaultopen` sounds too generic, yet there are myriad questions that would be raised by a "generic" version of the `defaultopen` feature.

So the request is to rename this attribute to something popover-specific, e.g. `popoverdefaultopen`.

Let's bikeshed a **popover-specific** name for this attribute.

Recall that we already discussed this in https://github.com/openui/open-ui/issues/500, but the new input is that this needs to be less generic.

**Comment by jh3y** [comment]
Thought this one might follow suit 👍

I do wonder if there is potentially the opportunity to line it up a little with `dialog` where the attribute is `popoveropen` and you could use that to drive the behavior too 🤔 Imagine that could potentially introduce some complications.

**Comment by mfreed7** [comment]
I commented on the WHATWG PR with [a summary of our discussion](https://github.com/whatwg/html/issues/7785#issuecomment-1310843461) today.
