### ISSUE TITLE
Broken images on select research page

### ISSUE THREAD

**Issue by gsnedders** [openui/open-ui#632]
https://open-ui.org/components/select.research shows a lot of broken image icons in both Safari and Chrome for me.

**Comment by josepharhar** [comment]
I see it too. There are a bunch of img elements with no src attribute or anything set. I wonder what they were supposed to point to...
I'm having a hard time finding where the images are in `research/src/pages/select`

**Comment by andrico1234** [comment]
Thanks for flagging! I'll take some time this week to investigate

**Comment by andrico1234** [comment]
It looks like the images were never added when the Select page was [created](https://github.com/openui/open-ui/commit/290a7552a7fdf955237ab6c6d0754672cf40a384).

e.g. [On line 661](https://github.com/openui/open-ui/commit/290a7552a7fdf955237ab6c6d0754672cf40a384#diff-648de5c9c7c66dd1b762523fad143e22aa893f04a2249b35667e54470f7a3caeR661), the `defaultValue` prop has been added, but with no reference to an image. Which results in the following:

![image](https://user-images.githubusercontent.com/17087167/216821158-633a637f-fab1-4dc2-9818-92066d7b931f.png)


I've added a change in the [Astro refactor PR](https://github.com/openui/open-ui/pull/606) to omit missing images and add text to explain which design systems are missing images, like so:

![image](https://user-images.githubusercontent.com/17087167/216821191-3d2f6ee0-1de0-429f-9dd7-867a0a27a1d3.png)

**Comment by bkardell** [comment]
It looks like the PR that fixed this has merged, can we close it now?

**Comment by josepharhar** [comment]
Yes, all the images look correct now

**Comment by josepharhar** [comment]
Removing agenda+ because I don't think we need to have a meeting about this
