### ISSUE TITLE
How to redirect URLs on open-ui.org

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#634]
In renaming the "Popup API" to the "Popover API", I've [renamed everything in the explainer](https://github.com/openui/open-ui/pull/629) (pending PR review and merging). However, the URL was left alone, as https://open-ui.org/components/popup.research.explainer. I'd really like to change that to https://open-ui.org/components/popover.research.explainer, but I would like to have a redirect from the "popup" URL so that links aren't broken. Can someone please tell me how that works with the OpenUI site?

**Comment by mfreed7** [comment]
@andrico1234 @gregwhitworth gentle ping. It'd be nice to be able to change the URL for popover.

**Comment by mfreed7** [comment]
@andrico1234 @gregwhitworth slightly less-gentle ping. The URL is still `popup`.

**Comment by gregwhitworth** [comment]
@mfreed7 thanks for the ping, I probably won't be able to get to this until next week as an FYI, @andrico1234 if you're able to get to it sooner please feel free.

**Comment by andrico1234** [comment]
Hi all! Sorry I didn't see these notifications!

I can take a look sometime this week :)

**Comment by andrico1234** [comment]
You should be able to change the file for "https://open-ui.org/components/popup.research.explainer" to behave like the [old Contribute](https://github.com/openui/open-ui/blob/main/research/src/pages/contribute.js) page. You can then point it to the new page with the correct URL. This is the way I did it a while back.

According to [Gatsby](https://www.gatsbyjs.com/docs/how-to/cloud/working-with-redirects-and-rewrites/), the idiomatic way would be creating the redirects within the `gatsby-node.js` file. I haven't done this approach before though.

I'm also happy to jump on a call if you need a hand

**Comment by mfreed7** [comment]
> I'll get a PR whipped up @mfreed7

Thanks for putting together a PR for this!
