### ISSUE TITLE
[popup] modals and toast stacking

### ISSUE THREAD

**Issue by kbrilla** [openui/open-ui#635]
I wonder how would one aproach stacked top layer approach when we have for example modal and toasts.

Let’s say toast are supposed to be topmost, 
and even modals should not cover them. 

In stacked approach this is not possible to achieve as let’s say we have
1. Toasts wrapper that is on top layer wchich holds all toasts. And then we have 
-toasts wrapper
-modal 
And now modal wants to show toasts and it end up being under it.
Solution (trick) hide and show again toasts layer to move it to top again - but that would introduce flicker , animation states problems etc.
2. Toasts shown individually then again we can and up with Toasts and modals one over another like
-toast
-modal
-toast
3. keeping toasts away from top layer but then again modal over them always.

so maybe instead it would be good to introduce something like top-layer-priority property that would hint on wchich level popover/modal (are modals popovers as well - is there a term that would incorporate all top-layer elements) should appear, and if two elements would have the same priority then stack order would apply. If a new popover would appear from within such element with such priority set it should be possible to inherit this priority or igonre it puting it on top most layer.

Then we can do something like this:
-toast wrapper popover (priority: 1)
-modal (priority : 2)
-hint popover - now we can decide if it should appear over toast or not as well.

There is also second problem with inert attribute when opening modals as modals. Again I would like to leave toasts active when modal is open but there is no way to prevent it - maybe something like preventinert attribute would be possible to achive - possible only applicable to popovers and other top layer elements and only if it’s priority would be higher than current inert applying modal - or maybe all such elements should be spared from jnert behaviour.

**Comment by mfreed7** [comment]
Sorry for the delay - I hadn't noticed this issue in the tracker. I've labeled it with popover so I keep track of it.

My general belief is that this line of reasoning starts a z-index arms race again, which inevitably leads to the need for a new "even higher top layer" that is over the top of the rest.

Instead, the design of the popover feature was such that it uses the existing mechanics of the [top layer](https://fullscreen.spec.whatwg.org/#top-layer), full stop. That does mean that the latest popover is topmost, and that can mean that a modal `<dialog>` can be shown on top of a `popover=manual` toast. However, in most typical use cases, that's the right thing for the developer/user: the latest thing to show up is shown top-most. It's generally always odd when a new thing shows up (e.g. a modal dialog) and it's displayed partially obscured underneath something that was already there (e.g. an existing toast).

Other thoughts? I'll add this to the agenda to discuss next year.

**Comment by mfreed7** [comment]
Thanks for the comments and discussion on this issue!

**Comment by kbrilla** [comment]
- I agree with the resolution that it would complicate things and maybe layers are no way to go but I worked on 2 big applications that heavily use dialogs and notifications like those:

1. open dialog to add np contact
2. you can click save or save and copy 
a) on save you will show "toast with successful creation information and link"
b) on save and copy you will show "toast with successful creation information and link" but you will keep the dialog open 
Big Boeing application so not a small one
- some toast show async which is maybe not the best thing but is required by the use case and needs to be shown even when dialogs are open
-  dialogs and toast have in/out animations and toast are stacking so hiding and showing them to keep the correct stacking order of top layer would require complex logic, disabling animations for this, and overriding display: none when popup container of toasts is closed for reshuffling
- 
![image](https://user-images.githubusercontent.com/22288449/210874821-88f58c8f-709d-40e4-9c41-bb814554201d.png)

So again I agree that my idea of solving this issue is not correct but such toasts and dialogs working together are what customers of web apps are expecting and I cannot agree that it's not a valid use case. Especially since those 2 apps are for completely different businesses and they both expect them. Push notifications of PWA applications could solve this issue but I'm afraid that customers don't like those and expect in-app notifications and toasts.
