### ISSUE TITLE
Should the button part of a SelectMenu toggle or show the listbox?

### ISSUE THREAD

**Issue by jh3y** [openui/open-ui#639]
Some SelectMenus in the wild have a button part that either opens the listbox and it remains open. Or, the button part toggles the listbox showing.

Do we have a way to support allowing the user to define how they want the listbox to behave?

Currently, the button part will keep triggering the opening of the listbox if you keep clicking it. This is evident if you have an opening transition on the popover that is used for the listbox: https://codepen.io/jh3y/pen/RwJrEye

cc @mfreed7

**Comment by scottaohara** [comment]
Agree.  The current select element works as a toggle (for the instances of where the brower's listbox popup doesn't cover the invoking element, and thus it can be clicked to verify).

**Comment by brechtDR** [comment]
I think the button should be a toggle indeed. This mostly for mouse / touch interactions. 

Quick side note:
The behaviour of focussing on the "first or currently selected" item when opening the listbox should remain as well as focus trapping inside the listbox. So the button should not be accessible with keyboard navigation for closing when the listbox is open.
(at least, that seems the default behaviour)

**Comment by scottaohara** [comment]
>as well as focus trapping inside the listbox

just clarifying, as that's not exactly the select element current behavior.  

Tab key will move not only move away from the select's listbox popup, it will cause it to auto-dismiss AND cause the last highlighted option to become the selected value for the component.   arrow keys, however, are limited to the listbox popup when it is open.

**Comment by brechtDR** [comment]
Agreed... This might be a whole other issue/question. I was indeed referring to the current state of the listbox.

**Comment by gregwhitworth** [comment]
cc: @dandclark

**Comment by brechtDR** [comment]
If I'm not mistaken... the current behaviour of clicking on the "button" of a select is that it triggers an "outside of the list click". At the moment, this isn't the case. So another question within this question is: "Should it be a button click that closes or be treated as an outside of the list click?"

This demo in Canary shows what I mean: https://codepen.io/utilitybend/pen/poKewPJ
Button has no effect, while outside click closes the listbox. Just some extra food for thought.

**Comment by smhigley** [comment]
+1 to the selectmenu button being a toggle trigger, both for click/touch as well as voice control and screen readers in virtual cursor mode.
