### ISSUE TITLE
default tooltip placement

### ISSUE THREAD

**Issue by NeilWix** [openui/open-ui#641]
As low vision users may benefit from a large cursor, placing a tooltip above the hovered content is recommended to avoid overlap of the cursor and the tooltip's content (as it happens when placing the tooltip below to triggering element).

**Comment by yinonov** [comment]
WAI task force hasn't agreed on a pattern and that sounds more related to that scope.
https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/

unless I've missed out, haven't seen an initiative regarding tooltip?

**Comment by gregwhitworth** [comment]
I agree with @yinonov - can you file an issue on WAI and then it can come back here to inform default styles of controls/components/primitives.
