### ISSUE TITLE
Popover: brainstorm ways around the lack (for now) of `popover=hint`

### ISSUE THREAD

**Issue by hidde** [openui/open-ui#643]
From [Westbrook Johnson on Mastodon](https://mastodon.social/@westbrook/109389726159139216), they would find popup API a lot more useful if it also had `popup=hint`: 

> Looking into `popover` and deeply effected by the removal of `popover="hint"`.
>
> Almost so that moving to `popover` without it causes more trouble than staying off of the API all together.
>
> Do you have any thoughts on how large the gap is between where things are now and getting "hint" into the implementation?
>
> Instead, I'm thinking to `popover="manual"` all of my Tooltips which leaves me with a new, more awkward custom stack of overlays to manage along side mixed x-browser support.

> The main issue I had is less how it's triggered... I'd still be handling that is JS either way. It's more that quality of stack member that it is:
>
> - force-closes only other hints
> - dismisses on close signal
>
> The other features are far less important, as this is what really sets `popover="auto|manual"` elements apart from `<dialog>.showModal()` elements for me.
> 
> I'm testing `popover="manual"` here because that's the closest I can see getting to allowing some interaction with the page below.

**Comment by jh3y** [comment]
Would be great to get an idea of what style of tooltip (assuming tooltip) was the desire with `popover=hint` 🤔 There are two main types I believe and one of the issues with continuing with `popover=hint` was around accessibility.

I think we can achieve "most" desired things with `popover=auto`. Especially if we are happy getting JavaScript involved in the meantime. The point on "force-closing other popovers" and "dismissing on close-signal" is similar to how `popover=auto` works.

I think where I'm a little confused, is those points are raised but then there's a desire for underlying page interaction which likely requires the use of `popover=manual`.

But, for anchored `popover=auto`, consider a rudimentary demo like this which is using `:hover` and non-implicit anchoring I'm afraid.

Demo: [codepen.io/jh3y/KKeJvXB](https://codepen.io/jh3y/pen/KKeJvXB)

**Comment by scottaohara** [comment]
I'm not sure I'd agree with any recommendation to try and roll your own hint.  I mean, sure it could be done per some additional work to the quick demo that @jh3y provided.  But why go to all that trouble to refactor a component to use popover, and THEN need to refactor it again to use the more robust hint feature when it's done and ready for release?

Per this line:
>The other features are far less important, as this is what really sets popover="auto|manual" elements apart from <dialog>.showModal() elements for me.

it seems there is a misconception that `hint` is the only thing that differentiates popover from modal dialogs.  And that's false.  @hidde did you provide correction to this misunderstanding?

**Comment by jh3y** [comment]
Yeah, agreed @scottaohara 👍 I'd be waiting on `popover=hint` in this scenario if you already have something that works.

On that possible misconception, I was a little confused around that part. Modality is a whole other thing we get from `dialog` and I couldn't work out the connection 🤔 😅

**Comment by mfreed7** [comment]
There are two points to this thread:
1. Express the need for the `popover=hint` use case. I agree with your points here, and I'd really like to push hard for re-landing all of the `popover=hint` stuff, including hover-triggering, in 2023. That is tracked in https://github.com/openui/open-ui/issues/617 (and summarized in https://github.com/openui/open-ui/issues/617#issuecomment-1329875678).
2. Brainstorm workarounds to the lack of `popover=hint` in the meantime.

I'm going to remove the popover label (having added it 2 minutes ago) because <span>#</span> isn't about shipping anything popover-related. Hopefully that works for people.

**Comment by mfreed7** [comment]
I'm going to remove the popover and tooltip labels from this issue, since this issue is about ways to do "hint type stuff" without actually using the Popover API, per se.

I'm not actually sure it's useful to keep this issue open at all. But I'll do that at least for now.

**Comment by lukewarlow** [comment]
I'm gonna go ahead and close this. With `interesttarget` and `popover='hint'` both actively in the works it doesn't make sense to keep this open.
