### ISSUE TITLE
[selectmenu] Add CSS selector to consistently select selectmenu parts

### ISSUE THREAD

**Issue by xiaochengh** [openui/open-ui#645]
There's currently no way to select a `<selectmenu>` part, especially if it's provided externally.

For example, if we want to select the listbox part:
* `selectmenu::part(listbox)` only works if we are using the listbox in the UA shadow DOM
* `selectmenu [behavior=listbox]` should work for most cases when the listbox is author-provided
* However, there doesn't seem to be a way if, e.g., the `selectmenu` is in a shadow DOM, and the listbox is passed through from an outer tree scope in a way similar to #565 

While this doesn't seem to be a big issue from the author's perspective (since the author should always know how to select the part they provided), it blocks the browser from adding a proper UA style sheet to position the listbox (as in this [Chromium patch](https://chromium-review.googlesource.com/c/chromium/src/+/4082046)). 

Should we introduce new CSS pseudo element selectors that can select the parts, regardless of where they are (whether in UA shadow DOM or not)? For example, `selectmenu::behavior(listbox)`.

This may be of interest for developers as well.

**Comment by gregwhitworth** [comment]
This is a great question and one I'll add to the agenda to discuss this week. I do agree that if this blocks the potential for a default UA stylesheet then we need a solution.

**Comment by xiaochengh** [comment]
Maybe it will also be useful for library authors, when they want to build a component based on a selectmenu and want to set a base style to it?

**Comment by josepharhar** [comment]
css-meeting-bot didn't pull the important part out of the details:
> Resolved: We recommend to add a new CSS pseudo selector of ::behavior which will allow selection within a shadow or light DOM

**Comment by josepharhar** [comment]
crbug: https://bugs.chromium.org/p/chromium/issues/detail?id=1412843

**Comment by lukewarlow** [comment]
This is addressed by https://open-ui.org/components/selectlist/#styling-parts-of-the-control
