### ISSUE TITLE
[popover] popover element auto-hide on right-click (context menu)

### ISSUE THREAD

**Issue by anilkumarum** [openui/open-ui#649]
I try to implement popover menu on right click. 
It is visible on right click but auto-hide immediately.
browser: chrome dev v110

Code to reproduce
```html
<button>Show popover</button>
<menu type="context" popover="auto" id="pop_menu">
        <li>Cut</li>
        <li>COpy</li>
        <li>Paste</li>
        <li>Save Link</li>
        <li>Save Image</li>
    </menu>
```

```js
const popmenu = document.getElementById("pop_menu");
        document.body.firstElementChild.addEventListener("contextmenu", (e) => {
            e.preventDefault();
            popmenu.showPopover();
        })
```
please confirm can we use popover element on right click??

**Comment by scottaohara** [comment]
tried to reproduce your issue but was not able to.  Does this example work for you, or does it autodissmiss as well?

https://codepen.io/scottohara/pen/PoBoJKM

**Comment by anilkumarum** [comment]
I update my code. test with updated code.

Your provided code is a hack.
I think default mechanism needed to fix right click auto-dismiss bug.

**Comment by scottaohara** [comment]
care to elaborate @anilkumarum ?  since my code was based on what you originally posted, calling it a hack isnt' very helpful in my attempt to help debug for you.

maybe it would be a good idea to provide your example where you're finding the problematic behavior? That way we don't have to guess about how to assist you?

**Comment by anilkumarum** [comment]
In your code, you manually call focus on button that's why i call it a hack.

If button element remove from these line
```html
<li><button role=menuitem>Cut</button></li>
<li><button role=menuitem>Copy</button></li>
<li><button role=menuitem>Paste</button></li>
```
then right click menu auto hide but visible in click.


As i understand, focusable element required to prevent auto hide.
`<li tabindex="0">Cut</li>`

Thanks for providing solution. I use this method in my project.

**Comment by scottaohara** [comment]
oh.  i see.  yeh, that's not a hack.  You need focusable elements to be keyboard accessible.  So, that makes more sense why yours wasn't working, because yours didn't include any focusable elements which are necessary to make it accessible
