### ISSUE TITLE
[popover] the complexity of triggering elements across multiple tree scopes (document or shadow root)

### ISSUE THREAD

**Issue by yinonov** [openui/open-ui#651]
As of now, the idref of 'popovertoggletarget' | 'popoverhidetarget' | 'popovershowtarget' must be in the same tree scope (document or shadow root) of the popover element. Reason is the chance of conflicting identical element `ID`s in the various trees.

```html
<button popovertoggletarget="my-popover">toggle popover</button>
<custom-element-1>
  #shadow-root
  <div id="my-popover">

<custom-element-2>
  #shadow-root
  <div id="my-popover">
```

Could triggering elements extend to work across tree scope boundaries?

that's quite a meaningful caveat considering triggering elements in real world use.

**Comment by mfreed7** [comment]
It's a good question. Due to the desire for an easy declarative API, IDREFs are indeed used and they are restricted to a single document or shadow root. However, the Javascript (IDL) reflections of these attributes allow arbitrary element references to be used:

```html
<button id=foo>Click me</button>
<div id=host>
  <template shadowroot=open>
    <div popover>My popover</div>
  </template>
</div>

<script>
foo.popoverToggleTargetElement = host.shadowRoot.querySelector('[popover]');
</script>
```

Does that meet your use case?

**Comment by yinonov** [comment]
absolutely!

**Comment by yinonov** [comment]
@mfreed7 

haven't found implementation details on handling the properties for the popover invokers. is there any reference authored by open-ui?

https://github.com/oddbird/popover-polyfill/pull/70#discussion_r1090592959
