### ISSUE TITLE
[selectmenu] alternative UX to unselect/uncheck selected values

### ISSUE THREAD

**Issue by NeilWix** [openui/open-ui#662]
I think that the mechanism of a slot="button" with the selected values, poses some discoverability and operability challenges for keyboard users. 
I'd like to suggest an alternative: 
Instead of popping out "bullets" of selected options, sort the selected items at the top of the options menu and <optgorup>'em as "selected items". A complementary mechanism should follow to inform users how many items are currently selected when the options menu is collapsed.

![image](https://user-images.githubusercontent.com/50541527/219388809-94fb9e24-7d0f-4411-aed0-ebcd673395f8.png)

**Comment by josepharhar** [comment]
This looks like a multi-select use case, which we are going to do in select-v2

**Comment by josepharhar** [comment]
Moving the selected options to the top of the listbox seems like something that should be possible with script, but I don't think is a great default considering that this is not what happens on android and ios's select multiple popups do and might not be expected. I also don't think it would be great for the browser to do significant dom changes to reorder the options this way.
