### ISSUE TITLE
Should we change the meeting day/time to be more inclusive

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#665]
The current meeting day is Thursday, and the time is:

- 11am PST
- 2pm EST
- 8pm CET
- 4am JST

It might be hard to be "convenient" in all of the above time zones. But what do folks think about moving the meeting to:
- 9am PST
- 12pm EST
- 6pm CET
- 2am JST

Other proposals/thoughts?

**Comment by gregwhitworth** [comment]
I'm game for a 9AM PST start.

**Comment by una** [comment]
SGTM

**Comment by dbaron** [comment]
Works for me (assuming the proposal is to stick with Thursdays).

**Comment by hidde** [comment]
For me personally 1hr earlier than the proposed time would be my preferenc as that makes it easier to attend for large parts of Asia too (and for me personally it is just before family/kids rush time, though not super important at all in the grander scheme of things).

**Comment by mfreed7** [comment]
Any chance I could re-open this issue and propose something closer to the original suggestion of 9am PST? I.e. move the meeting later by 1 hour? I've heard (private) comments from several participants that moving from 8am to 9am would help them a lot. Candidly I'm also one of those people.

**Comment by scottaohara** [comment]
i would (and anyone else in the ARIA wg) would sometimes have conflicts with a 9am pst time.  but that'd work great for me if it was, say, on a wednesday :)

**Comment by dbaron** [comment]
9am California time on a Wednesday would conflict with the CSS WG (except the first week of the month, when CSS uses a later time).

**Comment by scottaohara** [comment]
ah boo.  :(  well any other day also works.   silly conflicting wg meetings.

**Comment by mfreed7** [comment]
How about Monday 9am PST?

**Comment by mfreed7** [comment]
So there was general agreement that we should reschedule this meeting. Most people seemed happy changing to Monday, and there was some disagreement about which time would be the best. So here is a survey - please vote for the time(s) that work for you. Feel free to vote for more than one.

👍 - Monday 8am-9am PST
😃 - Monday 8:30am-9:30am PST
🎉 - Monday 9am-10am PST
😐 - Monday 10am-11am PST
❤️ - Thursday 9am-10am PST
🚀 - Thursday 8am-9am PST (current time slot)
👀 - Something else please!

**Comment by mfreed7** [comment]
Ok, thanks for all of the votes on the [comment](https://github.com/openui/open-ui/issues/665#issuecomment-1572303238) above! It looks like we've tentatively decided to accept the winning time of **Monday 10am PST** as the new meeting time.

**Comment by gregwhitworth** [comment]
@mfreed7 I'm considering re-opening this issue as we've unfortunately lost some a11y expertise and heavily engaged members in the voted time and somehow we didn't think about the many Monday holidays which will impact us 2 times over the next month alone.

I know that we had the option for _something else_ but I'm thinking we may want to take a step back and see what day works best for everyone and the group (eg: I probably won't vote for Monday given the holidays this time around) and then hours within the top voted days. That said, if I'm the only one wanting to re-visit this we can keep it as is.

cc: @brechtDR @dbaron @hidde @bkardell @una @scottaohara @gfellerph @dandclark @josepharhar @tbondwilkinson

Please vote:

👍 - re-opoen
👎 - do not re-open

**Comment by mfreed7** [comment]
So I'm in favor of re-opening this issue - let's make sure everyone who wants to be involved has a chance to participate.

Let's [re-use the comment above](https://github.com/openui/open-ui/issues/665#issuecomment-1572303238) to vote. It already has a "Something else please!" option if none of those times/days works for you.

If you haven't voted, now's the time!

**Comment by scottaohara** [comment]
re. choosing the something else option:
wed 11am EST (8am PST)
wed 12pm (9am PST) 
Thurs 11am EST (8am PST)
Fri 12pm, 1pm or 2pm  EST (9, 10 or 11am PST)
are additional times that'd work for me.

**Comment by mfreed7** [comment]
I've heard private comments that some highly-engaged folks can't make the new time. I'm wondering if it might make sense to have alternating week meeting times. For example, one week Monday 10am PST, and the other week another day/time. Would folks be interested in something like that?

**Comment by dbaron** [comment]
It may also be useful to do a more complete poll of times (e.g., on doodle or similar) that covers roughly 8am Pacific to 10am Pacific meeting start times for all of Monday through Thursday at hour granularity (or maybe half-hour slots where we could combine 2 adjacent slots that might not be hour-aligned).  Though I think the yes/no/maybe format isn't great for this, and yes/no/footnote might be better (so people can explain "will miss this time once per month" versus "probably won't make this time often because it's too early/late" versus other constraints), and I'm not sure if there's a good place to do such polls...

**Comment by hidde** [comment]
> I'm not sure if there's a good place to do such polls...

Maybe the W3C survey tool? I believe it can be used in a way that allows submissions from non W3C members?

**Comment by gregwhitworth** [comment]
I don't know of a better tool than Doodle even if it isn't perfect as @dbaron states. As such, I've spun up the following doodle poll: https://doodle.com/meeting/participate/id/e7XpVB1a

I recommend that we hold two meetings next week (limited to 30 mins each), one on the Monday (10AM - 10:30AM PST) we previously voted on to discuss this and on Thursday at the prior time (8AM - 8:30AM PST). Members will only need to attend one and I'll attend both (@mfreed7 feel free to attend both if you'd like) to get resolution on this for the following week (assuming the new day doesn't fall on the US holiday).

**Comment by scottaohara** [comment]
thanks @gregwhitworth.  i'm away this week, but will fill in the doodle with my available times asap

**Comment by brechtDR** [comment]
@gregwhitworth Thank you, one handy thing about this is that now more easy to calculate my timezone with a doodle

**Comment by bkardell** [comment]
If we're aiming for the time in the OP (seems like a good rationale) then Tues and Thursday are the best options for me that don't also have several occasional problems.  While Monday and Friday have plenty of times that might be appealing for me, generally Tues, Weds, Thurs are probably the best options to avoid the most bank holidays and vacation days.  Weds could be ok an hour earlier or later than that perhaps though I'm not sure it helps.

**Comment by flackr** [comment]
My availability would be roughly:
Mon 7-1 PST
Tues 7-1 PST
Wed 7-8, 11-1 PST
Thurs 7-10 PST
Fri 7-1 PST

Though I can probably make other times work by moving things around.

**Comment by brechtDR** [comment]
Mon-Thurs 9-10 PST is in general a good time for me, later is possible as well
Tues - Thurs: I can do 8-9 as well

**Comment by gregwhitworth** [comment]
The time is now Thurs 11am - 12PM PST.
