### ISSUE TITLE
Make CSS solution consistent across the whole site

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#674]
Recently, we completed our migration from Gatsby over to Astro. To ensure that we only changed the essential files during the migration, we didn't make our use of CSS consistent throughout the site.

As a result we have the following ways of applying styles in the site:

- global styles (e.g. global.css + reset.css)
- component css files (e.g. toggle-menu-button.css)
- styles in astro files (e.g. logo.astro)
- inline styles

I propose that we apply as much global styling as possible in `global.css` file to ensure that we write little CSS anywhere else.

We should also look to remove the amount of inline CSS as possible and only apply styles inline only when necessary.

In action, this means:

## global.css

Most of the code between line 281 - EOF will likely be removed (if unused), or moved to their respective components.
Resolved: https://github.com/openui/open-ui/pull/675

## inline styles

inline styles in `component-coverage.jsx` will be moved over to a corresponding `ccomponent-coverage.css` file.
The same goes for:
- component-layout.jsx
- component-name-matrix.jsx
- component-coverage.jsx
- concept.jsx
- concepts.jsx
- design-systems-list.jsx

**Comment by kant2002** [comment]
@andrico1234 I think I did cleanup for these things.
