### ISSUE TITLE
Support heading anchor links

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#677]
First, the new site looks great! Very fast.

Just one request, which was present on the old site: heading titles used to have a direct link icon next to them, making it easy to link to specific sections of an explainer. For example, the "Declarative Triggers" title here: https://open-ui.org/components/popover.research.explainer/#declarative-triggers. I used to be able to get that fragment link from a `#` directly next to the "Declarative Triggers" title, when I hovered over the heading.

Can we get that back?

**Comment by andrico1234** [comment]
Hey @mfreed7 , thanks for spotting!

Looks like @kant2002 , is already on it :) 

My apologies for missing this during the refactor
