### ISSUE TITLE
Add contributor bubbles to the Open UI site 

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#679]
The Astro site has an example for adding this to a site

Here's the link to the component they've made: https://github.com/withastro/docs/blob/main/src/components/ContributorList.astro
here's the page in the site: https://docs.astro.build/en/getting-started/
here's the usage of the component: https://github.com/withastro/docs/blob/main/src/content/docs/en/getting-started.mdx?plain=1#L114

**Comment by andrico1234** [comment]
CC - @jh3y

**Comment by jh3y** [comment]
Sweet - Wanna assign this one to me @andrico1234? I don't have the rights to self-assign 😁
