### ISSUE TITLE
Remove the Select element from proposals

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#683]
Now that `selectmenu` explainer has landed via #659 we should have the old one deleted. While we could just simply hide it from the menu I don't see the value in keeping it around since we're not actively trying to move this version forward.

**Comment by josepharhar** [comment]
There are two old select pages I can see:
1. https://open-ui.org/components/select/
2. https://open-ui.org/components/select.research/

Which one(s) of them do you want to delete? Should the path(s) be kept in use to redirect to the new explainer?

**Comment by josepharhar** [comment]
Ok I think I'm going to delete the first one and keep the second "research" one
