### ISSUE TITLE
[select] Consider making the popover-ness automatic

### ISSUE THREAD

**Issue by domenic** [openui/open-ui#703]
First, the explainer seems to be out of date and is using `popup=""` instead of `popover=""`.

But that aside, this is very weird:

>  The element with `behavior="listbox"` is required to be a `<div popup=popup>`.

There aren't any other cases I can think of in HTML where to get the effect you want, you have to trigger some other related effect. E.g., you don't have to do `<input type=text contenteditable>` to make it clear that text inputs are editable. You just get that for free.

Combined with #702 this could simplify the explainer's

```html
<selectmenu class="my-custom-select">
  <div slot="listbox">
    <div popup behavior="listbox">
      <option>Option 1</option>
      <option>Option 2</option>
      <option>Option 3</option>
      <option>Option 4</option>
      <option>Option 5</option>
    </div>
  </div>
</selectmenu>
```

into

```html
<selectmenu class="my-custom-select">
  <listbox>
    <option>Option 1</option>
    <option>Option 2</option>
    <option>Option 3</option>
    <option>Option 4</option>
    <option>Option 5</option>
  </listbox>
</selectmenu>
```

although I guess if you did #645 then even the `<listbox>` wrapper would not be necessary because you could just target the listbox in CSS.

---

This idea isn't free, as you need to think through some of the interactions on the API side. E.g. what happens if someone _does_ add `popover=""`? What does `listbox.popover` return by default? Etc. But I think this things are worth thinking through, to give a better developer experience.

**Comment by josepharhar** [comment]
I agree, I am doing this in the explainer here: https://github.com/openui/open-ui/pull/798
