### ISSUE TITLE
[select] The actual JS API surface and capabilities are not described anywhere

### ISSUE THREAD

**Issue by domenic** [openui/open-ui#705]
E.g. does this support normal form control semantics? Is it even form-associated? What parts of the JS API carry over?

I vaguely remember @josepharhar reassuring me in some thread that this was implemented, but I can't find it in this repository. In the meantime, the explainer has no such information.

**Comment by josepharhar** [comment]
Thanks for bringing this up, I will add form semantics to the explainer.
I have drafted the text for it here: https://github.com/openui/open-ui/commit/2f717332ad4b4b9d19ec8a7d38cc9373bd8f97ca
I will open a PR to add it to the explainer once this PR has been merged first: https://github.com/openui/open-ui/pull/707
