### ISSUE TITLE
Focusgroup move to WHATWG

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#734]
Is it worth moving the specification for focusgroup into the WHATWG html spec like had been done for popover?

Implementors may be more inclined to prototype and engage with the idea if it's at least as a PR in the WHATWG html repository.

https://github.com/WebKit/standards-positions/issues/171 for example has been marked as "concern: venue"

**Comment by gregwhitworth** [comment]
@lukewarlow the Open UI CG is meant as incubator, so popover graduated from here into WHATWG. Focusgroup was going to follow the same trajectory, but priorities and other situations occurred at the organization primarily driving the effort. That doesn't mean that someone won't pick it back up. Additionally, whether it's an explainer here or a PR in WHATWG it needs someone to champion it and invest the time into it. While not completely related, it does raise the question of whether we should mark some as "Archived" or "On Hold" if we don't have anyone actively driving it forward.
