### ISSUE TITLE
Modal dialog trigger without JS

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#736]
This may end up being superseded by a more generic thing such as https://github.com/openui/open-ui/issues/700

But I think the modality aspect warrants this being a separate issue.

Apologies if this is a duplicate

Currently (well soon) non-modal Dialogs can be shown by using popover attribute.

However, there's currently no way to load a modal dialog without using JS. This feels like a relatively simple but useful addition to the web.

**Comment by lukewarlow** [comment]
As a rough idea we could add a new modal attribute to the dialog element and then have a new modaltarget attribute on the button to match how popover works?

This is perhaps odd considering we now have popover which almost does the exact same thing?

**Comment by keithamus** [comment]
Refs https://github.com/whatwg/html/issues/3567.
