### ISSUE TITLE
[slider] `::-webkit-slider-container`

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#738]
While looking through the slider research I noticed that there isn't the concept of a "slider container". However, in side of Chromium and WebKit there's the `::-webkit-slider-container` pseudo element which afaict is basically the same as the range input itself but at least in Chrome internally is used for styling involving the slider ticks.

Not sure if this is something we want to document or if its more of an implementation detail.

**Comment by gregwhitworth** [comment]
I haven't had a chance to put time into a slide/range anatomy proposal, but here is a breakdown of research I did in the past on the various anatomies across design systems with part names and usecases: https://open-ui.org/components/slider.research.parts/

**Comment by gregwhitworth** [comment]
Moving this discussion to #770 and closing this one out
