### ISSUE TITLE
[popover] Dialog with popover-like triggers

### ISSUE THREAD

**Issue by una** [openui/open-ui#741]
When playing with `popover` recently, I ran into a scenario which I think will be relatively common: folks wanting dialog-like behavior (i.e. inerting content on the rest of the page when the dialog is open), with the developer ergonomics that `popover` and `popovertoggle` provide.

In this [example](https://codepen.io/una/pen/poxrJpK/643b91541a8de2f682d7b2d42449536e), I wouldn't want the rest of the page to be interactive while one of the popovers is open (you can see that I can still hover and click on buttons behind the popover `::backdrop`. Not ideal.

![Kapture 2023-05-01 at 13 35 30](https://user-images.githubusercontent.com/1693164/235513573-800a6330-a75e-42d8-9bb7-3788a74a7a8b.gif)

In this case, the popovers should probably be dialogs, but making them `<dialog>`, plus invoking them with `.showModal()` is the only way to get this behavior. Is there a way to get declarative popover-like developer ergonomics with dialog element semantics and behavior?

Some initial thoughts on solutions:

1. A new value for the popover attribute to clarify behavior such as `popover=modaldialog`
2. A seperate declarative trigger for dialog, such as `dialogtarget=foo dialogtargetaction=modal` (@mfreed7's suggestion)

**Comment by una** [comment]
Just saw #736, this might be a duplicate of that

**Comment by lukewarlow** [comment]
Happy to close my issue in favour of yours :)

**Comment by lukewarlow** [comment]
Text from my issue:

This may end up being superseded by a more generic thing such as #700

But I think the modality aspect warrants this being a separate issue.

Currently (well soon) non-modal Dialogs can be shown by using popover attribute.

However, there's currently no way to load a modal dialog without using JS. This feels like a relatively simple but useful addition to the web.

**Comment by mfreed7** [comment]
> Some initial thoughts on solutions:
> 
> 1. A new value for the popover attribute to clarify behavior such as `popover=modaldialog`
> 2. A seperate declarative trigger for dialog, such as `dialogtarget=foo dialogtargetaction=modal` (@mfreed7's suggestion)

I’m biased but I like option 2. I’m worried that `popover=modaldialog` is confusing for developers. If you’re building a dialog (and you are, in your example) then I think you should use a `<dialog>`. But let’s bring as much learning and functionality as we can from popover. I think that’s option 2. Separate attributes, because it’s not a popover. But functionally very similar.

**Comment by hidde** [comment]
> In this case, the popovers should probably be dialogs, but making them <dialog>, plus invoking them with .showModal() is the only way to get this behavior. 

Agreed, I would advise building these with `<dialog>`+`.showModal()`, but see the want to have something declarative here too. 

I am not big on suggestion (1) (a new value for popover that adds modal behaviour), I feel it would make it harder to teach developers the difference between `<dialog>` and `popover` (currently, modality seems to be a major differantiator; adding a way to do modal popvers would make the differences even more subtle).

I like suggestion (2), to be it seems like a no-brainer! There is a related discussion over at https://github.com/whatwg/html/issues/9167, where a more generic `openabletarget` attribute is proposed.

**Comment by lukewarlow** [comment]
Could we declare the modality on the dialog itself rather than on the toggle? This fits the pattern of popovers better where the type of popover is declared in the popover attribute. Potentially dialog="modal"? Not sure if this is web compatible though.

**Comment by una** [comment]
I would love if it could be as simple as:

```
<button popovertarget="my-dialog"> Open Dialog </button>

<dialog id="my-dialog" popover>
  ...
</dialog>

```

**Comment by tbondwilkinson** [comment]
I also had a discussion about this on #581. The feedback I got at the time was that popover was not intended to support dialog-like modals. I do think people will consistently reach for popover over dialog for modals, because of the new functionality.

**Comment by jimmyfrasche** [comment]
I'd like:
```
<button dialogtarget="my-dialog"> Open Dialog </button>

<dialog id="my-dialog" modal>
  ...
</dialog>
```

**Comment by lukewarlow** [comment]
https://github.com/whatwg/html/issues/3567

**Comment by mfreed7** [comment]
It looks like the discussion for this feature request is really happening over on https://github.com/whatwg/html/issues/3567. Should we close this issue, to avoid having it in two places?

**Comment by nt1m** [comment]
FWIW, `<dialog popover>` + `showModal()` wouldn't achieve the use-case as desired, as dismissing the popover dialog would leave the content inert.

**Comment by brechtDR** [comment]
@mfreed7 @una I think we can close it :) good to see so many thumbs up on the other issue, that should give it some weight. Seems like a lot of people found their way over there.

**Comment by una** [comment]
Closing in favor of https://github.com/whatwg/html/issues/3567
