### ISSUE TITLE
[accordion] Issues with current research

### ISSUE THREAD

**Issue by bkardell** [openui/open-ui#751]
Currently the [accordions research](https://open-ui.org/components/accordion.research/) mentions several design systems and attempts them up into, basically, groups of "exclusive" or "not exclusive" or "can do either".  

I think there are factual errors in what is there already. For example, it says "the following are never exclusive" and lists Fast, but according to the dropdown on the Fast site, [Fast can be exclusive](https://explore.fast.design/components/fast-accordion ). Similarly, under "  Similarly, under "The following are always exclusive:" is lists Semantic UI, however the site seemed to imply otherwise, and I followed [a link on it to and example showing otherwise](https://react.semantic-ui.com/modules/accordion/#usage-exclusive).

I didn't check them all, I simply came across these while trying to file another issue - but we should probably confirm and also expand the research, if we can.

**Comment by dbaron** [comment]
OK, I've reread the documentation more carefully for all of the libraries where I hadn't previously determined that there was more than one option, and made some further edits.  I'm going to call this fixed at this point, although that isn't a guarantee that everything is correct.  But I've at least checked it again.
