### ISSUE TITLE
Design Systems page probably could use updates

### ISSUE THREAD

**Issue by bkardell** [openui/open-ui#758]
It's been kind of a while since this project was started and a lot has happened since then.  Some of the links we have sort of no longer point to what is advertised. Auth0 Styleguide link, for example, doesn't.  Microsoft's things here are currently particularly confusing (@chrisdholt will provide more).  However, there have been plenty of additional developments since. Tabs research also considered some additional ones like shoelace, for example.  If we can get a decent crack at a list here, I'm happy to send a PR or three.

Note - there is a tricky aspect to this with two sides to it:  First, the components grid that was created initially is also kind of stuck in time in both respects. We could remove and add whole systems - but I think that is also not complete because there are abstract design systems and sometimes _N_ concrete implementations, and they don't  often agree.  We _say_ design systems but many implementations don't even refer to or share their design systems too.  I think we really have to look at all of them because, for example, we show some things as not having accordions, but some of their actual implementations do.

**Comment by gregwhitworth** [comment]
This is a generic issue as noted in the attached issues but I'm going to close this one and have us tackle them one at a time on the other issues.
