### ISSUE TITLE
Standardised tooltip styling

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#765]
https://github.com/w3c/csswg-drafts/issues/8930 thought it was worth bringing this discussion to this CGs attention

**Comment by scottaohara** [comment]
@lukewarlow well, that's interesting because I've been meaning to re-post this issue to the csswg to start moving that process forward https://github.com/openui/open-ui/issues/730

**Comment by scottaohara** [comment]
we could probably close this issue since we already had the linked issue open.  i've now linked that to the csswg issue.  :)
