### ISSUE TITLE
Multi Range Slider (slider with multiple handles)

### ISSUE THREAD

**Issue by brechtDR** [openui/open-ui#770]
Hi everyone.

I was thinking about something earlier this week about having the ability of a multi-range slider available in HTML such as we see a lot in webshops

<details>
<summary>Some screenshots</summary>

![slider1](https://github.com/openui/open-ui/assets/4632664/ff0173ba-ce34-4b7d-8995-f3fd97dc399e)
![slider2](https://github.com/openui/open-ui/assets/4632664/68614d11-d856-4ac1-956f-be53142d73b6)

</details>

we have the following in HTML already:
`<input type="range" />`

But as it currently stands there is no option to have multiple handles for this. So I was wondering if we could do something about this as a group. This is a UI feature that we see a lot on the web for multiple purpose, but mostly for choosing prices on webshops (from... till)

I wouldn't mind picking this up, although I don't have much experience with writing explainers. I wouldn't mind giving it a go.

Not sure if there already is an issue on the HTML working group (I've searched, but haven't found it). But I'm pretty sure I'm not the first one with this idea.

Is this something we can pick up in this group?

From the way I see it, there are two ways to do this:
- increase capabilities of the range slider (in my opinion preferred)
- create something new

I see a lot of benefits in this, this could create an accessible slider, but also potentially give the ability to show the text by using pseudo element and display value attributes in the content property. Making it a JS-free component (that of course be paired with some events and instances )

Just checking for some interest on this

**Comment by bkardell** [comment]
Yes, ana tudor has been looking into some things here.  This works for now she says -  https://css-tricks.com/multi-thumb-sliders-particular-two-thumb-case/ ... but she's trying to sort out a good proposal/thoughts here and I'll work to get that over here.

**Comment by brechtDR** [comment]
@bkardell awesome, thank you for the info. As I stated before. I wouldn't mind helping out with this although not having much experience with writing explainers.

**Comment by gregwhitworth** [comment]
@brechtDR let's try to not over-complicate it, let's start off simple in a collaboration doc and then we can move over to markdown. Happy to tag-team with you and @thebabydino on this as this is a common ask and I also think that there are short-term gains that can be made in addition to the _complete_ solution.

**Comment by gregwhitworth** [comment]
Duping this to #297

**Comment by account-long-lost** [comment]
I found the definitive answer https://pie-chart-all-white.github.io/OlgBw3bkoxWrik1VdGVnGqjE7hi0DTOpApM3bfISDbzqRwzQEg5Fv/
