### ISSUE TITLE
Enable Astro "View Transitions" in the Open UI site

### ISSUE THREAD

**Issue by andrico1234** [openui/open-ui#797]
https://docs.astro.build/en/guides/view-transitions/

Astro have recently released experimental support for view transitions. 

In the context of the Open UI site, enabling View Transitions would allow users to navigate across the site without a full page reload, which they call SPA mode (though I don't yet know exactly what the consequences of this kind of site navigation would have on the Open UI site as a whole).

The framework offers a few simple transitions out of the box, fallback for browser that don't support the View Transitions API, and a `prefers-reduced-motion` mode that prevents all animation if the setting is enabled.

What do you all think? I can get a push a small demo to the preview server and see how it fares against the current routing

**Comment by gregwhitworth** [comment]
I'm not opposed to this but this needs someone to tackle it and until that point I'll close this.
