### ISSUE TITLE
Do research on scrollbars

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#8]
There is a common request for more control over scrollbars. There is a specification for improving control here but not nearly to the extent that web developers desire: https://drafts.csswg.org/css-scrollbars-1/

This one is a bit different from the other components here as most design systems don't consider this a component in itself. Commonly JS libs are used to solve this issue, worth looking into those.

**Comment by Malvoz** [comment]
Also https://drafts.csswg.org/css-overflow-4/#scollbar-gutter-property

**Comment by metaa** [comment]
Scrollbars are also one of the things that still need vendor-specific selectors if desired to be customized.
It would be great if we could unify those one day.

**Comment by gregwhitworth** [comment]
There hasn't been movement on this in a while so I'm going to close this but put it on the backlog.

**Comment by lukaszpolowczyk** [comment]
I would like a Custom Scrollbar.

So that the Scrollbar could use for example decorators like in VSCode, adjust a different action for e.g. onmousedown button===1 on individual elements of the scrollbar, add additional elements inside the scrollbar using the shadow house.
Such Custom Scrollbar would be automatically added to all or specifically selected by the developer.

**Comment by lukewarlow** [comment]
Based on https://drafts.csswg.org/css-scrollbars/#out-of-scope I'm unsure there's much value in looking into scrollbar customisation as part of Open UI efforts. scrollbar-color and scrollbar-width *should* provide enough for most design systems to be satisfied with. There's also been some movement to actually implement them in WebKit and Chrome (admittedly that movement is from me), so these should actually be interopably usable soon.

**Comment by bkardell** [comment]
Closing this based on a rough agreement of what @lukewarlow said above.
