### ISSUE TITLE
[selectlist] Add `showPicker()` method to `<selectlist>`

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#807]
All input elements with some concept of a picker have a showPicker function that opens that UI. Adding this to `<select>` was marked as future work in https://github.com/whatwg/html/pull/7319. However, a subsequent request for this behaviour was raised in https://github.com/whatwg/html/issues/7957.

It would seem like a relatively simple addition to `<selectlist>` and I imagine there's more use cases for it like the above issue.

It's worth noting that while `showPicker()` doesn't exist for `<select>`s it does work for inputs with a datalist attached (inside of Chrome other browser may vary).

**Comment by josepharhar** [comment]
I am tentatively supportive. I was just writing some reftests and I had to do interesting things to get the listbox open, and I was dissapointed to find that something like this didn't already exist

**Comment by mfreed7** [comment]
Adding Agenda+ per the request at today's OpenUI meeting.

I'm supportive of adding `showPicker()` to `HTMLSelectListElement`.
