### ISSUE TITLE
[popover] Can we add hover-triggering to anchor (`<a>`) elements?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#815]
A common use case for "tooltips" is to show a preview of some content when an anchor tag, e.g. `<a href="example.com">`, is hovered. That gives users more comfort that when they commit to clicking the link, they'll get what they expect.

It'd be nice to be able to use the [declarative hover-triggering feature](https://open-ui.org/components/popover-hint.research.explainer/#hover-triggering) on anchor tags, and not just on buttons.

Is there any reason not to allow `<a popovertarget=foo popovertargetaction=interest>` to work, subject to the same limitations and behaviors imposed on buttons?

**Comment by mfreed7** [comment]
> Long-pressing on mobile browsers would be an issue, since normally long pressing on links opens a context menu, where the user can copy the link, etc.
> 
> But a popover is also supposed to show with the same long-press, so what should happen here? Maybe show the popover first, and once the link is long pressed again, the context menu shows.

Yeah, that's a good question. In my head, it would seem to make sense that if there's a popover trigger on the element, that supersedes the browser-provided context menu, to avoid having both. But that might make people unhappy if the thing they wanted to get to was in the context menu, such as copying the link address. I don't know how to best resolve that. Perhaps your suggestion of the double-long-press is the right answer?

**Comment by YummyBacon5** [comment]
Another solution could be to have a longer long-press which shows the context menu - in case of the popover covering the original link. And the shorter long-press shows the popover, or to have these the other way around.

But if `popovertargetaction=interest` is gonna work on `a`s, then I assume all the other `popovertargetaction`s are not going to work. Which may cause author confusion.

**Comment by brechtDR** [comment]
I think this is an interesting concept. But i'm not sure if overriding the default behavior of a context menu on mobile is a good idea. It's almost an afordance at the moment that long pressing gives you the ability to copy text. Are we then removing some "default" good user experience? 

The longer pressing idea sounds like a solution, but personally I think nobody will have the reflex to press longer than the context menu. 

Also, I'm wondering if it is pending on the duration  of something being pressed (context, then popover): Could this potentially be an accessibility nightmare for people with (for example) muscle contraction issues?

**Comment by josepharhar** [comment]
I like mason's idea mentioned in the call that a long press on mobile on an anchor could show the native user-agents context menu with an additional button to trigger the popover in the page.
If wikipedia were to use this for its anchors, I think that would be best.

**Comment by lukewarlow** [comment]
For the sake of completeness we should support interest triggering on `<area>` elements too. Probably goes without saying but gonna say it anyway.
