### ISSUE TITLE
Joint TPAC / WHATWG / OpenUI session?

### ISSUE THREAD

**Issue by mfreed7** [openui/open-ui#817]
TPAC is coming up, Sept 11-15. There's [a proposal](https://github.com/whatwg/meta/issues/284) to have a joint meeting between OpenUI and the WHATWG breakout there. Are folks interested in that? The current proposal is to have it on [Thursday, September 14, at 2:30am PST](https://www.timeanddate.com/worldclock/fixedtime.html?msg=TPAC+%2F+WHATWG+%2F+OpenUI&iso=20230914T1130&p1=321&ah=1&am=30). That time is obviously not ideal for folks in the US, particularly on the west coast. There might be some latitude to move it later by a little bit.

But I wanted to raise the issue and make sure there's interest.

@gregwhitworth Agenda+ hopefully we can discuss next week.

**Comment by gregwhitworth** [comment]
I think it should occur even if it's in person folks only. Depending on the agenda I may attend for some of it but that week is when Dreamforce is and I have a full day of booth sessions and a keynote on that day so assume I'm not attending.

**Comment by gregwhitworth** [comment]
@mfreed7 in reality I probably won't be able to attend but during the CSSWG there were quite a few comments made of concerns on what we're doing. I'm unsure where we stand given the changes to `selectlist` moving away from web component solutions. I think it would be good to post this to the CSSWG as well and try and pull on some of those issues as you all discuss `selectlist` to avoid moving even further to only be blocked later?
