### ISSUE TITLE
Should all `<button type=selectlist>`s get behavior? What about `<button>`?

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#821]
In the new architecture, we are using `<button type=selectlist>` to open the listbox. What happens if you have multiple of them, like this?
```html
<selectlist>
  <button type=selectlist>button one</button>
  <button type=selectlist>button two</button>
  <listbox>
    <option>one</option>
    <option>two</option>
  </listbox>
</selectlist>
```
In the old architecture, I believe that specifying `behavior=button` on multiple buttons would only make one of them get behavior.
This doesn't have to be a use case that actually makes any sense, but we have to implement it one way or the other. I am implementing the prototype of the new architecture in chromium, and I went with all `type=selectlist` buttons getting the behavior because it was easier to implement.

Another question that came up during my implementation is whether we need `type=selectlist` at all. What if all `<button>` descendants of the `<selectlist>` open the listbox automatically?
The reason I chose to create `type=selectlist` was to make it easy to have multiple buttons in a [split button](https://web.dev/building-a-split-button-component/) selectlist, but you could also create a split button if you add some script which calls preventDefault on one of the button's click events. This does require more script though, but maybe you'd want to add a click event listener to one of the buttons anyway...?

This is related to https://github.com/openui/open-ui/issues/809

**Comment by mfreed7** [comment]
I really like the two ideas presented:
- All `<button>`'s within `<selectlist>` (and outside of `<option>` or `<optgroup>`) get the behavior added: they all open the popover with the listbox.
- If you want to build a split button, you'll need to add code to `preventDefault` for the action button. That can look like:

```html
<selectlist>

  <button onclick=preventdefault()>Run the action</button>
  <button>Pick your action (this triggers the listbox popover)</button>

  <option>one</option>
  <option>two</option>

</selectlist>
```

So yes there's code involved, but it can be inline in the HTML, so perhaps not terrible? The upside of this approach is:
1. No need for `<button type=selectlist>` or `<selectlistbutton>`.
2. Perhaps more interesting use cases with multiple buttons that trigger the listbox.

**Comment by scottaohara** [comment]
for a split button specifically, i guess i'm wondering why someone wouldn't just make the button and the selectlist sibling elements in a container, rather than shove it into the selectlist itself and have to contend with these sorts of things?

**Comment by mfreed7** [comment]
> for a split button specifically, i guess i'm wondering why someone wouldn't just make the button and the selectlist sibling elements in a container, rather than shove it into the selectlist itself and have to contend with these sorts of things?

I think the thing you get by putting it together is that the selected option gets copied into the button text (assuming you put the `<selectedoption>` element in there).

> 
> Couldn't you also do this by having `type=button` on the button? Since `type=button` is supposed to make the button [do nothing](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type-button).

That’s another suggestion - perhaps even better because it’s script-free.

**Comment by scottaohara** [comment]
>I think the thing you get by putting it together is that the selected option gets copied into the button text (assuming you put the `<selectedoption>` element in there).

ah yes. you're right.  shoot.  i was still thinking of this as maintaining the default roles for the component, but that splitbutton setup you mention is more like a button with a companion menubutton that opens a menu > menuitems. for instance: https://react.fluentui.dev/?path=/docs/components-button-splitbutton--default

bleh... the overlap with these components and the differences in setting these up correctly is going to be frustrating for people.

**Comment by kbrilla** [comment]
> > I think the thing you get by putting it together is that the selected option gets copied into the button text (assuming you put the `<selectedoption>` element in there).
> 
> ah yes. you're right. shoot. i was still thinking of this as maintaining the default roles for the component, but that splitbutton setup you mention is more like a button with a companion menubutton that opens a menu > menuitems. for instance: https://react.fluentui.dev/?path=/docs/components-button-splitbutton--default
> 
> bleh... the overlap with these components and the differences in setting these up correctly is going to be frustrating for people.

Actually even more annoying is that difrent designer like those splitbuttons to behave diffrently, once it will be expected that when You click option it will actually excetue action as well as set this item as "default", on other hand one will expect it to only pop into "default" state and then click this default one to perform action, and of corse it can behave that "default" will be always one option and options form popover will be just actions. So is selectlsit actually best suited to be building block for splitbutton?

**Comment by scottaohara** [comment]
one probably "could" use it as a building block - but not without revising the default roles of the elements, and adding extra functionality.  tbh i'm not too concerned about people doing that so long as they don't think they can do this by default without making the necessary changes.  

arguably there could be some 'automagical' ways that the browsers could figure this out... but that might be more trouble than it's worth.

**Comment by josepharhar** [comment]
> > Couldn't you also do this by having type=button on the button? Since type=button is supposed to make the button [do nothing](https://html.spec.whatwg.org/multipage/form-elements.html#attr-button-type-button).
> 
> That’s another suggestion - perhaps even better because it’s script-free.

I like this the most so far. The only downside is that it's less obvious how to make a split button, but I don't think split buttons are the most common use case.

**Comment by mfreed7** [comment]
Here's the split button example, with the new suggestion:

```html
<selectlist>

  <button type=button onclick="do_something_else()">
    <selectedoption></selectedoption>
  </button>
  <button>Pick your action (this triggers the listbox popover)</button>

  <option>one</option>
  <option>two</option>

</selectlist>
```

**Comment by lukewarlow** [comment]
Closing this as I think it's done, I don't believe any edits needs to be made.

**Comment by josepharhar** [comment]
If I am reading correctly, this was overturned here: https://github.com/openui/open-ui/issues/939#issuecomment-1910837275
