### ISSUE TITLE
[Selectlist] Allow `<label>` as the first child of `<optgroup>`, as an alternative to the `label` attribute

### ISSUE THREAD

**Issue by YummyBacon5** [openui/open-ui#822]
# Issue

The only way to display a label with an `optgroup` element is with the `label` attribute.

But this would not allow for very much customisability. Since no other HTML elements would be shown, if induced with the attribute.

Also that there is currently [no way to style an `optgroup`'s label](https://open-ui.org/components/selectlist/#styling-parts-of-the-control).

Both of these issues would cause authors to create their own custom groups, which is what `selectlist` is supposed to fix.

# Possible Solution

Add a `::group-label` pseudo-element selector that targets the group's label.

Allow a `label` element to be the first child of an `optgroup` element. This would allow for authors to include their own elements.

Use cases for the latter:
Would allow authors to include more semantic meaning in a group's name. For example, an `abbr` element.
Would allow for better styling. For example, `span` elements to style individual words.

**Comment by scottaohara** [comment]
it was previously resolved that `legend` would be used to label optgroups https://github.com/openui/open-ui/issues/558

**Comment by YummyBacon5** [comment]
Thanks! Although, I think that this should be mentioned in the explainer somewhere. And that [for this example](https://open-ui.org/components/selectlist/#extending-the-markup) to be updated to be more accessible by using the `optgroup` element.

**Comment by scottaohara** [comment]
agreed, that appears to be a miss in the explainer to not be calling this out.
