### ISSUE TITLE
select: Should `<selectedoption>` respond to mutations in the selected `<option>`

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#825]
Consider the following:
```html
<selectlist>
  <button>
    <selectedoption></selectedoption>
  </button>
  <option>foo</option>
</selectlist>
<script>
requestAnimationFrame(() => {
  document.querySelector('option').textContent = 'bar';
});
</script>
```

Should the `<selectedoption>`'s contents set to "bar", or should it stay as "foo"?
The equivalent use case for `<select>` will change the button's text to "bar".

@argyleink @mfreed7

We should probably wait for https://github.com/openui/open-ui/issues/571 to be resolved before getting this 100% figured out.

**Comment by argyleink** [comment]
i vote for the value to update to bar

**Comment by lukewarlow** [comment]
It should display whatever the form submitted value would be imo. So if that code would update the value (I think it would) then it should also update the displayed html

**Comment by josepharhar** [comment]
Yeah we should probably listen to mutations, it really seems like the sane default. It will likely be expensive for the browser to do that, but there are ways that we can improve the performance: https://chromium-review.googlesource.com/c/chromium/src/+/5370555/2/third_party/blink/renderer/core/html/forms/html_selected_option_element.h

**Comment by josepharhar** [comment]
I propose that we resolve to make the selectedoption element respond to mutations inside option elements. Otherwise, we might not pick up updates that authors have made to the DOM and it will leave the selectedoption element in a broken state.

**Comment by josepharhar** [comment]
reopening due to https://github.com/whatwg/html/issues/10520

**Comment by sorvell** [comment]
[All of the options](https://github.com/whatwg/html/issues/10520#issuecomment-2418959922)  for syncronizing changes just seem to open different cans of worms. My concern is we'll get something that behaves in unexpected ways and has poor performance.

I think the root problem is that this behavior is really a new core platform feature. The DOM rendered inside `<selectedoption>` is not intended to be live and developer accessible. It's a projection of the "selected option" rendered in a different location, more like what [element()](https://developer.mozilla.org/en-US/docs/Web/CSS/element) anticipates. 

OK, but clearly that wouldn't be enough because it needs to be independently styleable. 

Now, jumping from that problem to cloning and synchronizing modifications is where I think things perhaps went wrong. And sorry in advance if this was previously considered and discussed.

Instead, it seems like we need a new concept of a projection (conceptually like `element()` but obviously not just a live image of the source) that is separately styleable. Something like:

```css
selectedoption::content(/* can target projected DOM of the selected <option> */)
```

**Comment by sorvell** [comment]
Was the following alternative considered?

If the content of the `<selectedoption>` really should be able to be different from the "selected" <option> then perhaps it should just not be synchronized at all other than its selection state.

1. There are 2 new elements, not one: `<selectedoptions>` is a container of `<selectedoption>` elements. 
2. When an item is selected in the select, the matching same value or child index `<selectedoption>` matches `:checked` or a new pseudo-class. 
3. Only if no matching `<selectedoption>` exists, one is cloned and inserted into the `<selectedoptions>` element. This allows users to pre-seed alternate renderings for the "selected option" via HTML or Javascript. Custom element users who want to avoid weird cloning limitations might also take advantage of this (at least until custom cloning steps are added to custom elements).
4. And the default styling is `selectedoptions :not(:checked) { display: none;}`
5. Other than that special 1x cloning no other modifications of the DOM are made. No syncing. No removal of the child `<selectedoption>` elements. The pseudoclass is sufficient for styling and events for JS modification.

```html
<select>
  <button>
    <selectedoptions>
      <selectedoption value="a">custom a</selectedoption>
    </selectedoptions>     
  </button>
  <option value="a">a</option>
  <option value="b">b (this will be cloned when selected)</option>
</select>
```

**Comment by josepharhar** [comment]
I think that for more sophisticated cases where you don't want to clone but instead want to have other content that lives in the option which gets rendered when a particular option is selected, this could be implemented by not using the `<selectedoption>` element at all, and could also be done by frameworks.

We wanted to add this element to support basic cases so that most users of this new select would not have to use javascript to copy the innerHTML on every change event, but since its a separate element that you can choose to put in the button or not, we are providing flexibility to build more sophisticated things in userland.

Based on the discussions so far, and my experimentation of implementing different things and testing out basic cases with React, I am supportive of not observing mutations inside select or option elements and only cloning during initialization (parsing) and when new options become selected (when the change event fires). This is the first option in [jake's article](https://jakearchibald.com/2024/how-should-selectedoption-work/#option-nothing-by-default-but-provide-a-way-to-trigger-an-update).

**Comment by josepharhar** [comment]
Since people sounded more interested in accessibility mappings of the button than the cloning behavior, I created a separate issue here so we can talk about it: https://github.com/openui/open-ui/issues/1116

**Comment by jakearchibald** [comment]
https://github.com/openui/open-ui/issues/1119 follow up on when the cloning should happen in relation to selecting the selected option.
