### ISSUE TITLE
selectlist: pseudo-class to style the selected option

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#827]
The selected option in the listbox should be easy to style independently from the other options.
A pseudo-class like `option:selected` would make sense for this, right?
Is there already another way to do this that I'm missing?

**Comment by lukewarlow** [comment]
Might be opening a can of worms here but could the selected attribute get updated in real time and then can do `option[selected]`?

**Comment by lukewarlow** [comment]
Did some playing around and for `<select multiple>` it's `option:checked`

And you can apply some styling to it however `select:-internal-list-box:focus` (exact name might be slightly different) has some errors that mean that you can't properly style the background or foreground colour.

**Comment by scottaohara** [comment]
The :checked pseudo class can be used now with select and selectlist 

but a :selected pseudo class would make far more sense, imo, but retaining support for :checked could be useful…

**Comment by lukewarlow** [comment]
Yeah I think I agree that it'd be nice to add a `:selected` pseudo and alias `:checked` to it for options. I wonder if that'd get push back as being superfluous though?

**Comment by scottaohara** [comment]
dunno.  but guess that comes down to what the end goal for multi-select ends up being.

e.g., someone _could_ end up needing to convey both a 'checked' and a 'selected' state - which is why in ARIA options support both.  It's not a common thing, and tbh due to it not being common, it is handled inconsistently / not something that is at the top of people's todo lists to sort out.  but, hey... priorities n' such.

**Comment by josepharhar** [comment]
Oh cool, I didn't know that `option:checked` worked. Yeah I agree we should at least make `:checked` work if it doesn't already, and then also add `option:selected` if people are cool with it - and if some people say we can only have one, then `option:selected` it is.

**Comment by lukewarlow** [comment]
Just to clarify are you wanting something for the selected option in the listbox? Or when it's displayed inside the button?

Because I think we need both separately

**Comment by josepharhar** [comment]
I filed another issue to talk about rendering checkmarks next to options: https://github.com/openui/open-ui/issues/863
