### ISSUE TITLE
Specifics of disallowing interactive content under <select>

### ISSUE THREAD

**Issue by dandclark** [openui/open-ui#83]
https://open-ui.org/components/select#structure bans a set of interactive elements from existing under `<select>`.  We should define more precisely how this is enforced and what it looks like when this rule is broken.  Parser rules can prevent these elements from being placed under `<select>` at parse time, but they can still be injected there dynamically.  So we have to handle this case.

There are a number of things we could do here:
1. Refuse to slot the banned content into the `<select>`'s shadow DOM.  It's not clear how this would be specified, especially given that banned elements could be present in the subtree of a slotted node even if the root of the slotted content was not a banned element.
1. Refuse to render the control if a banned element has been slotted anywhere into the control.
1. Refuse to render any banned content slotted into the control (treat it as `display:none`?), but allow everything else to work.
1. Show the banned elements but don't allow clicks/user interaction.
1. Other approaches?

Thanks to @mfreed7 for originally raising this question.

**Comment by gregwhitworth** [comment]
@chrisdholt @EisenbergEffect  and @levithomason - I believe you both stated that you don't allow interactive elements within your `<select>` elements. What do you all do with interactive content that is passed to the element anyways?

**Comment by dandclark** [comment]
> @dandclark what do you mean by this (eg: what does everything else to work mean? Do you mean I can reach the DOM element from JS?):
> 
> > Refuse to render any banned content slotted into the control (treat it as display:none?), but allow everything else to work.

For option (3) I mean that an `<iframe>`, `<input>` etc would be slotted into the `<select>`'s shadow and be reachable through the DOM in the normal ways, but always forced to be `display:none`.  The other content would not be affected (except by having the `dispay:none` element in the tree order).  It feels like some `display:none` interactive elements could still cause problems somehow but I don't have an example at hand.

**Comment by gregwhitworth** [comment]
@dandclark ok, that's what I figured and it does worry me. I think allowing them in the DOM but not rendering them is actually kind of confusing from an author perspective, so it makes sense to me to not allow them at the parser level. Based on the prior resolution #74 I think it safe to define it as such. That said, I'll make sure to add it to the agenda that we'll be changing the normative text to be more explicit in that they should not be added to the DOM.

**Comment by EisenbergEffect** [comment]
I'll let @chrisdholt speak to that for fast-dna. I'm not sure what has been done there historically on our team. Prior to my work at Microsoft, I would let the end user compose anything "passing the buck" to them for correctly handling any composed input elements.

**Comment by mfreed7** [comment]
> > @dandclark what do you mean by this (eg: what does everything else to work mean? Do you mean I can reach the DOM element from JS?):
> > > Refuse to render any banned content slotted into the control (treat it as display:none?), but allow everything else to work.
> 
> For option (3) I mean that an `<iframe>`, `<input>` etc would be slotted into the `<select>`'s shadow and be reachable through the DOM in the normal ways, but always forced to be `display:none`. The other content would not be affected (except by having the `dispay:none` element in the tree order). It feels like some `display:none` interactive elements could still cause problems somehow but I don't have an example at hand.

Thanks for raising this issue. I think either option 2 or 3 might be the best. As you pointed out, just disallowing this in the parser isn’t enough, since you can modify the DOM imperatively and we need to guard against that also. It seems like the display:none solution would likely be the most straightforward, but I agree that it feels like there might be a few corner cases left to outlaw here. I also don’t have any specific examples.

Not rendering the disallowed elements is a bit confusing, but it is also pretty close to what happens today when almost anything is nested inside a `<select>`. So I’m not sure it would be so confusing in practice.

**Comment by gregwhitworth** [comment]
> Not rendering the disallowed elements is a bit confusing, but it is also pretty close to what happens today when almost anything is nested inside a <select>. So I’m not sure it would be so confusing in practice.

Valid point.

**Comment by gregwhitworth** [comment]
valid point

> Not rendering the disallowed elements is a bit confusing, but it is also pretty close to what happens today when almost anything is nested inside a <select>. So I’m not sure it would be so confusing in practice.

**Comment by bathos** [comment]
> So I’m not sure it would be so confusing in practice.

Agreed. I’d go further and say that to do anything else would be more confusing; is there any reason why this one element ought to behave differently from (dozens?) of other elements which ignore imperatively assigned children they don’t expect?

( `<script>`, `<img>`, `<input>`, `<title>`, `<textarea>`, `<br>`, `<meta>`, `<iframe>`, `<style>`, `<base>`, `<video>`, ...)

**Comment by gregwhitworth** [comment]
>  is there any reason why this one element ought to behave differently from (dozens?) of other elements which ignore imperatively assigned children they don’t expect?

Nope, which is what was denoted above. Seems as though we have general agreement that number 3 is the best approach. Is there a reason we would prefer number 2 @dandclark @mfreed7

**Comment by dandclark** [comment]
> Is there a reason we would prefer number 2 @dandclark @mfreed7
None that I can think of given @bathos 's point that it would be inconsistent with how other elements already behave.  So I also prefer option 3.

**Comment by mfreed7** [comment]
> > is there any reason why this one element ought to behave differently from (dozens?) of other elements which ignore imperatively assigned children they don’t expect?
> 
> Nope, which is what was denoted above. Seems as though we have general agreement that number 3 is the best approach. Is there a reason we would prefer number 2 @dandclark @mfreed7

Number 3 sounds the most a) straightforward to implement, and b) straightforward to understand from the developer point of view. So I agree.

**Comment by gregwhitworth** [comment]
This was discussed on the last [telecon](https://www.w3.org/2020/05/22-openui-minutes.html#item02) and the resolution was:

>RESOLUTION: Keeping with precedent and allow script to add DOM elements that are not supported for Render. Recommend tooling to inform the developers that invalid elements were added

**Comment by andrico1234** [comment]
Closing this as this issue was resolved in a telecon
