### ISSUE TITLE
Improve client-side form validation with messages in the dom

### ISSUE THREAD

**Issue by jimmyfrasche** [openui/open-ui#846]
The client-side form validation API is nice up until a point but after that it's not enough. The largest flaw is that it displays errors as unstylable popups. Many form libraries/designs [citation needed] prefer to display validation errors adjacent to the input, either out of simplicity or so that the user may refer to the message without having to figure out how to get a popup to trigger again. I think this can and should be standardized with many benefits for developers and users.

Sketch:

```html
<input id=inputOrFormID required minlength=5 maxlength=15>
<p>
  Errors:
  <errors for=inputOrFormID>
    <error when=valueMissing>this is required</error>
    <error when="tooLong, tooShort">must be between 5 and 15 characters</error>
  </errors>
  plz fix
</p>
<style>
  p:has(> errors:not(:open)) { display: none }
</style>
```

The `errors` tag is hidden unless one or more of its child `error` tags match and all `error` tags are hidden unless they match.

When not hidden, it displays like an unordered list by default with each `error` as a list item and makes any appropriate `aria-*` connections. As the tag transitions to `:open` the UA may take the same action as if a polite live region was set to the `innerText` of the `error`, possibly throttling or waiting for a delay after the last input event.

No errors match unless the form/input is `:user-invalid`. Otherwise matching uses the `when` attribute to test the `ValidityState` of the connected form/input. An empty/missing `when` is shown if there is any error. The `when="tooLong, tooShort"` above means if either of those conditions hold. If there is an error state that matches no `error` tags it should show using the default popup to minimize user confusion and to let the developer know of the unhandled case; likewise, no popup is shown if it results in an `error` becoming `:open`.

If the `error` has a `force` attribute it is forced to match (even if the form/input is `:valid`) until the user interacts with the control, after which it behaves as normal, allowing server side error messages to be displayed by the same mechanism. A special `when=none` can be used for server side messages that needn't be shown again. A forced error is not reflected in `ValidityState` and does not prevent submission.

This would work well for all the standard errors but not well for custom errors. `setCustomValidity()` takes a single string and it's possible to have multiple errors; for example, a new password field may be in both the "must contain uppercase letters" and a "must contain numbers" states simultaneously. There should be an API to set multiple custom error validity states independently and a syntax to match them in individual `when` attributes. I am unsure what that would entail specifically but it would be an orthogonal and welcome change.

With all of that, it would be simpler to handle form validation errors and no JS would be needed except for custom validation.

An annoyance with writing a polyfill would be the lack of an event on any `ValidityState` change (there is only valid → invalid ). It would be necessary to listen to the form controls for any change then poll `ValidityState`. A generic any change event would be orthogonal and of use for this kind of thing even if the specifics above never happen.

**Comment by jimmyfrasche** [comment]
I'm also happy to file separate issues for the related enhancements to the javascript end of the validation api later but I'm not 100% sure which repo is the correct one for that. Is it [whatwg/html](https://github.com/whatwg/html)?

**Comment by gregwhitworth** [comment]
Hey @jimmyfrasche thanks for raising this, if it's alright I'm going to close this as a dupe to #802 . Additionally, I've started authoring an explainer/research in this [google doc](https://docs.google.com/document/d/1Uzk3dj7T0QpmhF1jKz9Cjy0gW1LMXut_2DlNNqzPGJw/edit?usp=sharing). Feel free to ping me on our discord channel if you'd like to be added as an editor with @hidde and I to help out.
