### ISSUE TITLE
Custom decorations in standard components

### ISSUE THREAD

**Issue by vollowx** [openui/open-ui#856]
If I made a component `std-button`, that can be used like this:

```html
<std-button md>
  <std-icon slot="icon">settings</std-icon>
  Material 3
<td-button>
<std-button fl>
  <std-icon slot="trailingicon">settings</std-icon>
  Fluent UI
<td-button>
```

```css
std-button[md] { /* Custom button styles in Material 3 */ }
std-button[fl] { /* Custom button styles in Fluent UI */ }
```

it's easy to switch styles and reduce duplicate codes.

But also, Material Design put ripples and focus ring inside buttons, checkboxes and other action elements, which need JS to implement, I wonder how can I inject the `<md-ripple>` or `<md-focus-ring>` inside the buttons or implement that in some other ways.

**Comment by gregwhitworth** [comment]
Hey @vollowx, I think [web components community group](https://github.com/w3c/webcomponents-cg) is a better place to bring this discussion to. I recommend joining their [discord](http://discord.gg/YmrNQ4rYJz) as they're much more engaged there as well.
