### ISSUE TITLE
[Popover] Tooltips on `<abbr>`s

### ISSUE THREAD

**Issue by YummyBacon5** [openui/open-ui#857]
Currently in HTML, the `title` attribute [has special semantics](https://html.spec.whatwg.org/multipage/text-level-semantics.html#attr-abbr-title) on the `<abbr>` element to provide an expanded abbreviation.

But the `title` attribute isn't accessible to mobile and keyboard users.

Since `popovertargetaction=interest` is meant to be an accessible tooltip, maybe it could be used here instead.

But popovers aren't allowed on non-interactive content. `<abbr>` is non-interactive. So should this be allowed?

**Comment by lukewarlow** [comment]
The link you've provided links back to this issue just as an fyi.

**Comment by lukewarlow** [comment]
Going to close this and continue discussing in https://github.com/openui/open-ui/issues/839
