### ISSUE TITLE
`focusgroup` should support logical properties

### ISSUE THREAD

**Issue by ramiy** [openui/open-ui#859]
Currently, the [focusgroup explainer](https://github.com/openui/open-ui/blob/main/site/src/pages/components/focusgroup.explainer.mdx) is using physical rather than logical properties, it should be fixed according to [CSS Logical Properties and Values](https://drafts.csswg.org/css-logical/) spec.

The `focus-group-direction` property accepts the following values:
* `horizontal`
* `vertical`
* `both`

It should also accept:
* `inline`
* `block`

Similarly, the CSS `resize` property has [the same values](https://drafts.csswg.org/css-ui/#resize), for physical direction flow it supports `horizontal` & `vertical` values, and for logical flow it supports `inline` and `block`.

**Comment by lukewarlow** [comment]
@ramiy could you sanity check https://github.com/openui/open-ui/pull/870 especially that the explanations make sense?

**Comment by travisleithead** [comment]
I might further add clarification around the physical vs logical navigation for those unfamiliar with it like I was. But that can be done in a separate pass.
