### ISSUE TITLE
Invokers: What should happen to popovertarget?

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#869]
In https://open-ui.org/components/invokers.explainer/#what-does-this-mean-for-popovertarget we say the new attribute doesn't neccesarily mean the popover ones will go away.

I think it'd be good to get a concrete proposal on what happens to them (effectively I want whatever we write to not need "necessarily" in it).

I propose we deprecate `popovertarget` and `popovertargetaction` as they're completely superfluous once we have `invoketarget` and `invokeaction`, with the eventual goal of their removal in future.

**Comment by keithamus** [comment]
I think we can realistically consider deprecating `popovertarget` as Firefox has yet to ship. If they do ship, it becomes a bit more difficult. The explainer says that `invoketarget` overrides `popovertarget` so steering people from `popovertarget` to `invoketarget` will lower usage.


If we are to deprecate, I think putting some effort into documenting the migration path (mdn?), correctly advocating to users why/what/how and possibly writing polyfills maintain the old behaviour during migration should be table stakes for this work though.

/cc @nt1m as we discussed this at TPAC.

**Comment by lukewarlow** [comment]
If Firefox could ship popover with invoketarget out the bat that'd be amazing, but as you say we'd need some effort to get people to migrate the code. 

Even just something like a warning in dev tools if you have popovertarget without a corresponding invoketarget would be a good start. At some point the usage of popover will probably drop to an acceptable level to remove but possibly not?

I think it's definitely worth discussing at least.

**Comment by keithamus** [comment]
> A migration polyfill probably wouldn't even be necessary on the basis they'd be polyfilling invoketarget anyway?

 While the migration path is quite straightforward for larger orgs (like GitHub) who have hundreds of references it'll take some time to migrate. We'd want a period of time where both are supported in some manner (be it via a singular polyfill, multiple polyfills, or by browsers supporting both for some time). Right now we polyfill popovertarget because Firefox doesn't support it, if Firefox shipped popover w/o popovertarget work would be need to done on https://github.com/oddbird/popover-polyfill which assumes `popovertarget` comes for free with `popover`. So there'd need to be not-insignificant coordination from all parties.

**Comment by lukewarlow** [comment]
Yeah that makes sense. So I guess once the new one is shipped immediately add the warning that it's deprecated. And then while "deprecated" keep it implemented for a bit. And revisit in 6months to a year to check use counters?

The use counter that would be specifically important is the popovertarget without an invoketarget or with one that has a different idref.

>I think browsers should probably add a console.warn when using both invoketarget/popovertarget because invoketarget will silently prevent popovertarget from working, which could lead to confusion.
So if we were to also warn when using popovertarget without invoketarget we're effectively making it warn whenever popovertarget would be used - which is fine but we should make that the conscious choice.

Ah yeah to clarify I think warn based on the above described use counter behaviour. So mismatched idref or missing invoketarget.

**Comment by nt1m** [comment]
cc @emilio @smaug--- Is this something Gecko could consider doing? Shipping invoketarget without popovertarget?

This is something WebKit can consider us shipping as well if Gecko can ship without popovertarget support.

**Comment by emilio** [comment]
I think that'd be nice, having to forever support `popovertarget` would be rather unfortunate.

cc @smaug---- (missing one dash above :))

**Comment by smaug----** [comment]
I don't think we could ship popover without popovertarget if other browsers still supported it.
It would be really nice to get rid of popovertarget though. I assume its usage must be very low still. Does anyone have telemetry data about that?

**Comment by mfreed7** [comment]
I'm supportive of deprecating `popovertarget` but *only* once `invoketarget` is a standardized thing with multiple implementations. I really don't like the "remove the old thing while we're still working on the new thing" approach - it's hard for developers.

**Comment by lukewarlow** [comment]
I've updated OpenUI to explain the intention is to eventually deprecate `popovertarget`. Made it clear that they will co-exist for a bit.

The exact specifics of the process of achieving this I'll leave to the WhatWG PRs and issues.
