### ISSUE TITLE
[focusgroup] Functionality defered to (abandoned?) CSS Toggles Proposal

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#893]
Currently the focusgroup proposal defers some functionality to the [CSS Toggles Proposal](https://tabatkins.github.io/css-toggle/)

However, based on the final comment on the [Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1250716&q=CSS%20Toggles%20Proposal&can=2) and the [linked document](https://docs.google.com/document/d/10JxXgeDAJ5zerOdxoWM9ZU9d5iMOdzGJt0EhlhkOkxM/edit#heading=h.dgwo5ekohooq) it would seem that the CSS Toggles concept has been abandoned.

It would be good to at least acknowledge this in the focusgroup explainer, even if it's not replaced with a new proposal yet.

cc @dbaron as he's the one who owned this in Chrome, so can confirm this is still the status quo?

**Comment by lukewarlow** [comment]
cc @keithamus ;)

**Comment by travisleithead** [comment]
After reading through [Invokers](https://open-ui.org/components/invokers.explainer/) and [Interest Invokers](https://open-ui.org/components/interest-invokers.explainer/), it made me think of having a very simple attribute that just translates "interest" (e.g., via focus) into a "toggle" or "click" on the same element, and would only be a viable attribute on elements that already have invocation state/patterns (like `<input type=checkbox>` -- others?)

Something like `invokeoninterest` (boolean). The default for when the element with this attribute **shows interest** is to invoke it/toggle it on, and when it loses interest then it can be toggled off. Such a simple attribute could enable selection-follows focus for native elements that already have "selection" state. Adding that selection state onto other random elements--that might be out of scope ;)

**Comment by travisleithead** [comment]
Current plan:
* Update the explainer such that CSS Toggles is not a proposed solution to the selection part of a focus+selection composed control.

**Comment by travisleithead** [comment]
PR #1021 has updated the CSS Toggles references. Closing this now.
