### ISSUE TITLE
Define file input anatomy

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#91]
There was a request for this to the CSSWG here: https://github.com/w3c/csswg-drafts/issues/5049

They are currently focused on the psuedo element for button but it would be good to have a full anatomy breakdown on a proposal page backed by our research.

**Comment by gregwhitworth** [comment]
In the PR I added the following:

Looking through the different parts across the different component libraries:

- File Picker
- File Selector

I think both of these are better than chooser but I do think all of them should be appended with button. @Roy-Orbison then made the valid point regarding other standards referencing this control:

> The majority of standards documents for HTML and JavaScript refer to such controls as file upload, and the action performed as selection, and have done so for many years. What benefit is there to CSS authors in deviating from those conventions?

Because of this I'd like to recommend that we use `file-selector-button`. Thoughts?

**Comment by gregwhitworth** [comment]
We discussed this in today's telecon, the minutes are here.
Here is the resolution:

> RESOLUTION: Use the name file-selector-button for the file input button part

@mfreed7 had a good point that we should ensure that this naming aligns with the anatomy we're actively investigating for `<select>`.

**Comment by andrico1234** [comment]
Closing this as the [File proposal](https://open-ui.org/components/file) has been added to the Open UI site
