### ISSUE TITLE
[invokers] Should input and select auto action exist?

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#911]
Currently the defaults for invokers on input and select are showPicker which is also the auto value.

![image](https://github.com/openui/open-ui/assets/32498324/bffd70e0-a5bd-4b56-a70d-17099ddc389f)

~~While I was implementing this @josepharhar mentioned it might be better for this to be a toggle by default?~~

~~Having auto as a togglePicker would better match others autos too so I tend to agree with Joey.~~

~~I propose a new togglePicker and hidePicker action to go with showPicker and auto would map to togglePicker instead of showPicker.~~

After some thought and discussion I propose removing auto for now.

**Comment by lukewarlow** [comment]
The one problem with this is there isn't currently a togglePicker and closePicker JS function so a polyfill might be slightly more difficult (generally speaking I think blur or another JS function can be used to achieve the desired effect though)

**Comment by lukewarlow** [comment]
cc @keithamus

**Comment by keithamus** [comment]
I agree `togglePicker` makes sense.

I think if we're adding behaviours via `invokeaction` is stands to reason that there should be an equivalent method on the IDL. See also `<dialog>`.`toggleModal()`.

**Comment by lukewarlow** [comment]
I was going to ask about that. Is that what's happening with the dialog toggleModal function then?

For now I'll do a PR to update the explainer and update the Chrome PR to include it but can do follow ups to expose the IDL

**Comment by keithamus** [comment]
I haven't proposed it yet, but it is where I first recognized the issue that things aren't cleanly mapping to method calls.

**Comment by lukewarlow** [comment]
Hmm actually the more I think about this the less sure I am this makes sense.

The only popover=manual type picker is the color input in Firefox. Everything else closes on clickoutside OR is a modal dialog (file picker).

So does having a toggle and hide action actually make sense.

@keithamus what do you think about for now just removing the auto action? Then if we decide we want these in future (before shipping) we can add them easy enough?

Implementing the toggle is slightly difficult because the mousedown on the button leads to the picker closing which then reopens on mouseup from the invoke.

**Comment by keithamus** [comment]
Yeah I think it makes sense to just have `showPicker` for inputs in that case. Toggles seem to make sense when there's a button inside the control that is opening, but as far as I know there's no ability to add buttons inside a picker, right?

**Comment by lukewarlow** [comment]
Yeah at the moment there's no access to the pickers. And if there is I'm future we can revisit this. Firefox might want a toggle for their colour picker too.
