### ISSUE TITLE
Combobox Proposal

### ISSUE THREAD

**Issue by sudheer-gowrigari** [openui/open-ui#924]
I have been working on an early draft for a ``combobox`` explainer and I would like to incubate it in Open UI to hopefully land a cohesive solution in the representative standards bodies following approval from Open UI.
The primary motivations and details of this proposal can be found in the explainer I've prepared: [Combobox Explainer](https://github.com/sudheer-gowrigari/explainers/blob/main/combobox.md).

**Comment by lukewarlow** [comment]
I don't think input type=selectlist is necessarily the right call (selectedoption slot wouldn't work because input can't have children?) but bringing this to openUI and getting the ball rolling is great!

**Comment by gregwhitworth** [comment]
@lukewarlow you actually raised a discussion Sudheer and myself had internally and one of the reasons we decided to just open the issue and request to move it here formally for incubation. It's very early, we know our proposal will be debated up and down in each section and as such we should get concrete resolutions against each of them.

**Comment by lukewarlow** [comment]
Yup exactly get it moved here and then we can work through it bit by bit

**Comment by YummyBacon5** [comment]
Would dynamic data work here?

For example, the actual search is preformed on a database, and the response is inserted into the DOM as `<option>`s.
---
This is also similar to #847

**Comment by sudheer-gowrigari** [comment]
> Would dynamic data work here?
> 
> For example, the actual search is preformed on a database, and the response is inserted into the DOM as `<option>`s.
> 
> This is also similar to #847

Yes, that's definitely one of the options available in [design systems](https://github.com/sudheer-gowrigari/explainers/blob/main/combobox-research.md#loading) and as this is just a starter explainer, we need a detailed proposal discussions as part of [search attribute](https://github.com/sudheer-gowrigari/explainers/blob/main/combobox.md#introduction-of-the-search-attribute)

**Comment by tay1orjones** [comment]
Hey, I'm thrilled to see this open. I can contribute research from the Carbon Design System, just let me know the way/best place to funnel that into.
