### ISSUE TITLE
[Selectlist] `<label>`s as children of `<selectlist>`

### ISSUE THREAD

**Issue by YummyBacon5** [openui/open-ui#926]
With [this](https://open-ui.org/components/selectlist/#slotting-your-own-content) and [this example](https://open-ui.org/components/selectlist/#extending-the-markup), in the explainer, they both have an authoring error. That text inside the `span class="label"` should clearly be a `label` element instead.

Which makes me think:
Should `<label>`s without a `for` attribute as a child of `selectlist` act as a label for the button?

Or maybe to fix authoring errors like this, that the text content of `<selectlist>` could be used as an accessible name by default, even without it being a `<label>` element. - it also seems like this behaviour was assumed in these two examples

**Comment by lukewarlow** [comment]
This brings up a similar sort of issue to #894 these aren't actually labels* afaik so I think that using spans is correct and if we can think of a better name we can fix the class names to be less ambiguous. 

*Not in the "accessible name" sense which is what `<label>` is for. These are more just helper text. Like the Choose a file... In a file input.

cc @scottaohara to check I've got that right?

**Comment by YummyBacon5** [comment]
> *Not in the "accessible name" sense

At least in the [first example](https://open-ui.org/components/selectlist/#extending-the-markup), it seems like it should be used as an accessible name. Since the button does not have any content at all. Meaning that otherwise it would not have one

**Comment by lukewarlow** [comment]
Yup you're right I misread that one initially. The example definitely should be fixed, how best to do that idk. Definitely worth discussing.

**Comment by josepharhar** [comment]
In the examples I can currently see in the explainer, all of the class=label text is inside buttons:
```html
  <button type=select>
    <span class="label">Choose a plant</span>
    <selectedoption></selectedoption>
  </button>
```
```html
  <button type=select>
    <span class="open">Open</span>
    <span class="label">Choose an option</span>
  </button>
```
Rather than adding new machinery for label elements, I think it would be better to either say that these examples are OK or provide some guidance that you should have this text in a label element which is outside the `<select>`.
