### ISSUE TITLE
[invokers] should `toggleModal`/`toggle` close open dialogs regardless of modal?

### ISSUE THREAD

**Issue by keithamus** [openui/open-ui#935]
The invokers proposal adds `toggle` and `toggleModal` actions, which aim to toggle the dialogs openness:

 - `toggleModal` should open the dialog as modal when closed.
 - `toggle` should open the dialog as _non modal_ when closed.

There's some questioning what it should do when it's open. The options are:

 1. `toggleModal` closes a dialog if it is open as modal, if it is open _non modal_ then it is a noop. Likewise, `toggle` closes an open _non modal_ dialog, and on a _modal_ is a noop.
 2. Both `toggleModal` and `toggle` will close a dialog regardless of whether it is _modal_ or not.

### Advantages of 1

It is clearer the intent for `toggleModal` and `toggle`; one always does the modal operation, and one always does the non-modal operation.

### Advantages of 2

As the default action for an invokertarget pointing to a `<dialog>` is `toggleModal`, it would mean that just having an invoker button with no action inside of a `<dialog>` is always going to do the right thing.

/cc @lukewarlow @mfreed7 @scottaohara

**Comment by lukewarlow** [comment]
https://github.com/openui/open-ui/issues/920 depending on this issue we might be able to simplify things

**Comment by scottaohara** [comment]
the toggling of a modal is odd to me.  is it just a sort of short hand so someone doesnt have to explictly call a show or a hide on the control that will be opening or closing?  since, one can't toggle a modal from the same control, after all.

**Comment by lukewarlow** [comment]
Technically if you force the dialog contents to always be visible even when closed you could...

But that's a good point. I guess the toggleModal is more for the auto default than for an explicit action? Just so it does the right thing even without defining an action?

**Comment by keithamus** [comment]
`toggleModal` is the explicit name for the `auto` action. IMO the auto actions should have explicit names (other than `auto`).

**Comment by scottaohara** [comment]
>Technically if you force the dialog contents to always be visible even when closed you could...

well, sure.  but then also that shouldn't be a modal. that'd be a non-modal dialog.... and if it were modal, then the rest of the page wouldn't work and that'd be quite the problem.

**Comment by scottaohara** [comment]
the idea that someone could override hiding a dialog by forcing it to be consistently display block, and then use a button within the dialog to toggle it between a modal / non-modal state made me stare at the wall for a good 15 minutes and reevaluate what i'm doing with my life.


but putting that aside...   ok sure, toggle/toggleModal are just quick defaults for auto so that people don't have to explicitly indicate that their buttons are supposed to close or dismiss

but #937 seems to need an answer to resolve this.  as i don't think it can be said that toggleModal will always do the right thing, if there two ways (close, cancel) to dismiss a dialog.

**Comment by lukewarlow** [comment]
Leaving on agenda to pick up next week

**Comment by lukewarlow** [comment]
If we do deprecate (remove) .show() from dialogs then we can drop the show and toggle actions entirely. That would also make this question effectively moot.

I guess you still have the <dialog open> case but if we remove .show() could we also make open on a dialog without popover not work?

**Comment by lukewarlow** [comment]
I've been thinking about this a bit more and I've gone back on my original stance and I think approach 2 is best. Ultimately the action when the dialog is open is "close" and that works either way when explicit. So toggle and toggleModal should do the same.

**Comment by lukewarlow** [comment]
@keithamus does this need any edits or can we just close as completed?

**Comment by keithamus** [comment]
I think we can mark this one as complete, yes.
