### ISSUE TITLE
[combobox] Is type="selectlist" correct for the input?

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#939]
I feel like adding a new input type doesn't really add anything?

Search feels appropriate?

**Comment by lukewarlow** [comment]
Alternatively I reckon at least call it combobox not selectlist. While they're similar they are distinct components.

**Comment by sudheer-gowrigari** [comment]
@gregwhitworth Let's use this issue for discussing all elements of combobox anatomy.?

**Comment by lukewarlow** [comment]
Thinking on this some more I think combobox should allow any type the user wants inside of its input. As the type attribute provides relevant validation.

If I want a telephone input that drops down with previously saved examples I want to get the free validation? (Might be a bad example I don't think telephone actually provides validation but you get the general idea)

**Comment by sudheer-gowrigari** [comment]
@lukewarlow In the case of `selectlist` the `type=selectlist` attribute indicates to the browser that this button should open the listbox. We need some kind of similar thing(either a unique attribute or type) even for combobox no?

**Comment by lukewarlow** [comment]
The key difference is selectlist is designed to support multiple buttons (split button design)
Whereas if someone puts 2 inputs into combobox they're asking for shenanigans and that's exactly what they'll get 😂.

**Comment by sudheer-gowrigari** [comment]
> The Open UI Community Group just discussed `[combobox] Is type="selectlist" correct for the input?`, and agreed to the following:
> 
> * `RESOLVED: the first button inside <select> triggers the popover. If there is more than one, use <button type=popover> to be the one that triggers the popover.`
> 
> The full IRC log of that discussion

We would like to reopen this discussion with reference to [this earlier comment](https://github.com/openui/open-ui/issues/839#issuecomment-1758381233). We believe the `combobox` should include:

- An input field with a "text" type for user entries.
- A button to display the selected option.
- An optional button to trigger a popover when clicked, represented by ⬇️.
```
<input type="text"> 
    <button><selectedoption></selectedoption></button>
   <button type=popover>⬇️</button>
</input>
```
Examples from Twitter and Facebook, where typing/clicking in the input field automatically triggers a popover.

https://github.com/openui/open-ui/assets/11438997/da9f1063-b57f-4791-9167-912599b9ce69



https://github.com/openui/open-ui/assets/11438997/59bf40dc-f3b2-4f25-9b17-6e9e65f06807
