### ISSUE TITLE
[invokers] Should synthesized clicks dispatch trusted invoke events?

### ISSUE THREAD

**Issue by keithamus** [openui/open-ui#946]
Currently the invoker implementations dispatch a trusted `invoke` event upon DOM Activation. This means it's possible to call `.click()` on a button and it'll dispatch a trusted `invoke` event. This makes sense because the invoke event is coming from the browser, but perhaps the invoke events trusted flag should reflect the source of the activation event.

This doesn't effect browsers security model, as they don't respond to events, but it may impact userland code as they may rely on `isTrusted` to ensure that this event was the result of a user gesture, which for invokers is currently not the case.

**Comment by lukewarlow** [comment]
We've got the answer to this earlier.

If the input that triggers invoke is trusted then propagate that else mark it as untrusted.
