### ISSUE TITLE
[invokers] Dialog's `toggle` needs a better name

### ISSUE THREAD

**Issue by keithamus** [openui/open-ui#956]
Invokers targeting a `<dialog>` can have `invokeaction=toggle`, which will open and close the dialog as non-modal.

`toggle` is a little ambiguous, especially as all other names are very clear in their action, `togglePopover`, `playpause`, etc.

Given https://github.com/whatwg/html/issues/9376 (Should we deprecate Dialog `show()`?) perhaps we can simply _not_ implement this?

If we are to implement this, it needs a clearer name. Some bad ideas to start the bidding:

 - `toggleNonModal`
 - `toggleOpen`
 - `toggleShow`

**Comment by lukewarlow** [comment]
I vote "don't implement". ToggleOpen isn't a perfect representation of what it does (given focusing) so I would vote against that.

**Comment by sashafirsov** [comment]
The separation of concerns IMO needs separate attributes: 
* ther aspect of visibility, i.e. switch the shown/hidden state
* the mode definition of how the dialog would be shown(modal/non-modal/inline)
* what should happen after the dialog completed(triggered) 

It is important as provide each functionality separately and do not mix those. As the imperative as **declarative** syntax for all. In this case declarative can be limited by allocation of DIALOG attributes.

# Open
`open` as name for visibility to match the other HTML elements like in [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element

# Toggle/Trigger
triggering the next UI on the `toggle` as pointer to the what should happen to element refered say by `for` attribute. Scenario:
* trigger the current dialog by setting `open=true` attribute
* get the ref element by `for` attribute
* get the target state of ref element from `toggle` attribute
* open/close the targer element, pass the focus

# Mode
the `modal` vs `popover` vs `inline` is rather the subject for `mode` attribute of Dialog.
