### ISSUE TITLE
[invokers] Casing for action values

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#969]
It was raised by Jake Archibald that the current action values might not match expectations. https://w3ctag.github.io/design-principles/#casing-rules specifically says that enumeration values should be kebab-case.

Should these be enumeration values?

If so how do we achieve the custom action naming requirements we resolved upon?

Potentially this is a question we should pose to the W3C tag review?

**Comment by mfreed7** [comment]
Quick comment - we discussed the double-dash naming scheme in WHATNOT just now, and the WHATWG folks are ok with that conclusion. So it sounds like we should just change the explainer and spec PR accordingly, to say `--foo` is a custom command name.

Side note: another suggestion was made, for `command: data-custom-name`. I.e. the prefix could be `data-`. My guess was that folks wouldn't like that idea much, but I could be wrong, so please chime in if you have strong feelings that `data-` would be a better choice for a prefix. Barring that, I think this issue and https://github.com/openui/open-ui/issues/954 can likely both be closed as Fixed, once the relevant PR edits have been made.
