### ISSUE TITLE
selectlist feedback from apple

### ISSUE THREAD

**Issue by josepharhar** [openui/open-ui#970]
I created a whatwg issue for selectlist here: https://github.com/whatwg/html/issues/9799

I have been discussing with Anne in the issue and offline, and I have agreed with him to make the following changes:
1. Reuse the `<select>` element instead of creating a new `<selectlist>` element
2. Reuse the `<datalist>` element instead of creating a `<listbox>` element for this element

Reusing the `<select>` element will work because of the new content model that we switched to in replacement of the behavior/slot/part attributes. We can update the HTML parser to allow `<button>` and `<datalist>` to be children of the `<select>` element.

I think that there are more arguments to be made for or against `<datalist>` instead of `<listbox>`, but Anne seemed more in favor of reusing `<datalist>`. Since reusing `<datalist>` can certainly fulfill all of our usecases for the select/selectlist project and would make it easier/faster to ship, I am receptive to reusing `<datalist>`.

Depending on how additional improvements for `<select>` go, I could also see us ending up with something like `<select size=n><datalist>...</datalist></select>` becoming a standalone `<listbox>`-like thing which could be the [aria-practices listbox](https://www.w3.org/WAI/ARIA/apg/patterns/listbox/) which people have been interested in. I haven't gotten feedback on this idea yet though.

I'd like to get a resolution that these two changes are ok.

**Comment by lukewarlow** [comment]
I would want a concrete solution to the potential compat issue of people applying the multiple attribute in these case?

Would it be possible to use legacy select rendering (e.g ignore button and datalist) when multiple is set likewise for size attribute.

Would that actually solve the issue?

**Comment by josepharhar** [comment]
I think that ideally we will make this `<button>` and `<datalist>` pattern work somehow for `<select multiple>` and `<select size>`, but in any case we will have to make it work in some particular way before we get to that point and after we ship plain `<select>` improvements, so yeah I suppose there will be some compat risk in the intermediate period.

It would certainly be possible to use legacy select rendering when the multiple or size attributes are set, and I imagine that's probably what we would end up implementing.

**Comment by lukewarlow** [comment]
So some further questions: 

- Would split button designs still work? 
- What type do we give button (type="select"?)?

**Comment by lukewarlow** [comment]
> I don't see how switching from listbox to datalist elements changes...

I guess difference is listbox doesn't have historical baggage of whatever the hell that is. Whereas datalist does. Was more just a hmm this'll need accounting for maybe
