### ISSUE TITLE
[combobox] Update proposal to use datalist not listbox

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#973]
As per https://github.com/openui/open-ui/issues/970 we've resolved to reuse select and datalist (with a long list of caveats but assuming it's possible).

We should update the combobox proposal to use datalist to match.

**Comment by sudheer-gowrigari** [comment]
Working on this https://github.com/openui/open-ui/pull/1025

**Comment by sudheer-gowrigari** [comment]
Anatamoy has now been updated to use datalist . Closing this now . cc: @gregwhitworth
