### ISSUE TITLE
[select] How to enable interoperable DOM, behaviors and user-agent styles for <select>

### ISSUE THREAD

**Issue by gregwhitworth** [openui/open-ui#985]
Definition of interoperable UI that ships in the web platform
==========================

Prior to outlining the potential solutions it’s important to outline the problem that we’re trying to solve. Open UI aims to introduce new solutions for fully styleable and extensible UI widgets that ship with HTML. In order to achieve this it requires standardized DOM, user-agent styles and behaviors.

Potential solutions
==========================

### 1. CSS appearance: base
Styling is one of the top reasons for taking on this initiative and the solution for this was to originally leverage a new appearance value of base. In recent discussions, for backwards compatibility we’ll need to introduce base-<widget> (eg: appearance: base-select).

**Pros**
* Easy Developer Experience
    * Allows `* { appearance: base-select, base-radio }`
* Has [Apple Support](https://github.com/openui/open-ui/issues/977#issuecomment-1899967646)

**Cons**
* This implies to the developer that the only thing changing are its styles but it’s also changing DOM and behaviors
* Update to the DOM and behaviors requires style computation which results in the engine having to go back to DOM creation which may lead to performance issues if many elements are leveraging this capability; or at a minimum this might make the implementation more complicated.

### 2. HTML attribute
Leverage a HTML attribute such as `<select base>` which results in the DOM, behaviors and subsequent styles in the user-agent style sheet

**Pros**
* Avoids needing to go do style calculation and then go back to DOM to result in an interoperable widget
* Allows interoperable DOM, behaviors and expanded capabilities without requiring interoperable styles

**Cons**
* Requires the developer to place the attribute on every element they want an interoperable DOM and styles
* This does not have multi-implementer support.

### 3. HTML element
Introduce a new element when interoperable DOM, behaviors and extended capabilities are desired. An example of this would be the originally proposed element `<selectlist>`.

**Pros**
* Avoids needing to go do style calculation and then go back to DOM to result in an interoperable widget
* Allows interoperable DOM, behaviors and expanded capabilities without requiring interoperable styles

**Cons**
* May result in developer confusion with more than one way to produce a similar widget
* Does not offer progressive enhancement
* This is [unlikely](https://github.com/whatwg/html/issues/9799#issuecomment-1770254871) to get multi-implementer interest

### 4. HTML Element or Attribute with interoperable styles by default
This is assuming that an attribute or element is used to produce interoperable DOM and behaviors. Introduce a new appearance value (eg: `appearance: ua-<widget>`) to allow developers to opt in to user-agent specific styling that is non-interoperable.

**Pros**
* Avoids having to do anything in CSS to result in interoperable styles by default
* As new elements are introduced the need for setting interoperable styles is not required

**Cons**
* Introduces inconsistencies in default behavior for HTML widgets

### 5. HTML markup divergence for adjusted elements that already exist
This one only applies to scenarios where there is already a widget in HTML that will be re-used. To use `<select>` as an example, when a `<datalist>` is parsed as a child of a `<select>` it will result in the interoperable DOM and behaviors.

**Pros**
* Avoids needing to go do style calculation and then go back to DOM to result in an interoperable widget
* Allows interoperable DOM, behaviors and expanded capabilities without requiring interoperable styles
* Provides progress enhancement

**Cons**
* May result in developer confusion since they’ll need to know the specific elements to add in order to trigger the interoperable experience
* The prior bullet is compounded by the potential of Javascript manipulation of the element which the component author may not have prepared for

Proposed Resolutions
==========================
### Interoperable DOM, Behaviors and Styles
1. Proposed Resolution: Introduction of a CSS property that changes the DOM, behaviors and styles to be made interoperable
2. Proposed Resolution: Introduction of new elements that have interoperable DOM, behaviors and styles by default. A new solution to be introduced to allow developers to opt-in to user-agent specific styles.
3. Proposed Resolution: Introduction of a new attribute that changes DOM, behaviors and styles with user-agent stylesheet referencing attribute (eg: `select[base] { /* interoperable styles */}`)

### Interoperable DOM & Behaviors 

> Note: Either of these resolutions also requires an interoperable style solution

1. Proposed Resolution: Introduction of a HTML attribute that results in interoperable DOM and behaviors
2. Proposed Resolution: Introduction of new elements or parser modifications of current semantic elements that result in interoperable DOM and behaviors

### Interoperable styles
1. Proposed Resolution: Introduce appearance: base-<widget> to result in interoperable styles

Related Discussions
===========================
1. [[appearance: user-agent] Opt-in to the current OSes control variant #689](https://github.com/openui/open-ui/issues/689)
2. [[css-ui] appearance: base to enable interoperable styling of controls/components #5998](https://github.com/w3c/csswg-drafts/issues/5998)
4. [Stylable <select> element #9799](https://github.com/whatwg/html/issues/9799)
5. [stylable select: What should we do about the multiple and size attributes? #977](https://github.com/openui/open-ui/issues/977)

**Comment by mfreed7** [comment]
Is the plan to take a live vote this Thursday?

**Comment by gregwhitworth** [comment]
@mfreed7 yes, the reason for this is that they're not ALL mutually exclusive (at least I don't view them that way) and so we may resolve on Thursday for `select` and our initial stance but I am curious about some of the arguments made that oppose certain solutions outside of the context of `select` or similar scenario.

**Comment by brechtDR** [comment]
I would like to make a small comment on this with an initial thought when hearing about the changes last time.

One thing I loved about the previous proposal was the idea to style the "listbox" and "button" using a pseudo element.

Reason: as a developer we sometimes need to work with third parties - for example - payment providers. It is common that when working with such external tools, we only get to add some CSS and cannot touch the HTML. Just saying that this is a feature that will be missed and could've been loved by many.

About the progressive enhancement. I am wondering if there is no chance to polyfill the old selectlist idea at all for older browsers.

I do believe an "opt-out" option for selectlist is more interesting than a "opt-in" option for a select

However, if going for an opt-in solution, i would like people to consider using an attribute rather than changing based behaviour based on children as an attribute would still give the ability to style certain elements such as button/marker/listbox with purely CSS. This would also be consistent with how the current switch implementation on Safari is. That consistency would be a nice bonus.

So for me personally: 
Still in love for the new element idea, if not, would love an attribute.
And in general I believe datalist could use some stylable improvements. Just not sure if this is the place for it or the thing that should trigger that

**Comment by mfreed7** [comment]
> **Reason:** As a developer we sometimes need to work with third parties - for example - payment providers. It is common that when working with such external tools, we only get to add some CSS and cannot touch the HTML. Just saying that pure CSS styling with pseudos is a feature that will be missed and could've been loved by many.

```css
select>datalist {
  /* put your datalist (popover) styles here */
}
select>button {
  /* put your select button styles here */
}
```

I'm unclear why we need pseudo elements to achieve "CSS only" styling of all the parts...?

If you mean that you need to touch the HTML to change `<select>` to `<select><datalist>`, then you'd also have to touch the HTML to change `<select>` to `<select newthing>`. Both are ~10 characters that need to be added to HTML, to opt your "old-style" select into the new "stylable" select shadow DOM structure. So perhaps you're arguing for option <span>#</span>1 above, where a CSS property opts you in to both styling and DOM structure?

**Comment by brechtDR** [comment]
> So perhaps you're arguing for option #1 above, where a CSS property opts you in to both styling and DOM structure?

Perhaps I am. It just felt so powerful and futuristic to do with pseudo elements. But as I stated before, I look at this with certain goggles. I also feel that some of the proposals are hard to explain (tutor) to people: "Adding a datalist to the select to make new things happen" is hard ...  That in itsef is not a viable argument, I am aware of that. Just sharing this thought / opinion.

**Comment by mfreed7** [comment]
> Perhaps I am. It just felt so powerful and futuristic to do with pseudo elements. But as I stated before, I look at this with certain goggles. I also feel that some of the proposals are hard to explain (tutor) to people: "Adding a datalist to the select to make new things happen" is hard ... That in itsef is not a viable argument, I am aware of that. Just sharing this thought / opinion.

Totally fair! Just to be clear, I wasn't trying to minimize your point, just understand it.

**Comment by gregwhitworth** [comment]
> That in itsef is not a viable argument, I am aware of that. Just sharing this thought / opinion. I know the idea of me liking what we had is not the popular route anymore. 🙂

@brechtDR This is a viable argument; just because there are many things about the web are confusing to teach to devs doesn't mean we should continue to introduce new ones.

That said, **I** will purposefully keep my position scoped to `<select>` and select the following, only if what @josepharhar mentioned is possible in that the shadow DOM could be interoperable without having to do style calculation:

> Proposed Resolution: Introduction of a CSS property that changes the DOM, behaviors and styles to be made interoperable

If it does require require going back to DOM construction then I prefer the attribute approach with user-agent styles referencing this attribute to set interoperable styles (eg: no introduction of a `base-<widget>` solution. I understand that an attribute is not preferred by some but to @brechtDR point the existence of `<datalist>` within a `<select>` making this switch doesn't make sense to me.

I am personally only a fan of any solution that changes DOM, Styles and behaviors at once (eg: I don't want a mix & match potential although I know some may want that).

**Comment by brechtDR** [comment]
@gregwhitworth I do have one question that is not completely answered in the document I think. Will we be able to add other elements inside of a styleable select? It can be handy to have an extra wrapper `<div>` for layout reasons to create a truly styleable select... I refer to a previous example I created: https://codepen.io/utilitybend/pen/PoXOzzw

**Comment by josepharhar** [comment]
> Will we be able to add other elements inside of a styleable select (more especially in the datalist)? 

Yes

> As a developer we sometimes need to work with third parties - for example - payment providers. It is common that when working with such external tools, we only get to add some CSS and cannot touch the HTML

> I'm unclear why we need pseudo elements to achieve "CSS only" styling of all the parts...?

Selectlist had pseudo elements and the new stylable select proposal doesn't have pseudo elements, but as mason showed in his example you can just target the button and datalist elements directly without the need for pseudo elements.

With selectlist, the opt in to the new behavior was to change the tag name from select to selectlist. With stylable select, the opt in is to add button and datalist elements. If the HTML of the website opts in, either with the old selectlist proposal with pseudo elements, or the new stylable select proposal, then you are guaranteed to be able to style the button and listbox with either proposal.

**Comment by flackr** [comment]
It's also possible to combine solutions 2 and 3, in a very analogous way to `<input type=button value="click me">` and `<button>click me</button>`.

The attribute allows you to create a `<select type=list>` that supports progressive enhancment (note, I'm using type, to further draw the analogy to input, but of course the attribute doesn't have to be type), or if you have an alternative fallback or in the future where every browser supports it, you can use `<selectlist>` or some other new element which is only ever the new thing.

This can of course be done anytime after adding the attribute.

**Comment by brechtDR** [comment]
I think most of my "worries" are gone now. I do like the idea by @flackr as well. For me though, it still feels strange to me putting a datalist in there instead of a more declarative name in a new element such as "listbox". But that's rather a feeling than something that is objective.
