### ISSUE TITLE
[invokers] bikeshed the attribute names.

### ISSUE THREAD

**Issue by keithamus** [openui/open-ui#998]
I’ve had a couple of mentions on social media, about bikeshedding the `invoketarget` and `invokeaction` names. Rather than keep that discourse on those social media platforms I thought I’d bring it here to be discussed.

[This post](https://x.com/Mr__Disagree/status/1708998764634001913) talks about using `for=` instead of `invoketarget=`. 

[This post](https://x.com/darylbarnes/status/1760713538463522832) talks about using `target=` instead of `invoketarget=` and `action=` instead of `invokeaction=`. 

I have reservations for both but to promote good critical discourse I thought I’d share so we have a canonical place to discuss the colour of this bikeshed.

**Comment by lukewarlow** [comment]
I'm against using `for` or `target` because it precludes multiple types of targets on one element. If you want interesttarget AND invoketarget together you need the specificity.

formaction for example is formaction NOT just action. It's only `action` when used on the form element itself.

**Comment by keithamus** [comment]
https://x.com/Keithamus/status/1791565930528440514

https://indieweb.social/@keithamus/112458309173840363

I ran a couple of polls to try and gather some off-the-cuff opinions. Especailly WRT https://github.com/whatwg/html/issues/9625#issuecomment-2115718679. While the polls have not yet ended I thought I'd gather some of the commentary:

Some notes on the discussions & results:

 - Many comments mentioned `clickaction` is confusing with regard to input:
   - > “clickaction” isn’t really right (it’s not always a click, and the click event would be called something different if named today)
   - > Is click action only *invoked* when clicking or can the keyboard *invoke* it too?
   - > Command is independent of input device (which I hope the code is, too). So is invoke but it feels harder to read and more passive.
   - > It should not be click because the action might not be a click (ie mobile, keyboard, etc.).
   - > Click seems too specific
   - > oh no invoke and click are tied.
   - > Yeah it's not always a click. click JS events do fire for buttons when keyboard activated but that's not true for any other elements (certainly not all elements).
   - > I don’t think click is right because it could be actions other than a click. I think invoke is probably the best option.
   - > Click is non-semantic if invoking the action can be done by focus+enter or anything else.
   - > Not everyone uses a mouse to activate a button so I voted for "invoke", which is what the button does.
 
- Some comments mentioned "invoke" was too confusing a name/concept:
   - > So is invoke but it feels harder to read and more passive.
   - > because “invokeaction” is unbearably techie (and sounds like it’s trying to be “invocation”, which sounds a lot cooler (a magic spell!) but not very professional

The replies contain a lot of ideas for alternate names, here are the most promiment:

- `type=foo`.
  - However we're not sure this is worth pursuing due to the complexity & compat risk.
- `do=foo`
  - I don't have strong opinions on this. While it's short, it may be _too_ ambigious.
- `action=foo`.
  - Some people explicitly mentioned the symmetry with `formaction=` and felt it gelled well with existing platform primitives. Obviously they do very different things.
  - This idea seems worth exploring; a button can have `action=`, `formaction=`, `interestaction=`, but the symmetry is lost with targets which would likely be `actiontarget=`, `form=`, `interesttarget=`.

**Comment by annevk** [comment]
The arguments against `click` are mostly about it not being device-independent, but the web platform `click` is device-independent as settled long ago. (And some of the comments you included there seem to apply to `invoke` instead or to both.)

**Comment by hax** [comment]
Indeed, `click` is already device-independent, so technically speaking, `clickaction` is not an issue. However, ordinary developers might not necessarily understand this point. On the other hand, the name `clickactiontarget` is a bit lengthy (and due to naming conventions being all lowercase without separation, it also makes reading a bit more difficult). So I would slightly prefer `invoketarget` and `invokeaction`. Though I also much like shorter names like `<button do="close" for="my-dialog">`

**Comment by zcorpan** [comment]
I'm OK with the current names, but something like `command` and `commandtarget` (or `commandfor`) could work too.

**Comment by mfreed7** [comment]
Please see https://github.com/whatwg/html/issues/9625#issuecomment-2127894305

**Comment by gregwhitworth** [comment]
@keithamus @mfreed7 just read through the novel that is the WHATWG thread. Looks like the naming is cemented. Is there a reason to keep this issue open any longer?

**Comment by keithamus** [comment]
We can close for now. We can re-open this if we need to.

For posterity: WHATWG resolved to explore `commandfor` and `command` over `invoketarget` and `invokeaction` respectively.
