### ISSUE TITLE
[interest invokers] Do we need an interestaction attribute?

### ISSUE THREAD

**Issue by lukewarlow** [openui/open-ui#999]
Currently the [interest invokers](https://open-ui.org/components/interest-invokers.explainer/) explainer doesn't include an `interestaction` attribute. While this makes sense as it's always "toggle"/"auto" for v1 browser actions, doesn't that preclude custom actions and also go against the premise that custom actions would have naming requirements?

cc @keithamus

**Comment by mfreed7** [comment]
We could just re-use the `invokeaction` attribute, perhaps? It would still be the "action" taken when the element is "invoked", just via "interest" this time.

**Comment by lukewarlow** [comment]
That precludes using both invokers and interest on the same element but for different actions right?

**Comment by mfreed7** [comment]
Yep, you're right. I guess this does need a fresh/different attribute.
